/**
 * DesignedCardGrid — renders a grid of cards using a CardTemplate.
 *
 * Each card is laid out according to the template's zone list,
 * using reusable CardPart components for each visible zone.
 * Compatible with LandingItem[] generated by mapRowsToItems().
 */
import type { LandingItem, CardTemplate, CardZone } from "../types";
import { migrateCardTemplate } from "../types";
import {
  CardPartImage,
  CardPartHeading,
  CardPartSubheading,
  CardPartIcon,
  CardPartLink,
} from "../card-parts";
import "./DesignedCardGrid.css";

interface DesignedCardGridProps {
  items: LandingItem[];
  template: CardTemplate;
}

function renderZone(zone: CardZone, item: LandingItem) {
  if (!zone.visible) return null;

  switch (zone.field) {
    case "heading":
      return (
        <CardPartHeading
          key="heading"
          text={item.heading}
          align={zone.align}
          size={zone.size}
        />
      );
    case "subheading":
      return (
        <CardPartSubheading
          key="subheading"
          text={item.subheading}
          align={zone.align}
          size={zone.size}
        />
      );
    case "icon":
      return (
        <CardPartIcon
          key="icon"
          icon={item.icon}
          align={zone.align}
          size={zone.size}
        />
      );
    case "link_url":
      return (
        <CardPartLink
          key="link_url"
          url={item.link_url}
          align={zone.align}
          size={zone.size}
        />
      );
    case "image_url":
      // image_url in body zones (non-positional) renders inline
      return (
        <CardPartImage
          key="image_url"
          src={item.image_url}
          alt={item.heading}
          align={zone.align}
          size={zone.size}
        />
      );
    default:
      return null;
  }
}

const DesignedCard = ({
  item,
  template: rawTemplate,
}: {
  item: LandingItem;
  template: CardTemplate;
}) => {
  const template = migrateCardTemplate(rawTemplate);
  const {
    zones,
    gap,
    imagePosition,
    minHeight,
    maxHeight,
    aspectRatio,
    paddingTop,
    paddingRight,
    paddingBottom,
    paddingLeft,
    borderRadius,
    cardStyle,
    overflow,
    contentAlign,
    imageHeight,
  } = template;

  // Separate image zone from body zones
  const imageZone = zones.find((z) => z.field === "image_url");
  const bodyZones = zones.filter((z) => z.field !== "image_url" && z.visible);

  const showImage = imagePosition !== "none" && imageZone?.visible !== false;

  const styleClass =
    cardStyle && cardStyle !== "default" ? ` dcard--${cardStyle}` : "";
  const customCssClass = template.customCss ? " dcard--custom-css" : "";

  const cardCss: React.CSSProperties = {
    minHeight: minHeight ? `${minHeight}px` : undefined,
    maxHeight: maxHeight ? `${maxHeight}px` : undefined,
    aspectRatio:
      aspectRatio && aspectRatio !== "auto" ? aspectRatio : undefined,
    borderRadius: `${borderRadius ?? 16}px`,
    overflow: overflow ?? "hidden",
    margin: `${template.marginTop ?? 0}px ${template.marginRight ?? 0}px ${template.marginBottom ?? 0}px ${template.marginLeft ?? 0}px`,
  };

  const bodyStyle: React.CSSProperties = {
    gap: `${gap}px`,
    padding: `${paddingTop ?? 0}px ${paddingRight ?? 16}px ${paddingBottom ?? 16}px ${paddingLeft ?? 16}px`,
    justifyContent: contentAlign === "stretch" ? undefined : contentAlign,
    alignItems: contentAlign === "stretch" ? "stretch" : undefined,
  };

  return (
    <div
      className={`dcard card card--interactive dcard--${template.cardWidth}${styleClass}${customCssClass}`}
      style={cardCss}
    >
      {/* Background image mode */}
      {showImage && imagePosition === "background" && (
        <CardPartImage
          src={item.image_url}
          alt={item.heading}
          align={imageZone?.align}
          size={imageZone?.size}
          position="background"
          fixedHeight={imageHeight}
        />
      )}

      {/* Top image */}
      {showImage && imagePosition === "top" && (
        <CardPartImage
          src={item.image_url}
          alt={item.heading}
          align={imageZone?.align}
          size={imageZone?.size}
          position="top"
          fixedHeight={imageHeight}
        />
      )}

      {/* Body zones */}
      <div
        className={`dcard__body${imagePosition === "background" ? " dcard__body--overlay" : ""}`}
        style={bodyStyle}
      >
        {bodyZones.map((zone) => renderZone(zone, item))}
      </div>

      {/* Bottom image */}
      {showImage && imagePosition === "bottom" && (
        <CardPartImage
          src={item.image_url}
          alt={item.heading}
          align={imageZone?.align}
          size={imageZone?.size}
          position="bottom"
          fixedHeight={imageHeight}
        />
      )}
    </div>
  );
};

export const DesignedCardGrid = ({
  items,
  template: rawTemplate,
}: DesignedCardGridProps) => {
  const template = migrateCardTemplate(rawTemplate);
  const gridStyle: React.CSSProperties = {
    gap: `${template.gridGap ?? 24}px`,
  };

  return (
    <div className="dcard-grid" style={gridStyle}>
      {template.customCss ? <style>{template.customCss}</style> : null}
      {items.map((item, index) => (
        <DesignedCard key={item.id ?? index} item={item} template={template} />
      ))}
    </div>
  );
};
