/**
 * DesignedCardGrid — renders a grid of cards using a CardTemplate.
 *
 * Each card is laid out according to the template's zone list,
 * using reusable CardPart components for each visible zone.
 * Compatible with LandingItem[] generated by mapRowsToItems().
 */
import type { LandingItem, CardTemplate, CardZone } from "../types";
import {
  CardPartImage,
  CardPartHeading,
  CardPartSubheading,
  CardPartIcon,
  CardPartLink,
} from "../card-parts";
import "./DesignedCardGrid.css";

interface DesignedCardGridProps {
  items: LandingItem[];
  template: CardTemplate;
}

function renderZone(zone: CardZone, item: LandingItem) {
  if (!zone.visible) return null;

  switch (zone.field) {
    case "heading":
      return (
        <CardPartHeading
          key="heading"
          text={item.heading}
          align={zone.align}
          size={zone.size}
        />
      );
    case "subheading":
      return (
        <CardPartSubheading
          key="subheading"
          text={item.subheading}
          align={zone.align}
          size={zone.size}
        />
      );
    case "icon":
      return (
        <CardPartIcon
          key="icon"
          icon={item.icon}
          align={zone.align}
          size={zone.size}
        />
      );
    case "link_url":
      return (
        <CardPartLink
          key="link_url"
          url={item.link_url}
          align={zone.align}
          size={zone.size}
        />
      );
    case "image_url":
      // image_url in body zones (non-positional) renders inline
      return (
        <CardPartImage
          key="image_url"
          src={item.image_url}
          alt={item.heading}
          align={zone.align}
          size={zone.size}
        />
      );
    default:
      return null;
  }
}

const DesignedCard = ({
  item,
  template,
}: {
  item: LandingItem;
  template: CardTemplate;
}) => {
  const { zones, gap, padding, imagePosition, minHeight, aspectRatio } =
    template;

  // Separate image zone from body zones
  const imageZone = zones.find((z) => z.field === "image_url");
  const bodyZones = zones.filter((z) => z.field !== "image_url" && z.visible);

  const showImage = imagePosition !== "none" && imageZone?.visible !== false;

  const cardStyle: React.CSSProperties = {
    minHeight: minHeight ? `${minHeight}px` : undefined,
    aspectRatio:
      aspectRatio && aspectRatio !== "auto" ? aspectRatio : undefined,
  };

  const bodyStyle: React.CSSProperties = {
    gap: `${gap}px`,
    padding: `${padding}px`,
  };

  return (
    <div
      className={`dcard card card--interactive dcard--${template.cardWidth}`}
      style={cardStyle}
    >
      {/* Background image mode */}
      {showImage && imagePosition === "background" && (
        <CardPartImage
          src={item.image_url}
          alt={item.heading}
          align={imageZone?.align}
          size={imageZone?.size}
          position="background"
        />
      )}

      {/* Top image */}
      {showImage && imagePosition === "top" && (
        <CardPartImage
          src={item.image_url}
          alt={item.heading}
          align={imageZone?.align}
          size={imageZone?.size}
          position="top"
        />
      )}

      {/* Body zones */}
      <div
        className={`dcard__body${imagePosition === "background" ? " dcard__body--overlay" : ""}`}
        style={bodyStyle}
      >
        {bodyZones.map((zone) => renderZone(zone, item))}
      </div>

      {/* Bottom image */}
      {showImage && imagePosition === "bottom" && (
        <CardPartImage
          src={item.image_url}
          alt={item.heading}
          align={imageZone?.align}
          size={imageZone?.size}
          position="bottom"
        />
      )}
    </div>
  );
};

export const DesignedCardGrid = ({
  items,
  template,
}: DesignedCardGridProps) => (
  <div className="dcard-grid">
    {items.map((item, index) => (
      <DesignedCard key={item.id ?? index} item={item} template={template} />
    ))}
  </div>
);
