// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: pkg/grpc/proto/skaia.proto

package skaia

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ----------------------------------------------------
// GrengoService Messages
// ----------------------------------------------------
type ReportStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportStatusRequest) Reset() {
	*x = ReportStatusRequest{}
	mi := &file_pkg_grpc_proto_skaia_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportStatusRequest) ProtoMessage() {}

func (x *ReportStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_skaia_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportStatusRequest.ProtoReflect.Descriptor instead.
func (*ReportStatusRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_skaia_proto_rawDescGZIP(), []int{0}
}

func (x *ReportStatusRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ReportStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ReportStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportStatusResponse) Reset() {
	*x = ReportStatusResponse{}
	mi := &file_pkg_grpc_proto_skaia_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportStatusResponse) ProtoMessage() {}

func (x *ReportStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_skaia_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportStatusResponse.ProtoReflect.Descriptor instead.
func (*ReportStatusResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_skaia_proto_rawDescGZIP(), []int{1}
}

func (x *ReportStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// ----------------------------------------------------
// BackendService Messages
// ----------------------------------------------------
type GetStorageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStorageRequest) Reset() {
	*x = GetStorageRequest{}
	mi := &file_pkg_grpc_proto_skaia_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStorageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStorageRequest) ProtoMessage() {}

func (x *GetStorageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_skaia_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStorageRequest.ProtoReflect.Descriptor instead.
func (*GetStorageRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_skaia_proto_rawDescGZIP(), []int{2}
}

type GetStorageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// We can serialize the existing JSON response or define strict fields
	StorageJson   string `protobuf:"bytes,1,opt,name=storage_json,json=storageJson,proto3" json:"storage_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStorageResponse) Reset() {
	*x = GetStorageResponse{}
	mi := &file_pkg_grpc_proto_skaia_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStorageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStorageResponse) ProtoMessage() {}

func (x *GetStorageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_skaia_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStorageResponse.ProtoReflect.Descriptor instead.
func (*GetStorageResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_skaia_proto_rawDescGZIP(), []int{3}
}

func (x *GetStorageResponse) GetStorageJson() string {
	if x != nil {
		return x.StorageJson
	}
	return ""
}

// ----------------------------------------------------
// GoFTWService Messages
// ----------------------------------------------------
type LogStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        string                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogStreamResponse) Reset() {
	*x = LogStreamResponse{}
	mi := &file_pkg_grpc_proto_skaia_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogStreamResponse) ProtoMessage() {}

func (x *LogStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_skaia_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogStreamResponse.ProtoReflect.Descriptor instead.
func (*LogStreamResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_skaia_proto_rawDescGZIP(), []int{4}
}

func (x *LogStreamResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

type SetupInitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Branch        string                 `protobuf:"bytes,1,opt,name=branch,proto3" json:"branch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetupInitRequest) Reset() {
	*x = SetupInitRequest{}
	mi := &file_pkg_grpc_proto_skaia_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetupInitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupInitRequest) ProtoMessage() {}

func (x *SetupInitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_skaia_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupInitRequest.ProtoReflect.Descriptor instead.
func (*SetupInitRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_skaia_proto_rawDescGZIP(), []int{5}
}

func (x *SetupInitRequest) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

type CheckoutSitesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckoutSitesRequest) Reset() {
	*x = CheckoutSitesRequest{}
	mi := &file_pkg_grpc_proto_skaia_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckoutSitesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckoutSitesRequest) ProtoMessage() {}

func (x *CheckoutSitesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_skaia_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckoutSitesRequest.ProtoReflect.Descriptor instead.
func (*CheckoutSitesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_skaia_proto_rawDescGZIP(), []int{6}
}

type StartDeploymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deployment    string                 `protobuf:"bytes,1,opt,name=deployment,proto3" json:"deployment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartDeploymentRequest) Reset() {
	*x = StartDeploymentRequest{}
	mi := &file_pkg_grpc_proto_skaia_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartDeploymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartDeploymentRequest) ProtoMessage() {}

func (x *StartDeploymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_skaia_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartDeploymentRequest.ProtoReflect.Descriptor instead.
func (*StartDeploymentRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_skaia_proto_rawDescGZIP(), []int{7}
}

func (x *StartDeploymentRequest) GetDeployment() string {
	if x != nil {
		return x.Deployment
	}
	return ""
}

type InstallAppsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SiteName      string                 `protobuf:"bytes,1,opt,name=site_name,json=siteName,proto3" json:"site_name,omitempty"`
	Apps          []string               `protobuf:"bytes,2,rep,name=apps,proto3" json:"apps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallAppsRequest) Reset() {
	*x = InstallAppsRequest{}
	mi := &file_pkg_grpc_proto_skaia_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallAppsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallAppsRequest) ProtoMessage() {}

func (x *InstallAppsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_skaia_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallAppsRequest.ProtoReflect.Descriptor instead.
func (*InstallAppsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_skaia_proto_rawDescGZIP(), []int{8}
}

func (x *InstallAppsRequest) GetSiteName() string {
	if x != nil {
		return x.SiteName
	}
	return ""
}

func (x *InstallAppsRequest) GetApps() []string {
	if x != nil {
		return x.Apps
	}
	return nil
}

var File_pkg_grpc_proto_skaia_proto protoreflect.FileDescriptor

const file_pkg_grpc_proto_skaia_proto_rawDesc = "" +
	"\n" +
	"\x1apkg/grpc/proto/skaia.proto\x12\n" +
	"skaia.grpc\"F\n" +
	"\x13ReportStatusRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"0\n" +
	"\x14ReportStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x13\n" +
	"\x11GetStorageRequest\"7\n" +
	"\x12GetStorageResponse\x12!\n" +
	"\fstorage_json\x18\x01 \x01(\tR\vstorageJson\"+\n" +
	"\x11LogStreamResponse\x12\x16\n" +
	"\x06output\x18\x01 \x01(\tR\x06output\"*\n" +
	"\x10SetupInitRequest\x12\x16\n" +
	"\x06branch\x18\x01 \x01(\tR\x06branch\"\x16\n" +
	"\x14CheckoutSitesRequest\"8\n" +
	"\x16StartDeploymentRequest\x12\x1e\n" +
	"\n" +
	"deployment\x18\x01 \x01(\tR\n" +
	"deployment\"E\n" +
	"\x12InstallAppsRequest\x12\x1b\n" +
	"\tsite_name\x18\x01 \x01(\tR\bsiteName\x12\x12\n" +
	"\x04apps\x18\x02 \x03(\tR\x04apps2b\n" +
	"\rGrengoService\x12Q\n" +
	"\fReportStatus\x12\x1f.skaia.grpc.ReportStatusRequest\x1a .skaia.grpc.ReportStatusResponse2]\n" +
	"\x0eBackendService\x12K\n" +
	"\n" +
	"GetStorage\x12\x1d.skaia.grpc.GetStorageRequest\x1a\x1e.skaia.grpc.GetStorageResponse2\xd6\x02\n" +
	"\fGoFTWService\x12J\n" +
	"\tSetupInit\x12\x1c.skaia.grpc.SetupInitRequest\x1a\x1d.skaia.grpc.LogStreamResponse0\x01\x12R\n" +
	"\rCheckoutSites\x12 .skaia.grpc.CheckoutSitesRequest\x1a\x1d.skaia.grpc.LogStreamResponse0\x01\x12V\n" +
	"\x0fStartDeployment\x12\".skaia.grpc.StartDeploymentRequest\x1a\x1d.skaia.grpc.LogStreamResponse0\x01\x12N\n" +
	"\vInstallApps\x12\x1e.skaia.grpc.InstallAppsRequest\x1a\x1d.skaia.grpc.LogStreamResponse0\x01B\x1dZ\x1bgithub.com/skaia/grpc/skaiab\x06proto3"

var (
	file_pkg_grpc_proto_skaia_proto_rawDescOnce sync.Once
	file_pkg_grpc_proto_skaia_proto_rawDescData []byte
)

func file_pkg_grpc_proto_skaia_proto_rawDescGZIP() []byte {
	file_pkg_grpc_proto_skaia_proto_rawDescOnce.Do(func() {
		file_pkg_grpc_proto_skaia_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_grpc_proto_skaia_proto_rawDesc), len(file_pkg_grpc_proto_skaia_proto_rawDesc)))
	})
	return file_pkg_grpc_proto_skaia_proto_rawDescData
}

var file_pkg_grpc_proto_skaia_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pkg_grpc_proto_skaia_proto_goTypes = []any{
	(*ReportStatusRequest)(nil),    // 0: skaia.grpc.ReportStatusRequest
	(*ReportStatusResponse)(nil),   // 1: skaia.grpc.ReportStatusResponse
	(*GetStorageRequest)(nil),      // 2: skaia.grpc.GetStorageRequest
	(*GetStorageResponse)(nil),     // 3: skaia.grpc.GetStorageResponse
	(*LogStreamResponse)(nil),      // 4: skaia.grpc.LogStreamResponse
	(*SetupInitRequest)(nil),       // 5: skaia.grpc.SetupInitRequest
	(*CheckoutSitesRequest)(nil),   // 6: skaia.grpc.CheckoutSitesRequest
	(*StartDeploymentRequest)(nil), // 7: skaia.grpc.StartDeploymentRequest
	(*InstallAppsRequest)(nil),     // 8: skaia.grpc.InstallAppsRequest
}
var file_pkg_grpc_proto_skaia_proto_depIdxs = []int32{
	0, // 0: skaia.grpc.GrengoService.ReportStatus:input_type -> skaia.grpc.ReportStatusRequest
	2, // 1: skaia.grpc.BackendService.GetStorage:input_type -> skaia.grpc.GetStorageRequest
	5, // 2: skaia.grpc.GoFTWService.SetupInit:input_type -> skaia.grpc.SetupInitRequest
	6, // 3: skaia.grpc.GoFTWService.CheckoutSites:input_type -> skaia.grpc.CheckoutSitesRequest
	7, // 4: skaia.grpc.GoFTWService.StartDeployment:input_type -> skaia.grpc.StartDeploymentRequest
	8, // 5: skaia.grpc.GoFTWService.InstallApps:input_type -> skaia.grpc.InstallAppsRequest
	1, // 6: skaia.grpc.GrengoService.ReportStatus:output_type -> skaia.grpc.ReportStatusResponse
	3, // 7: skaia.grpc.BackendService.GetStorage:output_type -> skaia.grpc.GetStorageResponse
	4, // 8: skaia.grpc.GoFTWService.SetupInit:output_type -> skaia.grpc.LogStreamResponse
	4, // 9: skaia.grpc.GoFTWService.CheckoutSites:output_type -> skaia.grpc.LogStreamResponse
	4, // 10: skaia.grpc.GoFTWService.StartDeployment:output_type -> skaia.grpc.LogStreamResponse
	4, // 11: skaia.grpc.GoFTWService.InstallApps:output_type -> skaia.grpc.LogStreamResponse
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_grpc_proto_skaia_proto_init() }
func file_pkg_grpc_proto_skaia_proto_init() {
	if File_pkg_grpc_proto_skaia_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_grpc_proto_skaia_proto_rawDesc), len(file_pkg_grpc_proto_skaia_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_pkg_grpc_proto_skaia_proto_goTypes,
		DependencyIndexes: file_pkg_grpc_proto_skaia_proto_depIdxs,
		MessageInfos:      file_pkg_grpc_proto_skaia_proto_msgTypes,
	}.Build()
	File_pkg_grpc_proto_skaia_proto = out.File
	file_pkg_grpc_proto_skaia_proto_goTypes = nil
	file_pkg_grpc_proto_skaia_proto_depIdxs = nil
}
