package main

import (
    "fmt"
    "os"
    "path/filepath"
    "strings"
)

func generateNginxConfig() {
	dir := nginxDir()
	if err := os.MkdirAll(dir, 0755); err != nil {
		die("Cannot create nginx directory: %v", err)
	}
	confPath := filepath.Join(dir, "default.conf")

	clients := enabledClients()

	if len(clients) == 0 {
		fallback := `server { listen 80 default_server; return 503 "No backends configured – run: grengo new <name>\n"; }` + "\n"
		if err := os.WriteFile(confPath, []byte(fallback), 0644); err != nil {
			die("Cannot write nginx config: %v", err)
		}
		log("nginx fallback written => %s", confPath)
		return
	}

	var b strings.Builder
	b.WriteString("# Auto-generated by grengo\n")
	b.WriteString("# Do not edit manually; run 'grengo nginx reload' to regenerate.\n\n")

	// gzip
	b.WriteString(`# ── gzip ───────────────────────────────────────────────────────────────────
gzip              on;
gzip_comp_level   5;
gzip_min_length   256;
gzip_vary         on;
gzip_proxied      any;
gzip_types
    text/plain text/css text/javascript text/xml
    application/javascript application/json
    application/xml application/xml+rss application/wasm
    image/svg+xml font/woff2;

`)

	// WebSocket upgrade map
	b.WriteString(`# ── WebSocket upgrade ─────────────────────────────────────────────────────
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

`)

	// Upload cache
	b.WriteString(`# ── Upload cache ──────────────────────────────────────────────────────────
proxy_cache_path /var/cache/nginx/uploads
                 levels=1:2 keys_zone=uploads_cache:10m
                 max_size=1g inactive=30d use_temp_path=off;

`)

	for i, c := range clients {
		serverNames := c.Domains
		if len(serverNames) == 0 {
			serverNames = []string{"_"}
		}
        listenDirective := "listen 80;"
        if i == 0 {
            listenDirective = "listen 80 default_server;"
        }
		fmt.Fprintf(&b, "server {\n    %s\n    server_name %s;\n    client_max_body_size 0;\n\n", listenDirective, strings.Join(serverNames, " "))

		b.WriteString(`    # Security headers
    add_header X-Frame-Options        "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy        "strict-origin-when-cross-origin" always;
    add_header Permissions-Policy     "camera=(), microphone=(self), geolocation=()" always;

`)

		fmt.Fprintf(&b, `    # ── Uploads (cached) ──────────────────────────────────────────────────
    location ^~ /uploads/ {
        proxy_pass         http://127.0.0.1:%s;
        proxy_http_version 1.1;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_set_header   Connection        "";

        proxy_cache           uploads_cache;
        proxy_cache_valid     200 30d;
        proxy_cache_valid     404 1m;
        proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;
        proxy_cache_lock      on;
        add_header X-Cache-Status $upstream_cache_status;
        expires 30d;
        add_header Cache-Control "public";
        add_header X-Content-Type-Options "nosniff" always;
        access_log off;
    }

`, c.Port)

		fmt.Fprintf(&b, `    # ── API ───────────────────────────────────────────────────────────────
    location /api/ {
        proxy_pass         http://127.0.0.1:%s;
        proxy_http_version 1.1;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_set_header   Connection        "";
        proxy_buffering    on;
        proxy_buffer_size  16k;
        proxy_buffers      8 16k;

        # Chunked upload completion can take minutes for large files
        proxy_read_timeout 3600;
        proxy_send_timeout 3600;

        # Prevent CDN / browser caching of API responses
        add_header Cache-Control "no-store, no-cache, must-revalidate" always;
        add_header Pragma        "no-cache" always;
    }

    # ── Downloads (No Buffering) ──────────────────────────────────────────
    location ~ ^/api/s/.*/(?:exports|jobs)/.*/download$ {
        proxy_pass         http://127.0.0.1:%s;
        proxy_http_version 1.1;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_set_header   Connection        "";
        proxy_buffering    off;
        
        # Prevent timeouts during long downloads
        proxy_read_timeout 3600;
        proxy_send_timeout 3600;
    }

    # ── Config / page endpoints ───────────────────────────────────────────
    location /config/ {
        proxy_pass         http://127.0.0.1:%s;
        proxy_http_version 1.1;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_set_header   Connection        "";

        # Prevent CDN / browser caching of config responses
        add_header Cache-Control "no-store, no-cache, must-revalidate" always;
        add_header Pragma        "no-cache" always;
    }

`, c.Port, c.Port, c.Port)

		fmt.Fprintf(&b, `    # ── WebSocket ─────────────────────────────────────────────────────────
    location = /ws {
        proxy_pass         http://127.0.0.1:%s;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade           $http_upgrade;
        proxy_set_header   Connection        $connection_upgrade;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_read_timeout 86400s;
        proxy_send_timeout 86400s;
    }

    location = /api/ws {
        proxy_pass         http://127.0.0.1:%s;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade           $http_upgrade;
        proxy_set_header   Connection        $connection_upgrade;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_read_timeout 86400s;
        proxy_send_timeout 86400s;
    }

`, c.Port, c.Port)

		fmt.Fprintf(&b, `    # ── Health ────────────────────────────────────────────────────────────
    location = /health {
        proxy_pass         http://127.0.0.1:%s;
        proxy_http_version 1.1;
        proxy_set_header   Host        $host;
        proxy_set_header   Connection  "";
    }

`, c.Port)

		fmt.Fprintf(&b, `    # ── Catch-all => SSR / SPA ────────────────────────────────────────────
    location / {
        proxy_pass         http://127.0.0.1:%s;
        proxy_http_version 1.1;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_set_header   Connection        "";
        proxy_buffering    off;
        proxy_buffer_size  16k;
        proxy_buffers      8 16k;
    }
}
`, c.Port)
	}

	if err := os.WriteFile(confPath, []byte(b.String()), 0644); err != nil {
		die("Cannot write nginx config: %v", err)
	}
	log("nginx config written => %s", confPath)
}
