package textpolicy

import (
	"os"
	"os/exec"
	"path/filepath"
	"testing"
)

func TestCheckCoreRules(t *testing.T) {
	data := []byte("// heading\n\nvalue := \"bad\u2014\u2192\U0001f600\" \t\n<<<<<<< HEAD\n")
	violations := Check("sample.go", data, false)
	want := map[Rule]bool{
		RuleBlankAfterComment: true,
		RuleConflictMarker:    true,
		RuleEmoji:             true,
		RuleEmDash:            true,
		RuleRightArrow:        true,
		RuleTrailingSpace:     true,
	}
	for _, violation := range violations {
		delete(want, violation.Rule)
	}
	for rule := range want {
		t.Errorf("missing violation for %s", rule)
	}
}

func TestCheckCommentStyles(t *testing.T) {
	tests := []struct {
		path string
		data string
	}{
		{path: "main.go", data: "// ----------\npackage main\n"},
		{path: "app.ts", data: "/* ===== */\nconst ok = true;\n"},
		{path: "tool.sh", data: "# ______\necho ok\n"},
		{path: "config.yaml", data: "# *****\nkey: value\n"},
		{path: "Dockerfile", data: "# =====\nFROM scratch\n"},
	}
	for _, test := range tests {
		t.Run(test.path, func(t *testing.T) {
			violations := Check(test.path, []byte(test.data), true)
			if !hasRule(violations, RuleDecorativeComment) {
				t.Fatalf("expected decorative comment violation, got %#v", violations)
			}
		})
	}
}

func TestCheckRejectsMultilineCommentBanner(t *testing.T) {
	data := []byte("//\n// Section\n//\nconst value = true\n")
	violations := Check("sample.ts", data, true)
	if !hasRule(violations, RuleDecorativeComment) {
		t.Fatalf("expected multiline banner violation, got %#v", violations)
	}
}

func TestCheckRejectsLabeledAndEmbeddedDecorativeRuns(t *testing.T) {
	tests := []struct {
		path string
		data string
	}{
		{path: "sample.go", data: "// \u2500\u2500 Tier 1: Jail \u2500\u2500\u2500\u2500\u2500\npackage sample\n"},
		{path: "sample.ts", data: "// Section ----------\nconst value = true;\n"},
		{path: "sample.css", data: "/* == Section ===== */\n.value {}\n"},
		{path: "multiline.css", data: "/* Section\n   ========== */\n.value {}\n"},
		{path: "sample.proto", data: "// Message -----\nmessage Sample {}\n"},
		{path: "sample.tsx", data: "const value = <div>{/* Section ----- */}</div>;\n"},
		{path: "template.go", data: "const config = `\n# \u2500\u2500 Downloads \u2500\u2500\u2500\n`\n"},
	}
	for _, test := range tests {
		t.Run(test.path, func(t *testing.T) {
			if violations := Check(test.path, []byte(test.data), true); !hasRule(violations, RuleDecorativeComment) {
				t.Fatalf("expected labeled decorative comment violation, got %#v", violations)
			}
		})
	}
}

func TestCheckAllowsDocumentationParagraphBreak(t *testing.T) {
	data := []byte("// Package sample describes the API.\n//\n// It has two paragraphs.\npackage sample\n")
	violations := Check("sample.go", data, true)
	if hasRule(violations, RuleDecorativeComment) {
		t.Fatalf("documentation paragraph was treated as a banner: %#v", violations)
	}
}

func TestCheckSkipsMarkdownCommentRules(t *testing.T) {
	violations := Check("README.md", []byte("# ----------\n\ntext\n"), true)
	if hasRule(violations, RuleDecorativeComment) || hasRule(violations, RuleBlankAfterComment) {
		t.Fatalf("Markdown comment rules must be disabled: %#v", violations)
	}
}

func TestCheckSkipsGeneratedAndVendoredCommentRules(t *testing.T) {
	generated := []byte("// Code generated by tool. DO NOT EDIT.\n\npackage sample\n")
	if violations := Check("generated.go", generated, true); hasRule(violations, RuleBlankAfterComment) {
		t.Fatalf("generated comment layout must be preserved: %#v", violations)
	}
	vendored := []byte("// heading\n\npackage sample\n")
	if violations := Check("vendor/example/sample.go", vendored, true); hasRule(violations, RuleBlankAfterComment) {
		t.Fatalf("vendored comment layout must be preserved: %#v", violations)
	}
}

func TestCheckAllowsEmojiAndSkipsBinary(t *testing.T) {
	if violations := Check("README.md", []byte("allowed \U0001f600\n"), true); len(violations) != 0 {
		t.Fatalf("allowed emoji produced violations: %#v", violations)
	}
	if violations := Check("image.data", []byte{0xff, 0x00, 0xfe}, false); len(violations) != 0 {
		t.Fatalf("binary data produced violations: %#v", violations)
	}
}

func TestFixPreservesVendoredSource(t *testing.T) {
	input := []byte("// Section ----------\npackage sample\n")
	if got := Fix("vendor/example/sample.go", input); string(got) != string(input) {
		t.Fatalf("vendored source changed: %q", got)
	}
}

func TestCheckUTF8AndFinalNewline(t *testing.T) {
	if violations := Check("bad.txt", []byte{0xff, 0xfe}, false); !hasRule(violations, RuleUTF8) {
		t.Fatalf("expected UTF-8 violation, got %#v", violations)
	}
	if violations := Check("plain.txt", []byte("missing"), false); !hasRule(violations, RuleFinalNewline) {
		t.Fatalf("expected final newline violation, got %#v", violations)
	}
}

func TestFixSafeFormattingRules(t *testing.T) {
	input := []byte("// heading\n\n// ----------\nvalue := \"bad\u2014\u2192\" \t")
	want := "// heading\nvalue := \"bad-->\"\n"
	if got := string(Fix("sample.go", input)); got != want {
		t.Fatalf("Fix() = %q, want %q", got, want)
	}
}

func TestFixPreservesEmojiAndConflictMarkers(t *testing.T) {
	input := []byte("\U0001f600\n<<<<<<< HEAD\n")
	if got := Fix("sample.go", input); string(got) != string(input) {
		t.Fatalf("unsafe content changed: %q", got)
	}
}

func TestLoadEmojiAllowlist(t *testing.T) {
	root := t.TempDir()
	contents := "# paths\nREADME.md\ndocs/**\n"
	if err := os.WriteFile(filepath.Join(root, emojiAllowlistFile), []byte(contents), 0o600); err != nil {
		t.Fatal(err)
	}
	patterns, err := loadEmojiAllowlist(root)
	if err != nil {
		t.Fatal(err)
	}
	if !matchesAny("README.md", patterns) || !matchesAny("docs/guide.md", patterns) {
		t.Fatalf("expected allowlist matches, got %#v", patterns)
	}
	if matchesAny("frontend/app.ts", patterns) {
		t.Fatal("unexpected allowlist match")
	}
}

func TestCheckRepositorySkipsDeletedTrackedFile(t *testing.T) {
	root := t.TempDir()
	writeTestFile(t, filepath.Join(root, emojiAllowlistFile), "\n")
	runGit(t, root, "init")
	runGit(t, root, "config", "user.email", "test@example.com")
	runGit(t, root, "config", "user.name", "Text Policy Test")
	writeTestFile(t, filepath.Join(root, "deleted.txt"), "valid\n")
	runGit(t, root, "add", ".")
	runGit(t, root, "commit", "-m", "fixture")
	if err := os.Remove(filepath.Join(root, "deleted.txt")); err != nil {
		t.Fatal(err)
	}
	violations, err := CheckRepository(root)
	if err != nil {
		t.Fatal(err)
	}
	if len(violations) != 0 {
		t.Fatalf("deleted tracked file produced violations: %#v", violations)
	}
}

func writeTestFile(t *testing.T, filePath, contents string) {
	t.Helper()
	if err := os.WriteFile(filePath, []byte(contents), 0o600); err != nil {
		t.Fatal(err)
	}
}

func runGit(t *testing.T, root string, args ...string) {
	t.Helper()
	command := exec.Command("git", append([]string{"-C", root}, args...)...)
	if output, err := command.CombinedOutput(); err != nil {
		t.Fatalf("git %v: %v: %s", args, err, output)
	}
}

func hasRule(violations []Violation, rule Rule) bool {
	for _, violation := range violations {
		if violation.Rule == rule {
			return true
		}
	}
	return false
}
