package main

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"time"
)

func normalizeFeatures(input string, allowed []string) string {
	allowedSet := map[string]bool{}
	for _, f := range allowed {
		allowedSet[f] = true
	}
	parts := strings.Split(input, ",")
	seen := map[string]bool{}
	var output []string
	for _, p := range parts {
		v := strings.TrimSpace(strings.ToLower(p))
		if v == "" {
			continue
		}
		if !allowedSet[v] {
			warn("Ignoring unknown feature: %s", v)
			continue
		}
		if !seen[v] {
			seen[v] = true
			output = append(output, v)
		}
	}
	return strings.Join(output, ",")
}

func cmdNew(args []string) {
	var name, port string
	var domains []string

	// Parse CLI flags (all optional — missing values will be prompted).
	for i := 0; i < len(args); i++ {
		switch args[i] {
		case "--domain":
			i++
			if i >= len(args) {
				die("--domain requires a value")
			}
			domains = append(domains, args[i])
		case "--port":
			i++
			if i >= len(args) {
				die("--port requires a value")
			}
			port = args[i]
		default:
			if strings.HasPrefix(args[i], "-") {
				die("Unknown flag: %s", args[i])
			}
			if name == "" {
				name = args[i]
			} else {
				die("Unexpected argument: %s", args[i])
			}
		}
	}

	// Ensure root .env (interactive if missing).
	ensureRootEnv()

	fmt.Println()
	fmt.Printf("%sCreate a new client%s\n", colorBold, colorReset)
	fmt.Printf("%s─────────────────────────────────────%s\n", colorBlue, colorReset)
	fmt.Println()

	// Name
	if name == "" {
		for {
			name = prompt("Client name", "", false)
			if len(name) > 32 {
				warn("Must be ≤ 32 chars")
				name = ""
				continue
			}
			valid := true
			if name == "" || name[0] < 'a' || name[0] > 'z' {
				valid = false
			}
			for _, c := range name {
				if !((c >= 'a' && c <= 'z') || (c >= '0' && c <= '9') || c == '-') {
					valid = false
				}
			}
			if !valid {
				warn("Must start with a letter, lowercase alphanumeric + hyphens, ≤ 32 chars")
				name = ""
				continue
			}
			if clientExists(name) {
				warn("Client '%s' already exists", name)
				name = ""
				continue
			}
			break
		}
	} else {
		validateName(name)
		if clientExists(name) {
			die("Client '%s' already exists", name)
		}
		fmt.Printf("  Client name: %s%s%s\n", colorGreen, name, colorReset)
	}

	// Domains
	if len(domains) == 0 {
		domainInput := prompt("Domain(s), space-separated", "localhost", false)
		domains = strings.Fields(domainInput)
		if len(domains) == 0 {
			domains = []string{"localhost"}
		}
	}

	// Port
	if port == "" {
		defaultPort := strconv.Itoa(nextPort())
		port = prompt("Port", defaultPort, false)
	}
	portNum, err := strconv.Atoi(port)
	if err != nil {
		die("Port must be numeric: %s", port)
	}
	if portInUse(portNum) {
		die("Port %s is already assigned to another client", port)
	}

	// Database name
	dbName := prompt("Database name", name, false)

	// Admin password
	adminPassword := prompt("Admin password", "changeme", false)

	// Admin email
	adminEmail := prompt("Admin email", "admin@localhost", false)

	// Session timeout (minutes) — default 1 month = 30d × 24h × 60m = 43200
	sessionTimeout := prompt("Session timeout (minutes)", "43200", false)

	// Environment
	environment := promptChoice("Environment", "production", []string{"production", "development"})

	// Payment provider
	paymentProvider := promptChoice("Payment provider", "demo", []string{"demo", "stripe"})

	// Feature toggles
	allFeatures := []string{"landing", "store", "forum", "cart", "users", "inbox", "presence"}
	defaultFeatures := strings.Join(allFeatures, ",")
	featurePrompt := fmt.Sprintf("Enabled features (comma-separated) - available: %s", strings.Join(allFeatures, ","))
	features := prompt(featurePrompt, defaultFeatures, false)
	features = normalizeFeatures(features, allFeatures)

	var stripeKey, stripeWebhook string
	if paymentProvider == "stripe" {
		stripeKey = prompt("Stripe secret key", "", false)
		stripeWebhook = prompt("Stripe webhook secret", "", false)
	}

	fmt.Println()

	// Auto-generated values
	jwtSecret := generateSecret(32)

	domainList := strings.Join(domains, " ")
	var corsParts []string
	for _, d := range domains {
		corsParts = append(corsParts, "http://"+d)
	}
	corsOrigins := strings.Join(corsParts, ",")

	env := loadSharedEnv()

	// Ensure backends/ parent dir exists and is writable (Docker may have
	// created it as root via volume mounts).
	ensureWritableDir(backendsDir())

	cdir := clientDir(name)
	if err := os.MkdirAll(filepath.Join(cdir, "uploads"), 0755); err != nil {
		die("Cannot create client directory: %v", err)
	}

	// Write .env
	envLines := []string{
		fmt.Sprintf("# Auto-generated by grengo – %s", time.Now().Format(time.RFC3339)),
		fmt.Sprintf("CLIENT_NAME=%s", name),
		fmt.Sprintf("PORT=%s", port),
		"",
		"# Database",
		fmt.Sprintf("POSTGRES_DB=%s", dbName),
		fmt.Sprintf("DATABASE_URL=postgres://%s:%s@postgres:%s/%s?sslmode=disable", env.PostgresUser, env.PostgresPassword, env.PGPort, dbName),
		"",
		"# Redis",
		"REDIS_URL=redis://redis:6379",
		"",
		"# Auth",
		fmt.Sprintf("JWT_SECRET=%s", jwtSecret),
		fmt.Sprintf("ADMIN_PASSWORD=%s", adminPassword),
		fmt.Sprintf("ADMIN_EMAIL=%s", adminEmail),
		fmt.Sprintf("SESSION_TIMEOUT_MIN=%s", sessionTimeout),
		fmt.Sprintf("ENVIRONMENT=%s", environment),
		"",
		"# Domains & CORS",
		fmt.Sprintf("DOMAINS=%s", domainList),
		fmt.Sprintf("CORS_ORIGINS=%s", corsOrigins),
		"",
		"# Frontend SSR",
		"INDEX_FILE_PATH=/app/frontend/dist/index.html",
		"",
		"# Features",
		fmt.Sprintf("FEATURES_ENABLED=%s", features),
		"",
		"# Payments",
		fmt.Sprintf("PAYMENT_PROVIDER=%s", paymentProvider),
		fmt.Sprintf("STRIPE_SECRET_KEY=%s", stripeKey),
		fmt.Sprintf("STRIPE_WEBHOOK_SECRET=%s", stripeWebhook),
		"",
		"# Tuning (sensible defaults)",
		"DB_MAX_OPEN_CONNS=100",
		"DB_MAX_IDLE_CONNS=50",
		"DB_CONN_MAX_LIFETIME_MIN=30",
		"DB_CONN_MAX_IDLE_TIME_MIN=5",
		"WS_MAX_CONNECTIONS=100000",
		"WS_MAX_WORKERS=256",
		"WS_SESSION_SIZE=100",
		"WS_CHAT_RING_SIZE=80",
		"WS_PRESENCE_INTERVAL_MS=1000",
		"HTTP_READ_TIMEOUT_SEC=15",
		"HTTP_WRITE_TIMEOUT_SEC=15",
		"HTTP_IDLE_TIMEOUT_SEC=60",
		"HTTP_SHUTDOWN_TIMEOUT_SEC=30",
		"",
		"# Upload Limits",
		"MAX_UPLOAD_PER_USER_MB=500",
		"MAX_UPLOAD_TOTAL_MB=5000",
		"",
		"# Email / SMTP (uncomment and configure to enable)",
		"# SMTP_HOST=",
		"# SMTP_PORT=587",
		"# SMTP_USER=",
		"# SMTP_PASSWORD=",
		"# SMTP_FROM=",
		"# SMTP_FROM_NAME=",
		"# BASE_URL=",
		"# SITE_NAME=",
		"",
		"# Grengo internal API",
		"GRENGO_API_URL=http://host.docker.internal:9100",
	}
	if err := writeEnvFile(clientEnvFile(name), envLines); err != nil {
		die("Cannot write .env: %v", err)
	}

	// Write compose.yml
	composeContent := `# Auto-generated by grengo
services:
  backend:
    image: skaia-backend:latest
    container_name: ${CLIENT_NAME}-backend
    restart: unless-stopped
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
      - ./armed:/app/armed
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - skaia-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:${PORT}/health"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  skaia-network:
    external: true
`
	if err := os.WriteFile(clientComposeFile(name), []byte(composeContent), 0644); err != nil {
		die("Cannot write compose.yml: %v", err)
	}

	log("Client %s created", bold(name))
	info("  Directory : backends/%s/", name)
	info("  Port      : %s", port)
	info("  Domains   : %s", domainList)
	info("  DB        : %s", dbName)
	fmt.Println()
	info("Next steps:")
	info("  1. grengo build          # first time only")
	info("  2. grengo compose up     # starts everything")
}

// cmdList prints a table of all clients and their status.
func cmdList() {
	fmt.Printf("%s%-20s %-8s %-10s %-10s %s%s\n", colorBold, "CLIENT", "PORT", "STATUS", "RUNNING", "DOMAINS", colorReset)
	fmt.Printf("%-20s %-8s %-10s %-10s %s\n", "────────────────────", "────────", "──────────", "──────────", "───────────────────────")

	entries, err := os.ReadDir(backendsDir())
	if err != nil || len(entries) == 0 {
		info("No clients yet. Create one with: grengo new <name>")
		return
	}

	found := false
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		envFile := filepath.Join(backendsDir(), e.Name(), ".env")
		if _, err := os.Stat(envFile); err != nil {
			continue
		}
		found = true

		name := envVal(envFile, "CLIENT_NAME")
		port := envVal(envFile, "PORT")
		domainsStr := envVal(envFile, "DOMAINS")

		var status, running string
		disabledFile := filepath.Join(backendsDir(), e.Name(), ".disabled")
		if _, err := os.Stat(disabledFile); err == nil {
			status = fmt.Sprintf("%sdisabled%s", colorYellow, colorReset)
		} else {
			status = fmt.Sprintf("%senabled%s", colorGreen, colorReset)
		}

		if clientRunning(name) {
			running = fmt.Sprintf("%syes%s", colorGreen, colorReset)
		} else {
			running = fmt.Sprintf("%sno%s", colorRed, colorReset)
		}

		fmt.Printf("%-20s %-8s %-22s %-22s %s\n", name, port, status, running, domainsStr)
	}

	if !found {
		info("No clients yet. Create one with: grengo new <name>")
	}
}

// cmdEnable re-enables a disabled client.
func cmdEnable(name string) {
	if !clientExists(name) {
		die("Client '%s' not found", name)
	}
	os.Remove(filepath.Join(backendsDir(), name, ".disabled"))
	log("Client '%s' enabled", name)
	generateNginxConfig()
	reloadNginxIfRunning()
}

// cmdDisable disables a client and stops its backend if running.
func cmdDisable(name string) {
	if !clientExists(name) {
		die("Client '%s' not found", name)
	}
	disabledFile := filepath.Join(backendsDir(), name, ".disabled")
	if err := os.WriteFile(disabledFile, []byte{}, 0644); err != nil {
		die("Cannot create .disabled file: %v", err)
	}
	log("Client '%s' disabled", name)

	if clientRunning(name) {
		info("Stopping backend…")
		dockerComposeSilent(clientComposeFile(name), "down")
	}

	generateNginxConfig()
	reloadNginxIfRunning()
}

// cmdStart starts a client's backend container.
func cmdStart(name string) {
	if !clientExists(name) {
		die("Client '%s' not found", name)
	}
	if !clientEnabled(name) {
		die("Client '%s' is disabled – enable it first", name)
	}

	ensureNetwork()
	ensureImage()

	log("Starting %s…", name)
	if err := dockerCompose(clientComposeFile(name), "up", "-d"); err != nil {
		die("Failed to start %s: %v", name, err)
	}
	log("%s started", name)
}

func cmdUpdateClient(name string) {
	if !clientExists(name) {
		die("Client '%s' not found", name)
	}
	const oneHint = "Comma-separated list: landing, store, forum, cart, users, inbox, presence"
	current := envVal(clientEnvFile(name), "FEATURES_ENABLED")
	if current == "" {
		current = "landing,store,forum,cart,users,inbox,presence"
	}
	fmt.Println()
	fmt.Printf("Updating features for client %s\n", name)
	fmt.Printf("%s\n", oneHint)
	values := prompt("Enabled features", current, false)
	values = normalizeFeatures(values, []string{"landing", "store", "forum", "cart", "users", "inbox", "presence"})
	if values == "" {
		values = "landing,store,forum,cart,users,inbox,presence"
	}
	if err := setEnvVal(clientEnvFile(name), "FEATURES_ENABLED", values); err != nil {
		die("Failed to update .env for %s: %v", name, err)
	}
	log("Updated %s: FEATURES_ENABLED=%s", name, values)
}

func cmdUpdateAll() {
	entries, err := os.ReadDir(backendsDir())
	if err != nil {
		die("Unable to read backends dir: %v", err)
	}
	const oneHint = "Comma-separated list: landing, store, forum, cart, users, inbox, presence"
	fmt.Println()
	fmt.Printf("Updating features for all clients\n")
	fmt.Printf("%s\n", oneHint)
	values := prompt("Enabled features", "landing,store,forum,cart,users,inbox,presence", false)
	values = normalizeFeatures(values, []string{"landing", "store", "forum", "cart", "users", "inbox", "presence"})
	if values == "" {
		values = "landing,store,forum,cart,users,inbox,presence"
	}

	updated := 0
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		path := filepath.Join(backendsDir(), e.Name(), ".env")
		if _, err := os.Stat(path); err != nil {
			continue
		}
		if err := setEnvVal(path, "FEATURES_ENABLED", values); err != nil {
			warn("Failed to update %s: %v", e.Name(), err)
			continue
		}
		updated++
	}
	log("Updated %d clients with FEATURES_ENABLED=%s", updated, values)
}

// cmdStop stops a client's backend container.
func cmdStop(name string) {
	if !clientExists(name) {
		die("Client '%s' not found", name)
	}
	log("Stopping %s…", name)
	dockerComposeSilent(clientComposeFile(name), "down")
	log("%s stopped", name)
}

// cmdRemove permanently deletes a client after confirmation.
func cmdRemove(name string) {
	if !clientExists(name) {
		die("Client '%s' not found", name)
	}

	fmt.Printf("%sThis will permanently delete backends/%s/ and its uploads.%s\n", colorRed, name, colorReset)
	if !confirmPrompt(name) {
		die("Aborted")
	}

	if clientRunning(name) {
		dockerComposeSilent(clientComposeFile(name), "down")
	}

	dir := clientDir(name)
	if dir == "" || dir == "/" {
		die("Refusing to remove dangerous path")
	}
	if err := os.RemoveAll(dir); err != nil {
		// Likely root-owned files from Docker volume mounts.
		warn("Cannot remove as current user — retrying with sudo…")
		cmd := exec.Command("sudo", "rm", "-rf", dir)
		cmd.Stdin = os.Stdin
		cmd.Stdout = os.Stdout
		cmd.Stderr = os.Stderr
		if err := cmd.Run(); err != nil {
			die("Cannot remove client directory: %v\n  Try: sudo rm -rf %s", err, dir)
		}
	}
	log("Client '%s' removed", name)

	generateNginxConfig()
	reloadNginxIfRunning()
}

// cmdBuild builds the backend Docker image.
func cmdBuild() {
	log("Building %s from %s …", Image(), backendSrc())
	if err := dockerRun("build", "-t", Image(), backendSrc()); err != nil {
		die("Build failed: %v", err)
	}
	log("Image %s built", Image())
}

// cmdComposeUp starts all infrastructure and enabled client backends.
func cmdComposeUp(follow bool, build bool) {
	loadSharedEnv()

	// 1) Optionally build backend image
	if build {
		cmdBuild()
	} else {
		ensureImage()
	}

	// 2) Start shared infrastructure (postgres + redis)
	log("Starting shared infrastructure…")
	if err := dockerCompose(composeFile(), "up", "-d", "postgres", "redis"); err != nil {
		die("Failed to start shared infrastructure: %v", err)
	}

	waitForHealthy("skaia-postgres", 60)
	waitForHealthy("skaia-redis", 60)

	// 3) Ensure network exists for client composes
	ensureNetwork()

	// 4) Init DBs + start enabled backends
	started := 0
	entries, _ := os.ReadDir(backendsDir())
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		dir := filepath.Join(backendsDir(), e.Name())
		if _, err := os.Stat(filepath.Join(dir, ".disabled")); err == nil {
			continue
		}
		envFile := filepath.Join(dir, ".env")
		if _, err := os.Stat(envFile); err != nil {
			continue
		}

		cname := envVal(envFile, "CLIENT_NAME")
		if cname == "" {
			continue
		}

		// Init DB if needed (ignore errors — DB may already exist)
		cmdDBInit(cname)

		log("Starting %s…", cname)
		if err := dockerCompose(filepath.Join(dir, "compose.yml"), "up", "-d"); err != nil {
			warn("Failed to start %s: %v", cname, err)
			continue
		}
		started++
	}

	if started == 0 {
		warn("No enabled clients found. Create one with: grengo new <name>")
	}

	// 5) Generate nginx config + start nginx
	generateNginxConfig()
	if err := dockerCompose(composeFile(), "up", "-d", "nginx"); err != nil {
		die("Failed to start nginx: %v", err)
	}
	log("All services started (%d client(s))", started)

	if follow {
		log("Following logs (ctrl-c to stop)…")
		if err := dockerComposeLogs(composeFile(), "--follow", "--tail", "100"); err != nil {
			warn("Log follow ended with error: %v", err)
		}
	}
}

// cmdComposeDown stops all client backends and shared infrastructure.
func cmdComposeDown() {
	// Stop all client backends
	entries, _ := os.ReadDir(backendsDir())
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		cf := filepath.Join(backendsDir(), e.Name(), "compose.yml")
		if _, err := os.Stat(cf); err == nil {
			dockerComposeSilent(cf, "down")
		}
	}

	// Stop shared infra
	if err := dockerCompose(composeFile(), "down"); err != nil {
		die("Failed to stop shared infrastructure: %v", err)
	}
	log("All services stopped")
}

// cmdWipeAll stops everything and removes all clients, volumes and data.
func cmdWipeAll() {
	fmt.Printf("%sThis will irreversibly delete all clients, uploads, and shared service data (postgres/redis).%s\n", colorRed, colorReset)
	fmt.Printf("%sType 'wipe all' to confirm: %s", colorYellow, colorReset)
	if !confirmPrompt("wipe all") {
		die("Aborted")
	}

	// Stop all containers and infrastructure.
	cmdComposeDown()

	// Remove all client directories under backends.
	entries, err := os.ReadDir(backendsDir())
	if err == nil {
		for _, e := range entries {
			if e.IsDir() {
				path := filepath.Join(backendsDir(), e.Name())
				if err := os.RemoveAll(path); err != nil {
					warn("Failed to remove %s: %v", path, err)
				}
			}
		}
	}

	// Remove shared data directories.
	for _, d := range []string{"postgres_data", "redis_data"} {
		path := filepath.Join(ProjectRoot(), d)
		if err := os.RemoveAll(path); err != nil {
			warn("Cannot remove %s as current user — retrying with sudo…", path)
			cmd := exec.Command("sudo", "rm", "-rf", path)
			cmd.Stdin = os.Stdin
			cmd.Stdout = os.Stdout
			cmd.Stderr = os.Stderr
			if err2 := cmd.Run(); err2 != nil {
				warn("Failed to remove %s: %v", path, err2)
			}
		}
	}

	log("Wipe complete. You can now run 'grengo new <name>' to create fresh clients.")
}

// cmdNginxReload regenerates the nginx config and hot-reloads it.
func cmdNginxReload() {
	generateNginxConfig()
	reloadNginxIfRunning()
}

// cmdLogs tails a client's container logs.
func cmdLogs(name string, extra []string) {
	if !clientExists(name) {
		die("Client '%s' not found", name)
	}
	if err := dockerComposeLogs(clientComposeFile(name), extra...); err != nil {
		die("Failed to get logs: %v", err)
	}
}

// ensureRootEnv creates the root .env interactively if it doesn't exist.
func ensureRootEnv() {
	if _, err := os.Stat(rootEnvFile()); err == nil {
		// Already exists
		return
	}

	fmt.Println()
	info("No root %s.env%s found — let's set up shared database credentials.", colorBold, colorReset)
	fmt.Println()

	pgUser := prompt("PostgreSQL user", "skaia", false)
	pgPass := prompt("PostgreSQL password", "", true)
	pgPort := prompt("PostgreSQL port", "5432", false)

	lines := []string{
		fmt.Sprintf("POSTGRES_USER=%s", pgUser),
		fmt.Sprintf("POSTGRES_PASSWORD=%s", pgPass),
		fmt.Sprintf("PGPORT=%s", pgPort),
	}
	if err := writeEnvFile(rootEnvFile(), lines); err != nil {
		die("Cannot write root .env: %v", err)
	}
	log("Root .env created")
	fmt.Println()
}

// generateSecret returns a hex-encoded random string of the given byte length.
func generateSecret(nBytes int) string {
	b := make([]byte, nBytes)
	if _, err := rand.Read(b); err != nil {
		die("Cannot generate random secret: %v", err)
	}
	return hex.EncodeToString(b)
}
