package app

import (
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"
)

func cmdNew(args []string) {
	var name, port string
	var domains []string

	// Parse CLI flags (all optional - missing values will be prompted).
	for i := 0; i < len(args); i++ {
		switch args[i] {
		case "--domain":
			i++
			if i >= len(args) {
				die("--domain requires a value")
			}
			domains = append(domains, args[i])
		case "--port":
			i++
			if i >= len(args) {
				die("--port requires a value")
			}
			port = args[i]
		default:
			if strings.HasPrefix(args[i], "-") {
				die("Unknown flag: %s", args[i])
			}
			if name == "" {
				name = args[i]
			} else {
				die("Unexpected argument: %s", args[i])
			}
		}
	}

	// Ensure root .env (interactive if missing).
	ensureRootEnv()

	fmt.Println()
	fmt.Printf("%sCreate a new client%s\n", colorBold, colorReset)
	fmt.Printf("%s─────────────────────────────────────%s\n", colorBlue, colorReset)
	fmt.Println()

	// Name
	if name == "" {
		for {
			name = prompt("Client name", "", false)
			if len(name) > 32 {
				warn("Must be ≤ 32 chars")
				name = ""
				continue
			}
			valid := true
			if name == "" || name[0] < 'a' || name[0] > 'z' {
				valid = false
			}
			for _, c := range name {
				if !((c >= 'a' && c <= 'z') || (c >= '0' && c <= '9') || c == '-') {
					valid = false
				}
			}
			if !valid {
				warn("Must start with a letter, lowercase alphanumeric + hyphens, ≤ 32 chars")
				name = ""
				continue
			}
			if clientExists(name) {
				warn("Client '%s' already exists", name)
				name = ""
				continue
			}
			break
		}
	} else {
		validateName(name)
		if clientExists(name) {
			die("Client '%s' already exists", name)
		}
		fmt.Printf("  Client name: %s%s%s\n", colorGreen, name, colorReset)
	}

	// Domains
	if len(domains) == 0 {
		domainInput := prompt("Domain(s), space-separated", "localhost", false)
		domains = strings.Fields(domainInput)
		if len(domains) == 0 {
			domains = []string{"localhost"}
		}
	}

	// Port
	if port == "" {
		defaultPort := strconv.Itoa(nextPort())
		port = prompt("Port", defaultPort, false)
	}
	portNum, err := strconv.Atoi(port)
	if err != nil {
		die("Port must be numeric: %s", port)
	}
	if portInUse(portNum) {
		die("Port %s is already assigned to another client", port)
	}

	// Database name
	dbName := prompt("Database name", name, false)

	// Admin password
	adminPassword := prompt("Admin password", "changeme", false)

	// Admin email
	adminEmail := prompt("Admin email", "admin@localhost", false)

	// Session timeout (minutes) - default 1 month = 30d × 24h × 60m = 43200
	sessionTimeout := prompt("Session timeout (minutes)", "43200", false)

	// Environment
	environment := promptChoice("Environment", "production", []string{"production", "development"})

	// Payment provider
	paymentProvider := promptChoice("Payment provider", "demo", []string{"demo", "stripe"})

	// Feature toggles
	allFeatures := []string{"landing", "store", "forum", "cart", "users", "inbox", "presence"}
	defaultFeatures := strings.Join(allFeatures, ",")
	featurePrompt := fmt.Sprintf("Enabled features (comma-separated) - available: %s", strings.Join(allFeatures, ","))
	features := prompt(featurePrompt, defaultFeatures, false)
	features = normalizeFeatures(features, allFeatures)

	var stripeKey, stripeWebhook string
	if paymentProvider == "stripe" {
		stripeKey = prompt("Stripe secret key", "", false)
		stripeWebhook = prompt("Stripe webhook secret", "", false)
	}

	fmt.Println()

	// Auto-generated values
	jwtSecret := generateSecret(32)

	domainList := strings.Join(domains, " ")
	var corsParts []string
	for _, d := range domains {
		corsParts = append(corsParts, "http://"+d)
	}
	corsOrigins := strings.Join(corsParts, ",")

	env := loadSharedEnv()

	// Ensure backends/ parent dir exists and is writable (Docker may have
	// created it as root via volume mounts).
	ensureWritableDir(backendsDir())

	cdir := clientDir(name)
	if err := os.MkdirAll(filepath.Join(cdir, "uploads"), 0755); err != nil {
		die("Cannot create client directory: %v", err)
	}

	// Write .env
	envLines := []string{
		fmt.Sprintf("# Auto-generated by grengo – %s", time.Now().Format(time.RFC3339)),
		fmt.Sprintf("CLIENT_NAME=%s", name),
		fmt.Sprintf("PORT=%s", port),
		"",
		"# Database",
		fmt.Sprintf("POSTGRES_DB=%s", dbName),
		fmt.Sprintf("DATABASE_URL=postgres://%s:%s@postgres:%s/%s?sslmode=disable", env.PostgresUser, env.PostgresPassword, env.PGPort, dbName),
		"",
		"# Redis",
		"REDIS_URL=redis://redis:6379",
		"",
		"# Auth",
		fmt.Sprintf("JWT_SECRET=%s", jwtSecret),
		fmt.Sprintf("ADMIN_PASSWORD=%s", adminPassword),
		fmt.Sprintf("ADMIN_EMAIL=%s", adminEmail),
		fmt.Sprintf("SESSION_TIMEOUT_MIN=%s", sessionTimeout),
		fmt.Sprintf("ENVIRONMENT=%s", environment),
		"",
		"# Domains & CORS",
		fmt.Sprintf("DOMAINS=%s", domainList),
		fmt.Sprintf("CORS_ORIGINS=%s", corsOrigins),
		"",
		"# Frontend SSR",
		"INDEX_FILE_PATH=/app/frontend/dist/index.html",
		"",
		"# Features",
		fmt.Sprintf("FEATURES_ENABLED=%s", features),
		"",
		"# Payments",
		fmt.Sprintf("PAYMENT_PROVIDER=%s", paymentProvider),
		fmt.Sprintf("STRIPE_SECRET_KEY=%s", stripeKey),
		fmt.Sprintf("STRIPE_WEBHOOK_SECRET=%s", stripeWebhook),
		"",
		"# Tuning (sensible defaults)",
		"DB_MAX_OPEN_CONNS=100",
		"DB_MAX_IDLE_CONNS=50",
		"DB_CONN_MAX_LIFETIME_MIN=30",
		"DB_CONN_MAX_IDLE_TIME_MIN=5",
		"WS_MAX_CONNECTIONS=100000",
		"WS_MAX_WORKERS=256",
		"WS_SESSION_SIZE=100",
		"WS_CHAT_RING_SIZE=80",
		"WS_PRESENCE_INTERVAL_MS=1000",
		"HTTP_READ_TIMEOUT_SEC=15",
		"HTTP_WRITE_TIMEOUT_SEC=15",
		"HTTP_IDLE_TIMEOUT_SEC=60",
		"HTTP_SHUTDOWN_TIMEOUT_SEC=30",
		"",
		"# Upload Limits",
		"MAX_UPLOAD_PER_USER_MB=500",
		"MAX_UPLOAD_TOTAL_MB=5000",
		"",
		"# Email / SMTP (uncomment and configure to enable)",
		"# SMTP_HOST=",
		"# SMTP_PORT=587",
		"# SMTP_USER=",
		"# SMTP_PASSWORD=",
		"# SMTP_FROM=",
		"# SMTP_FROM_NAME=",
		"# BASE_URL=",
		"# SITE_NAME=",
		"",
		"# Grengo internal API",
		"GRENGO_API_URL=http://host.docker.internal:9100",
	}
	if err := writeEnvFile(clientEnvFile(name), envLines); err != nil {
		die("Cannot write .env: %v", err)
	}

	// Write compose.yml
	composeContent := `# Auto-generated by grengo
services:
  backend:
    image: skaia-backend:latest
    container_name: ${CLIENT_NAME}-backend
    restart: unless-stopped
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
      - ./armed:/app/armed
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - skaia-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:${PORT}/health"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  skaia-network:
    external: true
`
	if err := os.WriteFile(clientComposeFile(name), []byte(composeContent), 0644); err != nil {
		die("Cannot write compose.yml: %v", err)
	}

	log("Client %s created", bold(name))
	info("  Directory : backends/%s/", name)
	info("  Port      : %s", port)
	info("  Domains   : %s", domainList)
	info("  DB        : %s", dbName)
	fmt.Println()
	info("Next steps:")
	info("  1. grengo build          # first time only")
	info("  2. grengo compose up     # starts everything")
}
