package app

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"
)

// clientInfo holds parsed data from a client's .env for nginx config generation.
type clientInfo struct {
	Name    string
	Port    string
	Domains []string
}

// cmdNginxReload regenerates the nginx config and hot-reloads it.
func cmdNginxReload() {
	generateNginxConfig()
	reloadNginxIfRunning()
}

// expandDomains adds www. variants for production domains (not localhost or IPs).
func expandDomains(domains []string) []string {
	seen := map[string]bool{}
	var out []string
	for _, d := range domains {
		if seen[d] {
			continue
		}
		seen[d] = true
		out = append(out, d)
		// Add www. variant for real domains (skip localhost, IPs, already-www)
		if d != "localhost" && !strings.HasPrefix(d, "www.") && strings.Contains(d, ".") && !isIPAddress(d) {
			www := "www." + d
			if !seen[www] {
				seen[www] = true
				out = append(out, www)
			}
		}
	}
	return out
}

// isIPAddress returns true if the string looks like an IPv4 address.
func isIPAddress(s string) bool {
	for _, c := range s {
		if c != '.' && (c < '0' || c > '9') {
			return false
		}
	}
	return true
}

// enabledClients scans the backends directory and returns info for all enabled clients.
func enabledClients() []clientInfo {
	var clients []clientInfo
	entries, err := os.ReadDir(backendsDir())
	if err != nil {
		return clients
	}
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		dir := filepath.Join(backendsDir(), e.Name())
		// Skip disabled
		if _, err := os.Stat(filepath.Join(dir, ".disabled")); err == nil {
			continue
		}
		envFile := filepath.Join(dir, ".env")
		if _, err := os.Stat(envFile); err != nil {
			continue
		}
		name := envVal(envFile, "CLIENT_NAME")
		port := envVal(envFile, "PORT")
		domainsStr := envVal(envFile, "DOMAINS")
		if name == "" || port == "" {
			continue
		}
		var domains []string
		if domainsStr != "" {
			domains = expandDomains(strings.Fields(domainsStr))
		}
		clients = append(clients, clientInfo{Name: name, Port: port, Domains: domains})
	}
	return clients
}

// generateNginxConfig writes the nginx default.conf based on enabled clients.
func generateNginxConfig() {
	dir := nginxDir()
	if err := os.MkdirAll(dir, 0755); err != nil {
		die("Cannot create nginx directory: %v", err)
	}
	confPath := filepath.Join(dir, "default.conf")

	clients := enabledClients()

	// No enabled clients => 503 fallback
	if len(clients) == 0 {
		fallback := `server { listen 80 default_server; return 503 "No backends configured – run: grengo new <name>\n"; }` + "\n"
		if err := os.WriteFile(confPath, []byte(fallback), 0644); err != nil {
			die("Cannot write nginx config: %v", err)
		}
		warn("No enabled clients – nginx will return 503")
		return
	}

	var b strings.Builder

	// Header
	fmt.Fprintf(&b, "# Auto-generated by grengo – %s\n", time.Now().Format(time.RFC3339))
	b.WriteString("# Do not edit manually; run 'grengo nginx reload' to regenerate.\n\n")

	// gzip
	b.WriteString(`# ── gzip ───────────────────────────────────────────────────────────────────
gzip              on;
gzip_comp_level   5;
gzip_min_length   256;
gzip_vary         on;
gzip_proxied      any;
gzip_types
    text/plain text/css text/javascript text/xml
    application/javascript application/json
    application/xml application/xml+rss application/wasm
    image/svg+xml font/woff2;

`)

	// Upstreams
	b.WriteString("# ── Upstreams ──────────────────────────────────────────────────────────────\n")
	for _, c := range clients {
		fmt.Fprintf(&b, "upstream %s-backend {\n    server 127.0.0.1:%s;\n    keepalive 32;\n}\n\n", c.Name, c.Port)
	}

	// Host => backend mapping
	b.WriteString("# ── Host => backend mapping ────────────────────────────────────────────────\n")
	b.WriteString("map $host $backend_upstream {\n")
	for _, c := range clients {
		for _, domain := range c.Domains {
			fmt.Fprintf(&b, "    %-24s%s-backend;\n", domain, c.Name)
		}
	}
	// Default to first client
	fmt.Fprintf(&b, "    %-24s%s-backend;\n", "default", clients[0].Name)
	b.WriteString("}\n\n")

	// WebSocket upgrade map
	b.WriteString(`# ── WebSocket upgrade ─────────────────────────────────────────────────────
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

`)

	// Upload cache
	b.WriteString(`# ── Upload cache ──────────────────────────────────────────────────────────
proxy_cache_path /var/cache/nginx/uploads
                 levels=1:2 keys_zone=uploads_cache:10m
                 max_size=1g inactive=30d use_temp_path=off;

`)

	// Collect all server names
	var serverNames []string
	for _, c := range clients {
		serverNames = append(serverNames, c.Domains...)
	}

	// Server block
	fmt.Fprintf(&b, "server {\n    listen 80;\n    server_name %s;\n    client_max_body_size 0;\n    proxy_intercept_errors on;\n\n", strings.Join(serverNames, " "))

	// Load frontend shell index.html for fallback
	indexPath := filepath.Join(ProjectRoot(), "backend", "frontend", "dist", "index.html")
	indexBytes, err := os.ReadFile(indexPath)
	if err != nil {
		// If running in production where source isn't checked out, extract it from the docker image
		cmd := exec.Command("docker", "run", "--rm", "--entrypoint", "cat", Image(), "/app/frontend/dist/index.html")
		indexBytes, err = cmd.Output()
	}

	var fallbackHTML string
	if err == nil {
		fallbackHTML = string(indexBytes)
		fallbackHTML = strings.ReplaceAll(fallbackHTML, "%TITLE_PLACEHOLDER%", "<title>Starting...</title>")
		fallbackHTML = strings.ReplaceAll(fallbackHTML, "%META_DESCRIPTION_PLACEHOLDER%", "<meta name=\"description\" content=\"Service is currently restarting. Please wait a moment.\">")
		fallbackHTML = strings.ReplaceAll(fallbackHTML, "%OG_IMAGE_PLACEHOLDER%", "")
		fallbackHTML = strings.ReplaceAll(fallbackHTML, "%FAVICON_PLACEHOLDER%", "<link rel=\"icon\" href=\"/logo.png\">")
		fallbackHTML = strings.ReplaceAll(fallbackHTML, "</head>", "  <meta http-equiv=\"refresh\" content=\"2\">\n</head>")
		
		// Escape for nginx double-quoted string
		fallbackHTML = strings.ReplaceAll(fallbackHTML, "\\", "\\\\")
		fallbackHTML = strings.ReplaceAll(fallbackHTML, "\"", "\\\"")
		fallbackHTML = strings.ReplaceAll(fallbackHTML, "$", "\\$")
		fallbackHTML = strings.ReplaceAll(fallbackHTML, "\r", "")
		fallbackHTML = strings.ReplaceAll(fallbackHTML, "\n", "\\n")
	} else {
		fallbackHTML = "<!DOCTYPE html><html><head><title>Starting...</title><meta http-equiv=\\\"refresh\\\" content=\\\"2\\\"></head><body><h2>System is starting...</h2><p>Please wait a moment while the system boots.</p><!-- padding to bypass cloudflare limit padding to bypass cloudflare limit padding to bypass cloudflare limit padding to bypass cloudflare limit padding to bypass cloudflare limit padding to bypass cloudflare limit padding to bypass cloudflare limit padding to bypass cloudflare limit padding to bypass cloudflare limit padding to bypass cloudflare limit padding to bypass cloudflare limit padding to bypass cloudflare limit padding to bypass cloudflare limit padding to bypass cloudflare limit padding to bypass cloudflare limit padding to bypass cloudflare limit padding to bypass cloudflare limit padding to bypass cloudflare limit padding to bypass cloudflare limit padding to bypass cloudflare limit padding to bypass cloudflare limit padding to bypass cloudflare limit padding to bypass cloudflare limit padding to bypass cloudflare limit padding to bypass cloudflare limit padding to bypass cloudflare limit --></body></html>"
	}

	// Fallback replacement to prevent 502 from Cloudflare
	b.WriteString("    error_page 502 503 504 =503 @fallback;\n")
	b.WriteString("    location @fallback {\n")
	b.WriteString("        default_type text/html;\n")
	b.WriteString("        return 503 \"" + fallbackHTML + "\";\n")
	b.WriteString("    }\n\n")

	// Security headers
	b.WriteString(`    # Security headers
    add_header X-Frame-Options        "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy        "strict-origin-when-cross-origin" always;
    add_header Permissions-Policy     "camera=(), microphone=(self), geolocation=()" always;

`)

	// Uploads location
	b.WriteString(`    # ── Uploads (cached) ──────────────────────────────────────────────────
    location ^~ /uploads/ {
        proxy_pass         http://$backend_upstream;
        proxy_http_version 1.1;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_set_header   Connection        "";

        proxy_cache           uploads_cache;
        proxy_cache_valid     200 30d;
        proxy_cache_valid     404 1m;
        proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;
        proxy_cache_lock      on;
        add_header X-Cache-Status $upstream_cache_status;
        expires 30d;
        add_header Cache-Control "public";
        add_header X-Content-Type-Options "nosniff" always;
        access_log off;
    }

`)

	// API location
	b.WriteString(`    # ── API ───────────────────────────────────────────────────────────────
    location /api/ {
        proxy_pass         http://$backend_upstream;
        proxy_http_version 1.1;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_set_header   Connection        "";
        proxy_buffering    on;
        proxy_buffer_size  16k;
        proxy_buffers      8 16k;

        # Chunked upload completion can take minutes for large files
        proxy_read_timeout 3600;
        proxy_send_timeout 3600;

        # Prevent CDN / browser caching of API responses
        add_header Cache-Control "no-store, no-cache, must-revalidate" always;
        add_header Pragma        "no-cache" always;
    }

    # ── Downloads (No Buffering) ──────────────────────────────────────────
    location ~ ^/api/s/.*/(?:exports|jobs)/.*/download$ {
        proxy_pass         http://$backend_upstream;
        proxy_http_version 1.1;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_set_header   Connection        "";
        proxy_buffering    off;
        
        # Prevent timeouts during long downloads
        proxy_read_timeout 3600;
        proxy_send_timeout 3600;
    }

    # ── Config / page endpoints ───────────────────────────────────────────
    location /config/ {
        proxy_pass         http://$backend_upstream;
        proxy_http_version 1.1;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_set_header   Connection        "";

        # Prevent CDN / browser caching of config responses
        add_header Cache-Control "no-store, no-cache, must-revalidate" always;
        add_header Pragma        "no-cache" always;
    }

`)

	// WebSocket locations
	b.WriteString(`    # ── WebSocket ─────────────────────────────────────────────────────────
    location = /ws {
        proxy_pass         http://$backend_upstream;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade           $http_upgrade;
        proxy_set_header   Connection        $connection_upgrade;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_read_timeout 86400s;
        proxy_send_timeout 86400s;
    }

    location = /api/ws {
        proxy_pass         http://$backend_upstream;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade           $http_upgrade;
        proxy_set_header   Connection        $connection_upgrade;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_read_timeout 86400s;
        proxy_send_timeout 86400s;
    }

`)

	// Webhook location
	fmt.Fprintf(&b, `    # ── Webhook ───────────────────────────────────────────────────────────
    location = /webhook/github {
        proxy_pass         http://127.0.0.1:%d;
        proxy_http_version 1.1;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
    }

`, DefaultAPIPort)

	// Health location
	b.WriteString(`    # ── Health ────────────────────────────────────────────────────────────
    location = /health {
        proxy_pass         http://$backend_upstream;
        proxy_http_version 1.1;
        proxy_set_header   Host        $host;
        proxy_set_header   Connection  "";
    }

`)

	// Catch-all
	b.WriteString(`    # ── Catch-all => SSR / SPA ────────────────────────────────────────────
    location / {
        proxy_pass         http://$backend_upstream;
        proxy_http_version 1.1;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_set_header   Connection        "";
        proxy_buffering    off;
        proxy_buffer_size  16k;
        proxy_buffers      8 16k;
    }
}
`)

	if err := os.WriteFile(confPath, []byte(b.String()), 0644); err != nil {
		die("Cannot write nginx config: %v", err)
	}
	log("nginx config written => %s", confPath)
}
