// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: proto/skaia.proto

package skaia

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GrengoService_ReportStatus_FullMethodName = "/skaia.grpc.GrengoService/ReportStatus"
)

// GrengoServiceClient is the client API for GrengoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GrengoService handles incoming communication from backend nodes to the central orchestrator
type GrengoServiceClient interface {
	ReportStatus(ctx context.Context, in *ReportStatusRequest, opts ...grpc.CallOption) (*ReportStatusResponse, error)
}

type grengoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGrengoServiceClient(cc grpc.ClientConnInterface) GrengoServiceClient {
	return &grengoServiceClient{cc}
}

func (c *grengoServiceClient) ReportStatus(ctx context.Context, in *ReportStatusRequest, opts ...grpc.CallOption) (*ReportStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportStatusResponse)
	err := c.cc.Invoke(ctx, GrengoService_ReportStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GrengoServiceServer is the server API for GrengoService service.
// All implementations must embed UnimplementedGrengoServiceServer
// for forward compatibility.
//
// GrengoService handles incoming communication from backend nodes to the central orchestrator
type GrengoServiceServer interface {
	ReportStatus(context.Context, *ReportStatusRequest) (*ReportStatusResponse, error)
	mustEmbedUnimplementedGrengoServiceServer()
}

// UnimplementedGrengoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGrengoServiceServer struct{}

func (UnimplementedGrengoServiceServer) ReportStatus(context.Context, *ReportStatusRequest) (*ReportStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportStatus not implemented")
}
func (UnimplementedGrengoServiceServer) mustEmbedUnimplementedGrengoServiceServer() {}
func (UnimplementedGrengoServiceServer) testEmbeddedByValue()                       {}

// UnsafeGrengoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GrengoServiceServer will
// result in compilation errors.
type UnsafeGrengoServiceServer interface {
	mustEmbedUnimplementedGrengoServiceServer()
}

func RegisterGrengoServiceServer(s grpc.ServiceRegistrar, srv GrengoServiceServer) {
	// If the following call panics, it indicates UnimplementedGrengoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GrengoService_ServiceDesc, srv)
}

func _GrengoService_ReportStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrengoServiceServer).ReportStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrengoService_ReportStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrengoServiceServer).ReportStatus(ctx, req.(*ReportStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GrengoService_ServiceDesc is the grpc.ServiceDesc for GrengoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GrengoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "skaia.grpc.GrengoService",
	HandlerType: (*GrengoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportStatus",
			Handler:    _GrengoService_ReportStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/skaia.proto",
}

const (
	BackendService_GetStorage_FullMethodName = "/skaia.grpc.BackendService/GetStorage"
)

// BackendServiceClient is the client API for BackendService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BackendService handles communication from Grengo to individual backend nodes
type BackendServiceClient interface {
	GetStorage(ctx context.Context, in *GetStorageRequest, opts ...grpc.CallOption) (*GetStorageResponse, error)
}

type backendServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBackendServiceClient(cc grpc.ClientConnInterface) BackendServiceClient {
	return &backendServiceClient{cc}
}

func (c *backendServiceClient) GetStorage(ctx context.Context, in *GetStorageRequest, opts ...grpc.CallOption) (*GetStorageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStorageResponse)
	err := c.cc.Invoke(ctx, BackendService_GetStorage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BackendServiceServer is the server API for BackendService service.
// All implementations must embed UnimplementedBackendServiceServer
// for forward compatibility.
//
// BackendService handles communication from Grengo to individual backend nodes
type BackendServiceServer interface {
	GetStorage(context.Context, *GetStorageRequest) (*GetStorageResponse, error)
	mustEmbedUnimplementedBackendServiceServer()
}

// UnimplementedBackendServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBackendServiceServer struct{}

func (UnimplementedBackendServiceServer) GetStorage(context.Context, *GetStorageRequest) (*GetStorageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStorage not implemented")
}
func (UnimplementedBackendServiceServer) mustEmbedUnimplementedBackendServiceServer() {}
func (UnimplementedBackendServiceServer) testEmbeddedByValue()                        {}

// UnsafeBackendServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BackendServiceServer will
// result in compilation errors.
type UnsafeBackendServiceServer interface {
	mustEmbedUnimplementedBackendServiceServer()
}

func RegisterBackendServiceServer(s grpc.ServiceRegistrar, srv BackendServiceServer) {
	// If the following call panics, it indicates UnimplementedBackendServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BackendService_ServiceDesc, srv)
}

func _BackendService_GetStorage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStorageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendServiceServer).GetStorage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackendService_GetStorage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendServiceServer).GetStorage(ctx, req.(*GetStorageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BackendService_ServiceDesc is the grpc.ServiceDesc for BackendService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BackendService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "skaia.grpc.BackendService",
	HandlerType: (*BackendServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStorage",
			Handler:    _BackendService_GetStorage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/skaia.proto",
}

const (
	GoFTWService_SetupInit_FullMethodName       = "/skaia.grpc.GoFTWService/SetupInit"
	GoFTWService_CheckoutSites_FullMethodName   = "/skaia.grpc.GoFTWService/CheckoutSites"
	GoFTWService_StartDeployment_FullMethodName = "/skaia.grpc.GoFTWService/StartDeployment"
	GoFTWService_InstallApps_FullMethodName     = "/skaia.grpc.GoFTWService/InstallApps"
	GoFTWService_ListSites_FullMethodName       = "/skaia.grpc.GoFTWService/ListSites"
	GoFTWService_CheckSite_FullMethodName       = "/skaia.grpc.GoFTWService/CheckSite"
	GoFTWService_ReloadNginx_FullMethodName     = "/skaia.grpc.GoFTWService/ReloadNginx"
	GoFTWService_GetApps_FullMethodName         = "/skaia.grpc.GoFTWService/GetApps"
	GoFTWService_GetSiteApps_FullMethodName     = "/skaia.grpc.GoFTWService/GetSiteApps"
	GoFTWService_InstallApp_FullMethodName      = "/skaia.grpc.GoFTWService/InstallApp"
	GoFTWService_UninstallApp_FullMethodName    = "/skaia.grpc.GoFTWService/UninstallApp"
)

// GoFTWServiceClient is the client API for GoFTWService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GoFTWService handles orchestration of the frappe cluster instances
type GoFTWServiceClient interface {
	SetupInit(ctx context.Context, in *SetupInitRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogStreamResponse], error)
	CheckoutSites(ctx context.Context, in *CheckoutSitesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogStreamResponse], error)
	StartDeployment(ctx context.Context, in *StartDeploymentRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogStreamResponse], error)
	InstallApps(ctx context.Context, in *InstallAppsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogStreamResponse], error)
	ListSites(ctx context.Context, in *ListSitesRequest, opts ...grpc.CallOption) (*ListSitesResponse, error)
	CheckSite(ctx context.Context, in *CheckSiteRequest, opts ...grpc.CallOption) (*CheckSiteResponse, error)
	ReloadNginx(ctx context.Context, in *ReloadNginxRequest, opts ...grpc.CallOption) (*ReloadNginxResponse, error)
	GetApps(ctx context.Context, in *GetAppsRequest, opts ...grpc.CallOption) (*GetAppsResponse, error)
	GetSiteApps(ctx context.Context, in *GetSiteAppsRequest, opts ...grpc.CallOption) (*GetSiteAppsResponse, error)
	InstallApp(ctx context.Context, in *InstallAppRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogStreamResponse], error)
	UninstallApp(ctx context.Context, in *UninstallAppRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogStreamResponse], error)
}

type goFTWServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGoFTWServiceClient(cc grpc.ClientConnInterface) GoFTWServiceClient {
	return &goFTWServiceClient{cc}
}

func (c *goFTWServiceClient) SetupInit(ctx context.Context, in *SetupInitRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GoFTWService_ServiceDesc.Streams[0], GoFTWService_SetupInit_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SetupInitRequest, LogStreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GoFTWService_SetupInitClient = grpc.ServerStreamingClient[LogStreamResponse]

func (c *goFTWServiceClient) CheckoutSites(ctx context.Context, in *CheckoutSitesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GoFTWService_ServiceDesc.Streams[1], GoFTWService_CheckoutSites_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CheckoutSitesRequest, LogStreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GoFTWService_CheckoutSitesClient = grpc.ServerStreamingClient[LogStreamResponse]

func (c *goFTWServiceClient) StartDeployment(ctx context.Context, in *StartDeploymentRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GoFTWService_ServiceDesc.Streams[2], GoFTWService_StartDeployment_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StartDeploymentRequest, LogStreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GoFTWService_StartDeploymentClient = grpc.ServerStreamingClient[LogStreamResponse]

func (c *goFTWServiceClient) InstallApps(ctx context.Context, in *InstallAppsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GoFTWService_ServiceDesc.Streams[3], GoFTWService_InstallApps_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[InstallAppsRequest, LogStreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GoFTWService_InstallAppsClient = grpc.ServerStreamingClient[LogStreamResponse]

func (c *goFTWServiceClient) ListSites(ctx context.Context, in *ListSitesRequest, opts ...grpc.CallOption) (*ListSitesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSitesResponse)
	err := c.cc.Invoke(ctx, GoFTWService_ListSites_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goFTWServiceClient) CheckSite(ctx context.Context, in *CheckSiteRequest, opts ...grpc.CallOption) (*CheckSiteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckSiteResponse)
	err := c.cc.Invoke(ctx, GoFTWService_CheckSite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goFTWServiceClient) ReloadNginx(ctx context.Context, in *ReloadNginxRequest, opts ...grpc.CallOption) (*ReloadNginxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReloadNginxResponse)
	err := c.cc.Invoke(ctx, GoFTWService_ReloadNginx_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goFTWServiceClient) GetApps(ctx context.Context, in *GetAppsRequest, opts ...grpc.CallOption) (*GetAppsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAppsResponse)
	err := c.cc.Invoke(ctx, GoFTWService_GetApps_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goFTWServiceClient) GetSiteApps(ctx context.Context, in *GetSiteAppsRequest, opts ...grpc.CallOption) (*GetSiteAppsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSiteAppsResponse)
	err := c.cc.Invoke(ctx, GoFTWService_GetSiteApps_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goFTWServiceClient) InstallApp(ctx context.Context, in *InstallAppRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GoFTWService_ServiceDesc.Streams[4], GoFTWService_InstallApp_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[InstallAppRequest, LogStreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GoFTWService_InstallAppClient = grpc.ServerStreamingClient[LogStreamResponse]

func (c *goFTWServiceClient) UninstallApp(ctx context.Context, in *UninstallAppRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GoFTWService_ServiceDesc.Streams[5], GoFTWService_UninstallApp_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UninstallAppRequest, LogStreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GoFTWService_UninstallAppClient = grpc.ServerStreamingClient[LogStreamResponse]

// GoFTWServiceServer is the server API for GoFTWService service.
// All implementations must embed UnimplementedGoFTWServiceServer
// for forward compatibility.
//
// GoFTWService handles orchestration of the frappe cluster instances
type GoFTWServiceServer interface {
	SetupInit(*SetupInitRequest, grpc.ServerStreamingServer[LogStreamResponse]) error
	CheckoutSites(*CheckoutSitesRequest, grpc.ServerStreamingServer[LogStreamResponse]) error
	StartDeployment(*StartDeploymentRequest, grpc.ServerStreamingServer[LogStreamResponse]) error
	InstallApps(*InstallAppsRequest, grpc.ServerStreamingServer[LogStreamResponse]) error
	ListSites(context.Context, *ListSitesRequest) (*ListSitesResponse, error)
	CheckSite(context.Context, *CheckSiteRequest) (*CheckSiteResponse, error)
	ReloadNginx(context.Context, *ReloadNginxRequest) (*ReloadNginxResponse, error)
	GetApps(context.Context, *GetAppsRequest) (*GetAppsResponse, error)
	GetSiteApps(context.Context, *GetSiteAppsRequest) (*GetSiteAppsResponse, error)
	InstallApp(*InstallAppRequest, grpc.ServerStreamingServer[LogStreamResponse]) error
	UninstallApp(*UninstallAppRequest, grpc.ServerStreamingServer[LogStreamResponse]) error
	mustEmbedUnimplementedGoFTWServiceServer()
}

// UnimplementedGoFTWServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGoFTWServiceServer struct{}

func (UnimplementedGoFTWServiceServer) SetupInit(*SetupInitRequest, grpc.ServerStreamingServer[LogStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method SetupInit not implemented")
}
func (UnimplementedGoFTWServiceServer) CheckoutSites(*CheckoutSitesRequest, grpc.ServerStreamingServer[LogStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method CheckoutSites not implemented")
}
func (UnimplementedGoFTWServiceServer) StartDeployment(*StartDeploymentRequest, grpc.ServerStreamingServer[LogStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method StartDeployment not implemented")
}
func (UnimplementedGoFTWServiceServer) InstallApps(*InstallAppsRequest, grpc.ServerStreamingServer[LogStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method InstallApps not implemented")
}
func (UnimplementedGoFTWServiceServer) ListSites(context.Context, *ListSitesRequest) (*ListSitesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSites not implemented")
}
func (UnimplementedGoFTWServiceServer) CheckSite(context.Context, *CheckSiteRequest) (*CheckSiteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckSite not implemented")
}
func (UnimplementedGoFTWServiceServer) ReloadNginx(context.Context, *ReloadNginxRequest) (*ReloadNginxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReloadNginx not implemented")
}
func (UnimplementedGoFTWServiceServer) GetApps(context.Context, *GetAppsRequest) (*GetAppsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetApps not implemented")
}
func (UnimplementedGoFTWServiceServer) GetSiteApps(context.Context, *GetSiteAppsRequest) (*GetSiteAppsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSiteApps not implemented")
}
func (UnimplementedGoFTWServiceServer) InstallApp(*InstallAppRequest, grpc.ServerStreamingServer[LogStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method InstallApp not implemented")
}
func (UnimplementedGoFTWServiceServer) UninstallApp(*UninstallAppRequest, grpc.ServerStreamingServer[LogStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method UninstallApp not implemented")
}
func (UnimplementedGoFTWServiceServer) mustEmbedUnimplementedGoFTWServiceServer() {}
func (UnimplementedGoFTWServiceServer) testEmbeddedByValue()                      {}

// UnsafeGoFTWServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GoFTWServiceServer will
// result in compilation errors.
type UnsafeGoFTWServiceServer interface {
	mustEmbedUnimplementedGoFTWServiceServer()
}

func RegisterGoFTWServiceServer(s grpc.ServiceRegistrar, srv GoFTWServiceServer) {
	// If the following call panics, it indicates UnimplementedGoFTWServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GoFTWService_ServiceDesc, srv)
}

func _GoFTWService_SetupInit_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SetupInitRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GoFTWServiceServer).SetupInit(m, &grpc.GenericServerStream[SetupInitRequest, LogStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GoFTWService_SetupInitServer = grpc.ServerStreamingServer[LogStreamResponse]

func _GoFTWService_CheckoutSites_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CheckoutSitesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GoFTWServiceServer).CheckoutSites(m, &grpc.GenericServerStream[CheckoutSitesRequest, LogStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GoFTWService_CheckoutSitesServer = grpc.ServerStreamingServer[LogStreamResponse]

func _GoFTWService_StartDeployment_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StartDeploymentRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GoFTWServiceServer).StartDeployment(m, &grpc.GenericServerStream[StartDeploymentRequest, LogStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GoFTWService_StartDeploymentServer = grpc.ServerStreamingServer[LogStreamResponse]

func _GoFTWService_InstallApps_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(InstallAppsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GoFTWServiceServer).InstallApps(m, &grpc.GenericServerStream[InstallAppsRequest, LogStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GoFTWService_InstallAppsServer = grpc.ServerStreamingServer[LogStreamResponse]

func _GoFTWService_ListSites_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSitesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoFTWServiceServer).ListSites(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoFTWService_ListSites_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoFTWServiceServer).ListSites(ctx, req.(*ListSitesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoFTWService_CheckSite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckSiteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoFTWServiceServer).CheckSite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoFTWService_CheckSite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoFTWServiceServer).CheckSite(ctx, req.(*CheckSiteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoFTWService_ReloadNginx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReloadNginxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoFTWServiceServer).ReloadNginx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoFTWService_ReloadNginx_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoFTWServiceServer).ReloadNginx(ctx, req.(*ReloadNginxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoFTWService_GetApps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAppsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoFTWServiceServer).GetApps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoFTWService_GetApps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoFTWServiceServer).GetApps(ctx, req.(*GetAppsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoFTWService_GetSiteApps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSiteAppsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoFTWServiceServer).GetSiteApps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoFTWService_GetSiteApps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoFTWServiceServer).GetSiteApps(ctx, req.(*GetSiteAppsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoFTWService_InstallApp_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(InstallAppRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GoFTWServiceServer).InstallApp(m, &grpc.GenericServerStream[InstallAppRequest, LogStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GoFTWService_InstallAppServer = grpc.ServerStreamingServer[LogStreamResponse]

func _GoFTWService_UninstallApp_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(UninstallAppRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GoFTWServiceServer).UninstallApp(m, &grpc.GenericServerStream[UninstallAppRequest, LogStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GoFTWService_UninstallAppServer = grpc.ServerStreamingServer[LogStreamResponse]

// GoFTWService_ServiceDesc is the grpc.ServiceDesc for GoFTWService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GoFTWService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "skaia.grpc.GoFTWService",
	HandlerType: (*GoFTWServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListSites",
			Handler:    _GoFTWService_ListSites_Handler,
		},
		{
			MethodName: "CheckSite",
			Handler:    _GoFTWService_CheckSite_Handler,
		},
		{
			MethodName: "ReloadNginx",
			Handler:    _GoFTWService_ReloadNginx_Handler,
		},
		{
			MethodName: "GetApps",
			Handler:    _GoFTWService_GetApps_Handler,
		},
		{
			MethodName: "GetSiteApps",
			Handler:    _GoFTWService_GetSiteApps_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SetupInit",
			Handler:       _GoFTWService_SetupInit_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "CheckoutSites",
			Handler:       _GoFTWService_CheckoutSites_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StartDeployment",
			Handler:       _GoFTWService_StartDeployment_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "InstallApps",
			Handler:       _GoFTWService_InstallApps_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "InstallApp",
			Handler:       _GoFTWService_InstallApp_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "UninstallApp",
			Handler:       _GoFTWService_UninstallApp_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/skaia.proto",
}
