// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/skaia.proto

package skaia

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ----------------------------------------------------
// GrengoService Messages
// ----------------------------------------------------
type ReportStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportStatusRequest) Reset() {
	*x = ReportStatusRequest{}
	mi := &file_proto_skaia_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportStatusRequest) ProtoMessage() {}

func (x *ReportStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_skaia_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportStatusRequest.ProtoReflect.Descriptor instead.
func (*ReportStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_skaia_proto_rawDescGZIP(), []int{0}
}

func (x *ReportStatusRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ReportStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ReportStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportStatusResponse) Reset() {
	*x = ReportStatusResponse{}
	mi := &file_proto_skaia_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportStatusResponse) ProtoMessage() {}

func (x *ReportStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_skaia_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportStatusResponse.ProtoReflect.Descriptor instead.
func (*ReportStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_skaia_proto_rawDescGZIP(), []int{1}
}

func (x *ReportStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// ----------------------------------------------------
// BackendService Messages
// ----------------------------------------------------
type GetStorageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStorageRequest) Reset() {
	*x = GetStorageRequest{}
	mi := &file_proto_skaia_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStorageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStorageRequest) ProtoMessage() {}

func (x *GetStorageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_skaia_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStorageRequest.ProtoReflect.Descriptor instead.
func (*GetStorageRequest) Descriptor() ([]byte, []int) {
	return file_proto_skaia_proto_rawDescGZIP(), []int{2}
}

type GetStorageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// We can serialize the existing JSON response or define strict fields
	StorageJson   string `protobuf:"bytes,1,opt,name=storage_json,json=storageJson,proto3" json:"storage_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStorageResponse) Reset() {
	*x = GetStorageResponse{}
	mi := &file_proto_skaia_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStorageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStorageResponse) ProtoMessage() {}

func (x *GetStorageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_skaia_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStorageResponse.ProtoReflect.Descriptor instead.
func (*GetStorageResponse) Descriptor() ([]byte, []int) {
	return file_proto_skaia_proto_rawDescGZIP(), []int{3}
}

func (x *GetStorageResponse) GetStorageJson() string {
	if x != nil {
		return x.StorageJson
	}
	return ""
}

// ----------------------------------------------------
// GoFTWService Messages
// ----------------------------------------------------
type LogStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        string                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogStreamResponse) Reset() {
	*x = LogStreamResponse{}
	mi := &file_proto_skaia_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogStreamResponse) ProtoMessage() {}

func (x *LogStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_skaia_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogStreamResponse.ProtoReflect.Descriptor instead.
func (*LogStreamResponse) Descriptor() ([]byte, []int) {
	return file_proto_skaia_proto_rawDescGZIP(), []int{4}
}

func (x *LogStreamResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

type SetupInitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Branch        string                 `protobuf:"bytes,1,opt,name=branch,proto3" json:"branch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetupInitRequest) Reset() {
	*x = SetupInitRequest{}
	mi := &file_proto_skaia_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetupInitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupInitRequest) ProtoMessage() {}

func (x *SetupInitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_skaia_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupInitRequest.ProtoReflect.Descriptor instead.
func (*SetupInitRequest) Descriptor() ([]byte, []int) {
	return file_proto_skaia_proto_rawDescGZIP(), []int{5}
}

func (x *SetupInitRequest) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

type CheckoutSitesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckoutSitesRequest) Reset() {
	*x = CheckoutSitesRequest{}
	mi := &file_proto_skaia_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckoutSitesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckoutSitesRequest) ProtoMessage() {}

func (x *CheckoutSitesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_skaia_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckoutSitesRequest.ProtoReflect.Descriptor instead.
func (*CheckoutSitesRequest) Descriptor() ([]byte, []int) {
	return file_proto_skaia_proto_rawDescGZIP(), []int{6}
}

type StartDeploymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deployment    string                 `protobuf:"bytes,1,opt,name=deployment,proto3" json:"deployment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartDeploymentRequest) Reset() {
	*x = StartDeploymentRequest{}
	mi := &file_proto_skaia_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartDeploymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartDeploymentRequest) ProtoMessage() {}

func (x *StartDeploymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_skaia_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartDeploymentRequest.ProtoReflect.Descriptor instead.
func (*StartDeploymentRequest) Descriptor() ([]byte, []int) {
	return file_proto_skaia_proto_rawDescGZIP(), []int{7}
}

func (x *StartDeploymentRequest) GetDeployment() string {
	if x != nil {
		return x.Deployment
	}
	return ""
}

type InstallAppsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SiteName      string                 `protobuf:"bytes,1,opt,name=site_name,json=siteName,proto3" json:"site_name,omitempty"`
	Apps          []string               `protobuf:"bytes,2,rep,name=apps,proto3" json:"apps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallAppsRequest) Reset() {
	*x = InstallAppsRequest{}
	mi := &file_proto_skaia_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallAppsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallAppsRequest) ProtoMessage() {}

func (x *InstallAppsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_skaia_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallAppsRequest.ProtoReflect.Descriptor instead.
func (*InstallAppsRequest) Descriptor() ([]byte, []int) {
	return file_proto_skaia_proto_rawDescGZIP(), []int{8}
}

func (x *InstallAppsRequest) GetSiteName() string {
	if x != nil {
		return x.SiteName
	}
	return ""
}

func (x *InstallAppsRequest) GetApps() []string {
	if x != nil {
		return x.Apps
	}
	return nil
}

type ListSitesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSitesRequest) Reset() {
	*x = ListSitesRequest{}
	mi := &file_proto_skaia_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSitesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSitesRequest) ProtoMessage() {}

func (x *ListSitesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_skaia_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSitesRequest.ProtoReflect.Descriptor instead.
func (*ListSitesRequest) Descriptor() ([]byte, []int) {
	return file_proto_skaia_proto_rawDescGZIP(), []int{9}
}

type ListSitesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sites         []string               `protobuf:"bytes,1,rep,name=sites,proto3" json:"sites,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSitesResponse) Reset() {
	*x = ListSitesResponse{}
	mi := &file_proto_skaia_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSitesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSitesResponse) ProtoMessage() {}

func (x *ListSitesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_skaia_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSitesResponse.ProtoReflect.Descriptor instead.
func (*ListSitesResponse) Descriptor() ([]byte, []int) {
	return file_proto_skaia_proto_rawDescGZIP(), []int{10}
}

func (x *ListSitesResponse) GetSites() []string {
	if x != nil {
		return x.Sites
	}
	return nil
}

type CheckSiteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SiteName      string                 `protobuf:"bytes,1,opt,name=site_name,json=siteName,proto3" json:"site_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckSiteRequest) Reset() {
	*x = CheckSiteRequest{}
	mi := &file_proto_skaia_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckSiteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckSiteRequest) ProtoMessage() {}

func (x *CheckSiteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_skaia_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckSiteRequest.ProtoReflect.Descriptor instead.
func (*CheckSiteRequest) Descriptor() ([]byte, []int) {
	return file_proto_skaia_proto_rawDescGZIP(), []int{11}
}

func (x *CheckSiteRequest) GetSiteName() string {
	if x != nil {
		return x.SiteName
	}
	return ""
}

type CheckSiteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusJson    string                 `protobuf:"bytes,1,opt,name=status_json,json=statusJson,proto3" json:"status_json,omitempty"` // Or defined strictly
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckSiteResponse) Reset() {
	*x = CheckSiteResponse{}
	mi := &file_proto_skaia_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckSiteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckSiteResponse) ProtoMessage() {}

func (x *CheckSiteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_skaia_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckSiteResponse.ProtoReflect.Descriptor instead.
func (*CheckSiteResponse) Descriptor() ([]byte, []int) {
	return file_proto_skaia_proto_rawDescGZIP(), []int{12}
}

func (x *CheckSiteResponse) GetStatusJson() string {
	if x != nil {
		return x.StatusJson
	}
	return ""
}

type ReloadNginxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadNginxRequest) Reset() {
	*x = ReloadNginxRequest{}
	mi := &file_proto_skaia_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadNginxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadNginxRequest) ProtoMessage() {}

func (x *ReloadNginxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_skaia_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadNginxRequest.ProtoReflect.Descriptor instead.
func (*ReloadNginxRequest) Descriptor() ([]byte, []int) {
	return file_proto_skaia_proto_rawDescGZIP(), []int{13}
}

type ReloadNginxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadNginxResponse) Reset() {
	*x = ReloadNginxResponse{}
	mi := &file_proto_skaia_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadNginxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadNginxResponse) ProtoMessage() {}

func (x *ReloadNginxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_skaia_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadNginxResponse.ProtoReflect.Descriptor instead.
func (*ReloadNginxResponse) Descriptor() ([]byte, []int) {
	return file_proto_skaia_proto_rawDescGZIP(), []int{14}
}

func (x *ReloadNginxResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetAppsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAppsRequest) Reset() {
	*x = GetAppsRequest{}
	mi := &file_proto_skaia_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppsRequest) ProtoMessage() {}

func (x *GetAppsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_skaia_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppsRequest.ProtoReflect.Descriptor instead.
func (*GetAppsRequest) Descriptor() ([]byte, []int) {
	return file_proto_skaia_proto_rawDescGZIP(), []int{15}
}

type GetAppsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Apps          []string               `protobuf:"bytes,1,rep,name=apps,proto3" json:"apps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAppsResponse) Reset() {
	*x = GetAppsResponse{}
	mi := &file_proto_skaia_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppsResponse) ProtoMessage() {}

func (x *GetAppsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_skaia_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppsResponse.ProtoReflect.Descriptor instead.
func (*GetAppsResponse) Descriptor() ([]byte, []int) {
	return file_proto_skaia_proto_rawDescGZIP(), []int{16}
}

func (x *GetAppsResponse) GetApps() []string {
	if x != nil {
		return x.Apps
	}
	return nil
}

type GetSiteAppsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SiteName      string                 `protobuf:"bytes,1,opt,name=site_name,json=siteName,proto3" json:"site_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSiteAppsRequest) Reset() {
	*x = GetSiteAppsRequest{}
	mi := &file_proto_skaia_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSiteAppsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSiteAppsRequest) ProtoMessage() {}

func (x *GetSiteAppsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_skaia_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSiteAppsRequest.ProtoReflect.Descriptor instead.
func (*GetSiteAppsRequest) Descriptor() ([]byte, []int) {
	return file_proto_skaia_proto_rawDescGZIP(), []int{17}
}

func (x *GetSiteAppsRequest) GetSiteName() string {
	if x != nil {
		return x.SiteName
	}
	return ""
}

type GetSiteAppsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Apps          []string               `protobuf:"bytes,1,rep,name=apps,proto3" json:"apps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSiteAppsResponse) Reset() {
	*x = GetSiteAppsResponse{}
	mi := &file_proto_skaia_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSiteAppsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSiteAppsResponse) ProtoMessage() {}

func (x *GetSiteAppsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_skaia_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSiteAppsResponse.ProtoReflect.Descriptor instead.
func (*GetSiteAppsResponse) Descriptor() ([]byte, []int) {
	return file_proto_skaia_proto_rawDescGZIP(), []int{18}
}

func (x *GetSiteAppsResponse) GetApps() []string {
	if x != nil {
		return x.Apps
	}
	return nil
}

type InstallAppRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SiteName      string                 `protobuf:"bytes,1,opt,name=site_name,json=siteName,proto3" json:"site_name,omitempty"`
	AppName       string                 `protobuf:"bytes,2,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallAppRequest) Reset() {
	*x = InstallAppRequest{}
	mi := &file_proto_skaia_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallAppRequest) ProtoMessage() {}

func (x *InstallAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_skaia_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallAppRequest.ProtoReflect.Descriptor instead.
func (*InstallAppRequest) Descriptor() ([]byte, []int) {
	return file_proto_skaia_proto_rawDescGZIP(), []int{19}
}

func (x *InstallAppRequest) GetSiteName() string {
	if x != nil {
		return x.SiteName
	}
	return ""
}

func (x *InstallAppRequest) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

type UninstallAppRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SiteName      string                 `protobuf:"bytes,1,opt,name=site_name,json=siteName,proto3" json:"site_name,omitempty"`
	AppName       string                 `protobuf:"bytes,2,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UninstallAppRequest) Reset() {
	*x = UninstallAppRequest{}
	mi := &file_proto_skaia_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UninstallAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UninstallAppRequest) ProtoMessage() {}

func (x *UninstallAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_skaia_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UninstallAppRequest.ProtoReflect.Descriptor instead.
func (*UninstallAppRequest) Descriptor() ([]byte, []int) {
	return file_proto_skaia_proto_rawDescGZIP(), []int{20}
}

func (x *UninstallAppRequest) GetSiteName() string {
	if x != nil {
		return x.SiteName
	}
	return ""
}

func (x *UninstallAppRequest) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

var File_proto_skaia_proto protoreflect.FileDescriptor

const file_proto_skaia_proto_rawDesc = "" +
	"\n" +
	"\x11proto/skaia.proto\x12\n" +
	"skaia.grpc\"F\n" +
	"\x13ReportStatusRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"0\n" +
	"\x14ReportStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x13\n" +
	"\x11GetStorageRequest\"7\n" +
	"\x12GetStorageResponse\x12!\n" +
	"\fstorage_json\x18\x01 \x01(\tR\vstorageJson\"+\n" +
	"\x11LogStreamResponse\x12\x16\n" +
	"\x06output\x18\x01 \x01(\tR\x06output\"*\n" +
	"\x10SetupInitRequest\x12\x16\n" +
	"\x06branch\x18\x01 \x01(\tR\x06branch\"\x16\n" +
	"\x14CheckoutSitesRequest\"8\n" +
	"\x16StartDeploymentRequest\x12\x1e\n" +
	"\n" +
	"deployment\x18\x01 \x01(\tR\n" +
	"deployment\"E\n" +
	"\x12InstallAppsRequest\x12\x1b\n" +
	"\tsite_name\x18\x01 \x01(\tR\bsiteName\x12\x12\n" +
	"\x04apps\x18\x02 \x03(\tR\x04apps\"\x12\n" +
	"\x10ListSitesRequest\")\n" +
	"\x11ListSitesResponse\x12\x14\n" +
	"\x05sites\x18\x01 \x03(\tR\x05sites\"/\n" +
	"\x10CheckSiteRequest\x12\x1b\n" +
	"\tsite_name\x18\x01 \x01(\tR\bsiteName\"4\n" +
	"\x11CheckSiteResponse\x12\x1f\n" +
	"\vstatus_json\x18\x01 \x01(\tR\n" +
	"statusJson\"\x14\n" +
	"\x12ReloadNginxRequest\"/\n" +
	"\x13ReloadNginxResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x10\n" +
	"\x0eGetAppsRequest\"%\n" +
	"\x0fGetAppsResponse\x12\x12\n" +
	"\x04apps\x18\x01 \x03(\tR\x04apps\"1\n" +
	"\x12GetSiteAppsRequest\x12\x1b\n" +
	"\tsite_name\x18\x01 \x01(\tR\bsiteName\")\n" +
	"\x13GetSiteAppsResponse\x12\x12\n" +
	"\x04apps\x18\x01 \x03(\tR\x04apps\"K\n" +
	"\x11InstallAppRequest\x12\x1b\n" +
	"\tsite_name\x18\x01 \x01(\tR\bsiteName\x12\x19\n" +
	"\bapp_name\x18\x02 \x01(\tR\aappName\"M\n" +
	"\x13UninstallAppRequest\x12\x1b\n" +
	"\tsite_name\x18\x01 \x01(\tR\bsiteName\x12\x19\n" +
	"\bapp_name\x18\x02 \x01(\tR\aappName2b\n" +
	"\rGrengoService\x12Q\n" +
	"\fReportStatus\x12\x1f.skaia.grpc.ReportStatusRequest\x1a .skaia.grpc.ReportStatusResponse2]\n" +
	"\x0eBackendService\x12K\n" +
	"\n" +
	"GetStorage\x12\x1d.skaia.grpc.GetStorageRequest\x1a\x1e.skaia.grpc.GetStorageResponse2\xee\x06\n" +
	"\fGoFTWService\x12J\n" +
	"\tSetupInit\x12\x1c.skaia.grpc.SetupInitRequest\x1a\x1d.skaia.grpc.LogStreamResponse0\x01\x12R\n" +
	"\rCheckoutSites\x12 .skaia.grpc.CheckoutSitesRequest\x1a\x1d.skaia.grpc.LogStreamResponse0\x01\x12V\n" +
	"\x0fStartDeployment\x12\".skaia.grpc.StartDeploymentRequest\x1a\x1d.skaia.grpc.LogStreamResponse0\x01\x12N\n" +
	"\vInstallApps\x12\x1e.skaia.grpc.InstallAppsRequest\x1a\x1d.skaia.grpc.LogStreamResponse0\x01\x12H\n" +
	"\tListSites\x12\x1c.skaia.grpc.ListSitesRequest\x1a\x1d.skaia.grpc.ListSitesResponse\x12H\n" +
	"\tCheckSite\x12\x1c.skaia.grpc.CheckSiteRequest\x1a\x1d.skaia.grpc.CheckSiteResponse\x12N\n" +
	"\vReloadNginx\x12\x1e.skaia.grpc.ReloadNginxRequest\x1a\x1f.skaia.grpc.ReloadNginxResponse\x12B\n" +
	"\aGetApps\x12\x1a.skaia.grpc.GetAppsRequest\x1a\x1b.skaia.grpc.GetAppsResponse\x12N\n" +
	"\vGetSiteApps\x12\x1e.skaia.grpc.GetSiteAppsRequest\x1a\x1f.skaia.grpc.GetSiteAppsResponse\x12L\n" +
	"\n" +
	"InstallApp\x12\x1d.skaia.grpc.InstallAppRequest\x1a\x1d.skaia.grpc.LogStreamResponse0\x01\x12P\n" +
	"\fUninstallApp\x12\x1f.skaia.grpc.UninstallAppRequest\x1a\x1d.skaia.grpc.LogStreamResponse0\x01B\x1dZ\x1bgithub.com/skaia/grpc/skaiab\x06proto3"

var (
	file_proto_skaia_proto_rawDescOnce sync.Once
	file_proto_skaia_proto_rawDescData []byte
)

func file_proto_skaia_proto_rawDescGZIP() []byte {
	file_proto_skaia_proto_rawDescOnce.Do(func() {
		file_proto_skaia_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_skaia_proto_rawDesc), len(file_proto_skaia_proto_rawDesc)))
	})
	return file_proto_skaia_proto_rawDescData
}

var file_proto_skaia_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_proto_skaia_proto_goTypes = []any{
	(*ReportStatusRequest)(nil),    // 0: skaia.grpc.ReportStatusRequest
	(*ReportStatusResponse)(nil),   // 1: skaia.grpc.ReportStatusResponse
	(*GetStorageRequest)(nil),      // 2: skaia.grpc.GetStorageRequest
	(*GetStorageResponse)(nil),     // 3: skaia.grpc.GetStorageResponse
	(*LogStreamResponse)(nil),      // 4: skaia.grpc.LogStreamResponse
	(*SetupInitRequest)(nil),       // 5: skaia.grpc.SetupInitRequest
	(*CheckoutSitesRequest)(nil),   // 6: skaia.grpc.CheckoutSitesRequest
	(*StartDeploymentRequest)(nil), // 7: skaia.grpc.StartDeploymentRequest
	(*InstallAppsRequest)(nil),     // 8: skaia.grpc.InstallAppsRequest
	(*ListSitesRequest)(nil),       // 9: skaia.grpc.ListSitesRequest
	(*ListSitesResponse)(nil),      // 10: skaia.grpc.ListSitesResponse
	(*CheckSiteRequest)(nil),       // 11: skaia.grpc.CheckSiteRequest
	(*CheckSiteResponse)(nil),      // 12: skaia.grpc.CheckSiteResponse
	(*ReloadNginxRequest)(nil),     // 13: skaia.grpc.ReloadNginxRequest
	(*ReloadNginxResponse)(nil),    // 14: skaia.grpc.ReloadNginxResponse
	(*GetAppsRequest)(nil),         // 15: skaia.grpc.GetAppsRequest
	(*GetAppsResponse)(nil),        // 16: skaia.grpc.GetAppsResponse
	(*GetSiteAppsRequest)(nil),     // 17: skaia.grpc.GetSiteAppsRequest
	(*GetSiteAppsResponse)(nil),    // 18: skaia.grpc.GetSiteAppsResponse
	(*InstallAppRequest)(nil),      // 19: skaia.grpc.InstallAppRequest
	(*UninstallAppRequest)(nil),    // 20: skaia.grpc.UninstallAppRequest
}
var file_proto_skaia_proto_depIdxs = []int32{
	0,  // 0: skaia.grpc.GrengoService.ReportStatus:input_type -> skaia.grpc.ReportStatusRequest
	2,  // 1: skaia.grpc.BackendService.GetStorage:input_type -> skaia.grpc.GetStorageRequest
	5,  // 2: skaia.grpc.GoFTWService.SetupInit:input_type -> skaia.grpc.SetupInitRequest
	6,  // 3: skaia.grpc.GoFTWService.CheckoutSites:input_type -> skaia.grpc.CheckoutSitesRequest
	7,  // 4: skaia.grpc.GoFTWService.StartDeployment:input_type -> skaia.grpc.StartDeploymentRequest
	8,  // 5: skaia.grpc.GoFTWService.InstallApps:input_type -> skaia.grpc.InstallAppsRequest
	9,  // 6: skaia.grpc.GoFTWService.ListSites:input_type -> skaia.grpc.ListSitesRequest
	11, // 7: skaia.grpc.GoFTWService.CheckSite:input_type -> skaia.grpc.CheckSiteRequest
	13, // 8: skaia.grpc.GoFTWService.ReloadNginx:input_type -> skaia.grpc.ReloadNginxRequest
	15, // 9: skaia.grpc.GoFTWService.GetApps:input_type -> skaia.grpc.GetAppsRequest
	17, // 10: skaia.grpc.GoFTWService.GetSiteApps:input_type -> skaia.grpc.GetSiteAppsRequest
	19, // 11: skaia.grpc.GoFTWService.InstallApp:input_type -> skaia.grpc.InstallAppRequest
	20, // 12: skaia.grpc.GoFTWService.UninstallApp:input_type -> skaia.grpc.UninstallAppRequest
	1,  // 13: skaia.grpc.GrengoService.ReportStatus:output_type -> skaia.grpc.ReportStatusResponse
	3,  // 14: skaia.grpc.BackendService.GetStorage:output_type -> skaia.grpc.GetStorageResponse
	4,  // 15: skaia.grpc.GoFTWService.SetupInit:output_type -> skaia.grpc.LogStreamResponse
	4,  // 16: skaia.grpc.GoFTWService.CheckoutSites:output_type -> skaia.grpc.LogStreamResponse
	4,  // 17: skaia.grpc.GoFTWService.StartDeployment:output_type -> skaia.grpc.LogStreamResponse
	4,  // 18: skaia.grpc.GoFTWService.InstallApps:output_type -> skaia.grpc.LogStreamResponse
	10, // 19: skaia.grpc.GoFTWService.ListSites:output_type -> skaia.grpc.ListSitesResponse
	12, // 20: skaia.grpc.GoFTWService.CheckSite:output_type -> skaia.grpc.CheckSiteResponse
	14, // 21: skaia.grpc.GoFTWService.ReloadNginx:output_type -> skaia.grpc.ReloadNginxResponse
	16, // 22: skaia.grpc.GoFTWService.GetApps:output_type -> skaia.grpc.GetAppsResponse
	18, // 23: skaia.grpc.GoFTWService.GetSiteApps:output_type -> skaia.grpc.GetSiteAppsResponse
	4,  // 24: skaia.grpc.GoFTWService.InstallApp:output_type -> skaia.grpc.LogStreamResponse
	4,  // 25: skaia.grpc.GoFTWService.UninstallApp:output_type -> skaia.grpc.LogStreamResponse
	13, // [13:26] is the sub-list for method output_type
	0,  // [0:13] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_proto_skaia_proto_init() }
func file_proto_skaia_proto_init() {
	if File_proto_skaia_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_skaia_proto_rawDesc), len(file_proto_skaia_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_proto_skaia_proto_goTypes,
		DependencyIndexes: file_proto_skaia_proto_depIdxs,
		MessageInfos:      file_proto_skaia_proto_msgTypes,
	}.Build()
	File_proto_skaia_proto = out.File
	file_proto_skaia_proto_goTypes = nil
	file_proto_skaia_proto_depIdxs = nil
}
