package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// clientInfo holds parsed data from a client's .env for nginx config generation.
type clientInfo struct {
	Name    string
	Port    string
	Domains []string
}

// expandDomains adds www. variants for production domains (not localhost or IPs).
func expandDomains(domains []string) []string {
	seen := map[string]bool{}
	var out []string
	for _, d := range domains {
		if seen[d] {
			continue
		}
		seen[d] = true
		out = append(out, d)
		// Add www. variant for real domains (skip localhost, IPs, already-www)
		if d != "localhost" && !strings.HasPrefix(d, "www.") && strings.Contains(d, ".") && !isIPAddress(d) {
			www := "www." + d
			if !seen[www] {
				seen[www] = true
				out = append(out, www)
			}
		}
	}
	return out
}

// isIPAddress returns true if the string looks like an IPv4 address.
func isIPAddress(s string) bool {
	for _, c := range s {
		if c != '.' && (c < '0' || c > '9') {
			return false
		}
	}
	return true
}

// enabledClients scans the backends directory and returns info for all enabled clients.
func enabledClients() []clientInfo {
	var clients []clientInfo
	entries, err := os.ReadDir(backendsDir())
	if err != nil {
		return clients
	}
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		dir := filepath.Join(backendsDir(), e.Name())
		// Skip disabled
		if _, err := os.Stat(filepath.Join(dir, ".disabled")); err == nil {
			continue
		}
		envFile := filepath.Join(dir, ".env")
		if _, err := os.Stat(envFile); err != nil {
			continue
		}
		name := envVal(envFile, "CLIENT_NAME")
		port := envVal(envFile, "PORT")
		domainsStr := envVal(envFile, "DOMAINS")
		if name == "" || port == "" {
			continue
		}
		var domains []string
		if domainsStr != "" {
			domains = expandDomains(strings.Fields(domainsStr))
		}
		clients = append(clients, clientInfo{Name: name, Port: port, Domains: domains})
	}
	return clients
}

// generateNginxConfig writes the nginx default.conf based on enabled clients.
func generateNginxConfig() {
	dir := nginxDir()
	if err := os.MkdirAll(dir, 0755); err != nil {
		die("Cannot create nginx directory: %v", err)
	}
	confPath := filepath.Join(dir, "default.conf")

	clients := enabledClients()

	// No enabled clients → 503 fallback
	if len(clients) == 0 {
		fallback := `server { listen 80 default_server; return 503 "No backends configured – run: grengo new <name>\n"; }` + "\n"
		if err := os.WriteFile(confPath, []byte(fallback), 0644); err != nil {
			die("Cannot write nginx config: %v", err)
		}
		warn("No enabled clients – nginx will return 503")
		return
	}

	var b strings.Builder

	// Header
	fmt.Fprintf(&b, "# Auto-generated by grengo – %s\n", time.Now().Format(time.RFC3339))
	b.WriteString("# Do not edit manually; run 'grengo nginx reload' to regenerate.\n\n")

	// Custom log format that includes $host and $upstream_addr for routing debug
	b.WriteString(`# ── Logging ────────────────────────────────────────────────────────────────
log_format routing '$remote_addr - [$time_local] host=$host '
                   '"$request" $status $body_bytes_sent '
                   'upstream=$upstream_addr '
                   '"$http_referer" "$http_x_forwarded_for"';

`)

	// gzip
	b.WriteString(`# ── gzip ───────────────────────────────────────────────────────────────────
gzip              on;
gzip_comp_level   5;
gzip_min_length   256;
gzip_vary         on;
gzip_proxied      any;
gzip_types
    text/plain text/css text/javascript text/xml
    application/javascript application/json
    application/xml application/xml+rss application/wasm
    image/svg+xml font/woff2;

`)

	// Upstreams
	b.WriteString("# ── Upstreams ──────────────────────────────────────────────────────────────\n")
	for _, c := range clients {
		fmt.Fprintf(&b, "upstream %s-backend {\n    server %s-backend:%s;\n    keepalive 32;\n}\n\n", c.Name, c.Name, c.Port)
	}

	// WebSocket upgrade map (shared — protocol-level, no routing)
	b.WriteString(`# ── WebSocket upgrade ─────────────────────────────────────────────────────
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

`)

	// Upload cache (shared zone)
	b.WriteString(`# ── Upload cache ──────────────────────────────────────────────────────────
proxy_cache_path /var/cache/nginx/uploads
                 levels=1:2 keys_zone=uploads_cache:10m
                 max_size=1g inactive=30d use_temp_path=off;

`)

	// One server block per client — no map, no default fallthrough
	for _, c := range clients {
		upstream := c.Name + "-backend"
		serverNames := strings.Join(c.Domains, " ")

		fmt.Fprintf(&b, "# ── %s ──────────────────────────────────────────────────────────────\n", c.Name)
		fmt.Fprintf(&b, "server {\n    listen 80;\n    server_name %s;\n    client_max_body_size 50M;\n\n", serverNames)
		fmt.Fprintf(&b, "    access_log /var/log/nginx/access.log routing;\n\n")

		// Security headers
		b.WriteString(`    add_header X-Frame-Options        "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy        "strict-origin-when-cross-origin" always;
    add_header Permissions-Policy     "camera=(), microphone=(), geolocation=()" always;

`)

		// Uploads (cached)
		fmt.Fprintf(&b, `    location ^~ /uploads/ {
        proxy_pass         http://%s;
        proxy_http_version 1.1;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_set_header   Connection        "";

        proxy_cache           uploads_cache;
        proxy_cache_valid     200 30d;
        proxy_cache_valid     404 1m;
        proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;
        proxy_cache_lock      on;
        add_header X-Cache-Status $upstream_cache_status;
        expires 30d;
        add_header Cache-Control "public";
        add_header X-Content-Type-Options "nosniff" always;
        access_log off;
    }

`, upstream)

		// API
		fmt.Fprintf(&b, `    location /api/ {
        proxy_pass         http://%s;
        proxy_http_version 1.1;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_set_header   Connection        "";
        proxy_buffering    on;
        proxy_buffer_size  16k;
        proxy_buffers      8 16k;
    }

`, upstream)

		// WebSocket
		fmt.Fprintf(&b, `    location = /ws {
        proxy_pass         http://%s;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade           $http_upgrade;
        proxy_set_header   Connection        $connection_upgrade;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_read_timeout 86400s;
        proxy_send_timeout 86400s;
    }

    location = /api/ws {
        proxy_pass         http://%s;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade           $http_upgrade;
        proxy_set_header   Connection        $connection_upgrade;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_read_timeout 86400s;
        proxy_send_timeout 86400s;
    }

`, upstream, upstream)

		// Health
		fmt.Fprintf(&b, `    location = /health {
        proxy_pass         http://%s;
        proxy_http_version 1.1;
        proxy_set_header   Host        $host;
        proxy_set_header   Connection  "";
    }

`, upstream)

		// Catch-all → SSR / SPA
		fmt.Fprintf(&b, `    location / {
        proxy_pass         http://%s;
        proxy_http_version 1.1;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_set_header   Connection        "";
        proxy_buffering    on;
        proxy_buffer_size  16k;
        proxy_buffers      8 16k;
    }
}

`, upstream)
	}

	// Default server — reject unmatched hosts with 444 (drop connection)
	b.WriteString(`# ── Default (unmatched hosts) ──────────────────────────────────────────────
server {
    listen 80 default_server;
    server_name _;
    return 444;
}
`)

	if err := os.WriteFile(confPath, []byte(b.String()), 0644); err != nil {
		die("Cannot write nginx config: %v", err)
	}
	log("nginx config written → %s", confPath)
}
