/**
 * Icon map - a curated set of icons available for page blocks.
 * We re-export Lucide components keyed by their string name so the
 * block renderer can look them up from the DB `icon` column.
 */
import {
  Award,
  CheckCircle,
  Coffee,
  Compass,
  Facebook,
  Flame,
  Gamepad2,
  Github,
  Globe,
  Headphones,
  Heart,
  Instagram,
  Link,
  Linkedin,
  type LucideIcon,
  MessageCircle,
  Music,
  Shield,
  ShoppingCart,
  Star,
  Swords,
  TrendingUp,
  Twitch,
  Twitter,
  Users,
  Youtube,
  Zap,
} from "lucide-react";

export const ICON_MAP: Record<string, LucideIcon> = {
  CheckCircle,
  Users,
  Star,
  Gamepad2,
  TrendingUp,
  ShoppingCart,
  MessageCircle,
  Twitter,
  Instagram,
  Github,
  Heart,
  Shield,
  Zap,
  Globe,
  Award,
  Coffee,
  Headphones,
  Compass,
  Flame,
  Swords,
  Youtube,
  Facebook,
  Twitch,
  Linkedin,
  Music,
  Link,
};

export const ICON_NAMES = Object.keys(ICON_MAP);
