package cli

type Commands struct {
	DefaultAPIPort int
	Die            func(format string, args ...any)

	New             func([]string)
	List            func()
	Enable          func(string)
	Disable         func(string)
	Start           func(string)
	Stop            func(string)
	Remove          func(string)
	Build           func()
	GlobalStart     func()
	GlobalStop      func()
	GlobalRestart   func()
	ShipFrontend    func()
	Dev             func()
	ComposeUp       func(follow bool, build bool)
	ComposeDown     func()
	NginxReload     func()
	DBInit          func(string)
	Migrate         func(name string, rebuild bool)
	MigrateAll      func(rebuild bool)
	Logs            func(name string, extra []string)
	UpdateClient    func(string)
	UpdateAll       func()
	ExportClient    func(name, outFile string)
	ImportClient    func(archivePath, newName, newPort string)
	ExportNode      func(outFile string)
	ImportNode      func(archivePath string)
	WipeAll         func()
	APIStart        func(port int)
	APIStop         func()
	APIStatus       func()
	PasscodeSet     func([]string)
	PasscodeVerify  func([]string)
	PasscodeClear   func()
	PasscodeStatus  func()
	FrappeProvision func(siteName string)
}
