package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strings"
	"unicode"

	"github.com/skaia/backend/internal/s_registry"
)

func main() {
	if err := run(os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run(args []string) error {
	flags := flag.NewFlagSet("section-contract-gen", flag.ContinueOnError)
	output := flags.String("output", "", "generated TypeScript output path")
	goOutput := flags.String("go-output", "", "generated Go output path")
	check := flags.Bool("check", false, "fail if the generated output is stale")
	if err := flags.Parse(args); err != nil {
		return err
	}
	if *output == "" || *goOutput == "" {
		return errors.New("-output and -go-output are required")
	}

	typeScript, err := generateTypeScript()
	if err != nil {
		return err
	}
	goSource, err := generateGo()
	if err != nil {
		return err
	}
	if *check {
		for path, expected := range map[string][]byte{*output: typeScript, *goOutput: goSource} {
			current, err := os.ReadFile(path)
			if err != nil {
				return fmt.Errorf("read generated contract file %s: %w", path, err)
			}
			if !bytes.Equal(current, expected) {
				return fmt.Errorf("generated section contracts are stale; run go generate ./internal/s_registry")
			}
		}
		return nil
	}
	if err := os.WriteFile(*output, typeScript, 0o644); err != nil {
		return fmt.Errorf("write generated contract file: %w", err)
	}
	if err := os.WriteFile(*goOutput, goSource, 0o644); err != nil {
		return fmt.Errorf("write generated Go contract file: %w", err)
	}
	return nil
}

func definitionsInOrder() ([]string, map[string]s_registry.Definition, error) {
	sectionTypes := s_registry.SectionTypes()
	definitions := make(map[string]s_registry.Definition, len(sectionTypes))
	for _, sectionType := range sectionTypes {
		definition, ok := s_registry.Get(sectionType)
		if !ok {
			return nil, nil, fmt.Errorf("registry lost section type %q", sectionType)
		}
		definitions[sectionType] = definition
	}
	return sectionTypes, definitions, nil
}

func generateTypeScript() ([]byte, error) {
	sectionTypes, definitions, err := definitionsInOrder()
	if err != nil {
		return nil, err
	}

	var out strings.Builder
	out.WriteString("// Code generated by backend/cmd/section-contract-gen; DO NOT EDIT.\n\n")
	out.WriteString("export const SECTION_TYPES = [\n")
	for _, sectionType := range sectionTypes {
		fmt.Fprintf(&out, "  %q,\n", sectionType)
	}
	out.WriteString("] as const;\n\n")
	out.WriteString("export type SectionType = (typeof SECTION_TYPES)[number];\n\n")

	shellSchema := s_registry.ContractSchemas()[s_registry.SharedSectionShellV1]
	var shellRoot map[string]any
	if err := json.Unmarshal(shellSchema, &shellRoot); err != nil {
		return nil, fmt.Errorf("decode shared shell schema: %w", err)
	}
	out.WriteString("export type SharedSectionShell = ")
	out.WriteString(renderType(shellRoot, shellRoot, 0))
	out.WriteString(";\n\n")
	shellDefault, err := json.Marshal(shellRoot["default"])
	if err != nil {
		return nil, fmt.Errorf("encode shared shell default: %w", err)
	}
	formattedShellDefault, err := formatJSON(shellDefault, 0)
	if err != nil {
		return nil, fmt.Errorf("format shared shell default: %w", err)
	}
	out.WriteString("export const DEFAULT_SECTION_SHELL = ")
	out.WriteString(formattedShellDefault)
	out.WriteString(" satisfies SharedSectionShell;\n\n")

	for _, sectionType := range sectionTypes {
		definition := definitions[sectionType]
		var root map[string]any
		if err := json.Unmarshal(definition.ConfigSchema, &root); err != nil {
			return nil, fmt.Errorf("decode %s schema: %w", sectionType, err)
		}
		typeName := exportedName(sectionType) + "Config"
		fmt.Fprintf(&out, "export type %s = %s;\n\n", typeName, renderType(root, root, 0))
	}

	out.WriteString("export interface SectionConfigByType {\n")
	for _, sectionType := range sectionTypes {
		fmt.Fprintf(&out, "  %q: %sConfig;\n", sectionType, exportedName(sectionType))
	}
	out.WriteString("}\n\n")
	out.WriteString("export type SectionConfig<T extends SectionType> = SectionConfigByType[T];\n\n")

	out.WriteString("export const SECTION_CONFIG_VERSIONS = {\n")
	for _, sectionType := range sectionTypes {
		fmt.Fprintf(&out, "  %q: %d,\n", sectionType, definitions[sectionType].ConfigVersion)
	}
	out.WriteString("} as const satisfies Record<SectionType, number>;\n\n")

	out.WriteString("export const SECTION_CONFIG_KEYS = {\n")
	for _, sectionType := range sectionTypes {
		var root map[string]any
		if err := json.Unmarshal(definitions[sectionType].ConfigSchema, &root); err != nil {
			return nil, err
		}
		properties, _ := root["properties"].(map[string]any)
		keys := make([]string, 0, len(properties))
		for key := range properties {
			keys = append(keys, key)
		}
		sort.Strings(keys)
		encoded, err := json.Marshal(keys)
		if err != nil {
			return nil, err
		}
		fmt.Fprintf(&out, "  %q: %s,\n", sectionType, encoded)
	}
	out.WriteString("} as const satisfies Record<SectionType, readonly string[]>;\n\n")

	out.WriteString("export const SECTION_DEFAULT_CONFIGS = {\n")
	for _, sectionType := range sectionTypes {
		formatted, err := formatJSON(definitions[sectionType].DefaultConfig, 2)
		if err != nil {
			return nil, fmt.Errorf("format %s default: %w", sectionType, err)
		}
		fmt.Fprintf(&out, "  %q: %s,\n", sectionType, formatted)
	}
	out.WriteString("} satisfies { [T in SectionType]: SectionConfigByType[T] };\n\n")

	out.WriteString("export const SECTION_CAPABILITIES = {\n")
	for _, sectionType := range sectionTypes {
		capabilities, err := json.Marshal(definitions[sectionType].Capabilities)
		if err != nil {
			return nil, err
		}
		fmt.Fprintf(&out, "  %q: %s,\n", sectionType, capabilities)
	}
	out.WriteString("} as const satisfies Record<SectionType, readonly string[]>;\n")
	return []byte(out.String()), nil
}

func generateGo() ([]byte, error) {
	sectionTypes, definitions, err := definitionsInOrder()
	if err != nil {
		return nil, err
	}
	var out strings.Builder
	out.WriteString("// Code generated by backend/cmd/section-contract-gen; DO NOT EDIT.\n\n")
	out.WriteString("package s_registry\n\n")
	out.WriteString("// NormalizedSectionType is a canonical page-section discriminator.\n")
	out.WriteString("type NormalizedSectionType string\n\n")
	out.WriteString("const (\n")
	for _, sectionType := range sectionTypes {
		fmt.Fprintf(&out, "\tSectionType%s NormalizedSectionType = %q\n", goExportedName(sectionType), sectionType)
	}
	out.WriteString(")\n\n")
	out.WriteString("// NormalizedSectionConfig is implemented by every generated config DTO.\n")
	out.WriteString("type NormalizedSectionConfig interface { isNormalizedSectionConfig() }\n\n")

	for _, sectionType := range sectionTypes {
		definition := definitions[sectionType]
		var root map[string]any
		if err := json.Unmarshal(definition.ConfigSchema, &root); err != nil {
			return nil, fmt.Errorf("decode %s schema: %w", sectionType, err)
		}
		typeName := goExportedName(sectionType) + "Config"
		fmt.Fprintf(&out, "type %s %s\n\n", typeName, renderGoType(root, root, 0))
		fmt.Fprintf(&out, "func (*%s) isNormalizedSectionConfig() {}\n\n", typeName)
	}

	out.WriteString("var normalizedSectionConfigFactories = map[NormalizedSectionType]func() NormalizedSectionConfig{\n")
	for _, sectionType := range sectionTypes {
		fmt.Fprintf(&out, "\tSectionType%s: func() NormalizedSectionConfig { return &%sConfig{} },\n", goExportedName(sectionType), goExportedName(sectionType))
	}
	out.WriteString("}\n\n")
	out.WriteString("// ParseNormalizedSectionType rejects unknown discriminators.\n")
	out.WriteString("func ParseNormalizedSectionType(value string) (NormalizedSectionType, bool) {\n")
	out.WriteString("\tsectionType := NormalizedSectionType(value)\n")
	out.WriteString("\t_, ok := normalizedSectionConfigFactories[sectionType]\n")
	out.WriteString("\treturn sectionType, ok\n")
	out.WriteString("}\n")

	formatted, err := format.Source([]byte(out.String()))
	if err != nil {
		return nil, fmt.Errorf("format generated Go contracts: %w", err)
	}
	return formatted, nil
}

func renderType(schema, root map[string]any, depth int) string {
	if ref, _ := schema["$ref"].(string); strings.HasPrefix(ref, "#/$defs/") {
		name := strings.TrimPrefix(ref, "#/$defs/")
		defs, _ := root["$defs"].(map[string]any)
		if target, ok := defs[name].(map[string]any); ok {
			return renderType(target, root, depth)
		}
		return "unknown"
	}
	for _, keyword := range []string{"oneOf", "anyOf"} {
		if choices, ok := schema[keyword].([]any); ok {
			parts := make([]string, 0, len(choices))
			for _, choice := range choices {
				if child, ok := choice.(map[string]any); ok {
					parts = append(parts, renderType(child, root, depth))
				}
			}
			if len(parts) > 0 {
				return strings.Join(parts, " | ")
			}
		}
	}
	if value, exists := schema["const"]; exists {
		return literal(value)
	}
	if values, ok := schema["enum"].([]any); ok {
		parts := make([]string, len(values))
		for i, value := range values {
			parts[i] = literal(value)
		}
		return strings.Join(parts, " | ")
	}

	switch typ := schema["type"].(type) {
	case []any:
		parts := make([]string, len(typ))
		for i, value := range typ {
			parts[i] = renderPrimitive(fmt.Sprint(value), schema, root, depth)
		}
		return strings.Join(parts, " | ")
	case string:
		return renderPrimitive(typ, schema, root, depth)
	default:
		if _, ok := schema["properties"]; ok {
			return renderObject(schema, root, depth)
		}
		return "unknown"
	}
}

func renderPrimitive(typ string, schema, root map[string]any, depth int) string {
	switch typ {
	case "string":
		return "string"
	case "number", "integer":
		return "number"
	case "boolean":
		return "boolean"
	case "null":
		return "null"
	case "array":
		item, _ := schema["items"].(map[string]any)
		if item == nil {
			return "unknown[]"
		}
		return "Array<" + renderType(item, root, depth) + ">"
	case "object":
		return renderObject(schema, root, depth)
	default:
		return "unknown"
	}
}

func renderObject(schema, root map[string]any, depth int) string {
	properties, _ := schema["properties"].(map[string]any)
	if len(properties) == 0 {
		switch additional := schema["additionalProperties"].(type) {
		case bool:
			if !additional {
				return "Record<string, never>"
			}
		case map[string]any:
			return "Record<string, " + renderType(additional, root, depth) + ">"
		}
		return "Record<string, unknown>"
	}
	required := map[string]bool{}
	if fields, ok := schema["required"].([]any); ok {
		for _, field := range fields {
			required[fmt.Sprint(field)] = true
		}
	}
	keys := make([]string, 0, len(properties))
	for key := range properties {
		keys = append(keys, key)
	}
	sort.Strings(keys)

	indent := strings.Repeat("  ", depth)
	childIndent := strings.Repeat("  ", depth+1)
	var out strings.Builder
	out.WriteString("{\n")
	for _, key := range keys {
		child, _ := properties[key].(map[string]any)
		optional := "?"
		if required[key] {
			optional = ""
		}
		rendered := strings.ReplaceAll(renderType(child, root, depth+1), "\n", "\n"+childIndent)
		fmt.Fprintf(&out, "%s%q%s: %s;\n", childIndent, key, optional, rendered)
	}
	out.WriteString(indent + "}")
	return out.String()
}

func exportedName(value string) string {
	var out strings.Builder
	upperNext := true
	for _, r := range value {
		if r == '_' || r == '-' {
			upperNext = true
			continue
		}
		if upperNext {
			r = unicode.ToUpper(r)
			upperNext = false
		}
		out.WriteRune(r)
	}
	return out.String()
}

func renderGoType(schema, root map[string]any, depth int) string {
	if ref, _ := schema["$ref"].(string); strings.HasPrefix(ref, "#/$defs/") {
		name := strings.TrimPrefix(ref, "#/$defs/")
		defs, _ := root["$defs"].(map[string]any)
		if target, ok := defs[name].(map[string]any); ok {
			return renderGoType(target, root, depth)
		}
		return "any"
	}
	if value, exists := schema["const"]; exists {
		switch value.(type) {
		case string:
			return "string"
		case float64:
			return "int64"
		case bool:
			return "bool"
		default:
			return "any"
		}
	}
	if values, ok := schema["enum"].([]any); ok && len(values) > 0 {
		switch values[0].(type) {
		case string:
			return "string"
		case float64:
			return "float64"
		default:
			return "any"
		}
	}
	switch typ := schema["type"].(type) {
	case []any:
		return "any"
	case string:
		switch typ {
		case "string":
			return "string"
		case "number":
			return "float64"
		case "integer":
			return "int64"
		case "boolean":
			return "bool"
		case "array":
			item, _ := schema["items"].(map[string]any)
			if item == nil {
				return "[]any"
			}
			return "[]" + renderGoType(item, root, depth)
		case "object":
			return renderGoObject(schema, root, depth)
		default:
			return "any"
		}
	default:
		if _, ok := schema["properties"]; ok {
			return renderGoObject(schema, root, depth)
		}
		return "any"
	}
}

func renderGoObject(schema, root map[string]any, depth int) string {
	properties, _ := schema["properties"].(map[string]any)
	if len(properties) == 0 {
		switch additional := schema["additionalProperties"].(type) {
		case bool:
			if !additional {
				return "struct{}"
			}
		case map[string]any:
			return "map[string]" + renderGoType(additional, root, depth)
		}
		return "map[string]any"
	}
	required := map[string]bool{}
	if fields, ok := schema["required"].([]any); ok {
		for _, field := range fields {
			required[fmt.Sprint(field)] = true
		}
	}
	keys := make([]string, 0, len(properties))
	for key := range properties {
		keys = append(keys, key)
	}
	sort.Strings(keys)

	indent := strings.Repeat("\t", depth)
	childIndent := strings.Repeat("\t", depth+1)
	var out strings.Builder
	out.WriteString("struct {\n")
	for _, key := range keys {
		child, _ := properties[key].(map[string]any)
		fieldType := renderGoType(child, root, depth+1)
		if !required[key] && !goTypeIsNilable(fieldType) {
			fieldType = "*" + fieldType
		}
		fieldType = strings.ReplaceAll(fieldType, "\n", "\n"+childIndent)
		tag := key
		if !required[key] {
			tag += ",omitempty"
		}
		fmt.Fprintf(&out, "%s%s %s `json:%q`\n", childIndent, goExportedName(key), fieldType, tag)
	}
	out.WriteString(indent + "}")
	return out.String()
}

func goTypeIsNilable(typ string) bool {
	return strings.HasPrefix(typ, "[]") || strings.HasPrefix(typ, "map[") || typ == "any"
}

func goExportedName(value string) string {
	parts := strings.FieldsFunc(value, func(r rune) bool { return r == '_' || r == '-' })
	var out strings.Builder
	for _, part := range parts {
		switch strings.ToLower(part) {
		case "id":
			out.WriteString("ID")
		case "url":
			out.WriteString("URL")
		case "css":
			out.WriteString("CSS")
		case "qa":
			out.WriteString("QA")
		case "cta":
			out.WriteString("CTA")
		default:
			runes := []rune(part)
			if len(runes) > 0 {
				runes[0] = unicode.ToUpper(runes[0])
			}
			out.WriteString(string(runes))
		}
	}
	return out.String()
}

func literal(value any) string {
	raw, err := json.Marshal(value)
	if err != nil {
		return "unknown"
	}
	return string(raw)
}

func formatJSON(raw json.RawMessage, continuationIndent int) (string, error) {
	var formatted bytes.Buffer
	if err := json.Indent(&formatted, raw, "", "  "); err != nil {
		return "", err
	}
	indent := strings.Repeat(" ", continuationIndent)
	return strings.ReplaceAll(formatted.String(), "\n", "\n"+indent), nil
}
