// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: grengo.proto

package grengo

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GrengoService_ListSites_FullMethodName       = "/grengo.grpc.GrengoService/ListSites"
	GrengoService_Exec_FullMethodName            = "/grengo.grpc.GrengoService/Exec"
	GrengoService_CreateSite_FullMethodName      = "/grengo.grpc.GrengoService/CreateSite"
	GrengoService_ProvisionFrappe_FullMethodName = "/grengo.grpc.GrengoService/ProvisionFrappe"
	GrengoService_DeleteSite_FullMethodName      = "/grengo.grpc.GrengoService/DeleteSite"
	GrengoService_StartSite_FullMethodName       = "/grengo.grpc.GrengoService/StartSite"
	GrengoService_StopSite_FullMethodName        = "/grengo.grpc.GrengoService/StopSite"
	GrengoService_EnableSite_FullMethodName      = "/grengo.grpc.GrengoService/EnableSite"
	GrengoService_DisableSite_FullMethodName     = "/grengo.grpc.GrengoService/DisableSite"
	GrengoService_ArmSite_FullMethodName         = "/grengo.grpc.GrengoService/ArmSite"
	GrengoService_DisarmSite_FullMethodName      = "/grengo.grpc.GrengoService/DisarmSite"
	GrengoService_GetSiteEnv_FullMethodName      = "/grengo.grpc.GrengoService/GetSiteEnv"
	GrengoService_UpdateSiteEnv_FullMethodName   = "/grengo.grpc.GrengoService/UpdateSiteEnv"
	GrengoService_Stats_FullMethodName           = "/grengo.grpc.GrengoService/Stats"
	GrengoService_Storage_FullMethodName         = "/grengo.grpc.GrengoService/Storage"
	GrengoService_GetSysInfo_FullMethodName      = "/grengo.grpc.GrengoService/GetSysInfo"
	GrengoService_GetHardware_FullMethodName     = "/grengo.grpc.GrengoService/GetHardware"
	GrengoService_ExportSite_FullMethodName      = "/grengo.grpc.GrengoService/ExportSite"
	GrengoService_ImportSite_FullMethodName      = "/grengo.grpc.GrengoService/ImportSite"
	GrengoService_MigrateSite_FullMethodName     = "/grengo.grpc.GrengoService/MigrateSite"
	GrengoService_MigrateAll_FullMethodName      = "/grengo.grpc.GrengoService/MigrateAll"
	GrengoService_ExportNode_FullMethodName      = "/grengo.grpc.GrengoService/ExportNode"
	GrengoService_ImportNode_FullMethodName      = "/grengo.grpc.GrengoService/ImportNode"
	GrengoService_ListExports_FullMethodName     = "/grengo.grpc.GrengoService/ListExports"
	GrengoService_DownloadExport_FullMethodName  = "/grengo.grpc.GrengoService/DownloadExport"
	GrengoService_DeleteExport_FullMethodName    = "/grengo.grpc.GrengoService/DeleteExport"
	GrengoService_ListJobs_FullMethodName        = "/grengo.grpc.GrengoService/ListJobs"
	GrengoService_GetJob_FullMethodName          = "/grengo.grpc.GrengoService/GetJob"
	GrengoService_DownloadJob_FullMethodName     = "/grengo.grpc.GrengoService/DownloadJob"
	GrengoService_WatchJobs_FullMethodName       = "/grengo.grpc.GrengoService/WatchJobs"
	GrengoService_SendAction_FullMethodName      = "/grengo.grpc.GrengoService/SendAction"
	GrengoService_PasscodeStatus_FullMethodName  = "/grengo.grpc.GrengoService/PasscodeStatus"
	GrengoService_VerifyPasscode_FullMethodName  = "/grengo.grpc.GrengoService/VerifyPasscode"
)

// GrengoServiceClient is the client API for GrengoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GrengoServiceClient interface {
	// Sites
	ListSites(ctx context.Context, in *ListSitesRequest, opts ...grpc.CallOption) (*ListSitesResponse, error)
	Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (*ExecResponse, error)
	CreateSite(ctx context.Context, in *CreateSiteRequest, opts ...grpc.CallOption) (*CreateSiteResponse, error)
	ProvisionFrappe(ctx context.Context, in *ProvisionFrappeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogStreamResponse], error)
	DeleteSite(ctx context.Context, in *SiteRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	StartSite(ctx context.Context, in *SiteRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	StopSite(ctx context.Context, in *SiteRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	EnableSite(ctx context.Context, in *SiteRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	DisableSite(ctx context.Context, in *SiteRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	ArmSite(ctx context.Context, in *SiteRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	DisarmSite(ctx context.Context, in *SiteRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	// Environment
	GetSiteEnv(ctx context.Context, in *SiteRequest, opts ...grpc.CallOption) (*GetSiteEnvResponse, error)
	UpdateSiteEnv(ctx context.Context, in *UpdateSiteEnvRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	// Metrics & SysInfo
	Stats(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*StatsResponse, error)
	Storage(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*StorageResponse, error)
	GetSysInfo(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*SysInfoResponse, error)
	GetHardware(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*HardwareResponse, error)
	// Archives & Migrations
	ExportSite(ctx context.Context, in *SiteRequest, opts ...grpc.CallOption) (*ExportSiteResponse, error)
	ImportSite(ctx context.Context, in *ImportSiteRequest, opts ...grpc.CallOption) (*ImportSiteResponse, error)
	MigrateSite(ctx context.Context, in *MigrateSiteRequest, opts ...grpc.CallOption) (*MigrateSiteResponse, error)
	MigrateAll(ctx context.Context, in *MigrateAllRequest, opts ...grpc.CallOption) (*MigrateAllResponse, error)
	ExportNode(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*ExportNodeResponse, error)
	ImportNode(ctx context.Context, in *ImportNodeRequest, opts ...grpc.CallOption) (*ImportNodeResponse, error)
	ListExports(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*ListExportsResponse, error)
	DownloadExport(ctx context.Context, in *DownloadExportRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FileChunk], error)
	DeleteExport(ctx context.Context, in *DeleteExportRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	// Jobs
	ListJobs(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*ListJobsResponse, error)
	GetJob(ctx context.Context, in *GetJobRequest, opts ...grpc.CallOption) (*GetJobResponse, error)
	DownloadJob(ctx context.Context, in *DownloadJobRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FileChunk], error)
	WatchJobs(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JobEvent], error)
	// WS proxy replacement
	SendAction(ctx context.Context, in *SendActionRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	// Auth
	PasscodeStatus(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*PasscodeStatusResponse, error)
	VerifyPasscode(ctx context.Context, in *VerifyPasscodeRequest, opts ...grpc.CallOption) (*VerifyPasscodeResponse, error)
}

type grengoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGrengoServiceClient(cc grpc.ClientConnInterface) GrengoServiceClient {
	return &grengoServiceClient{cc}
}

func (c *grengoServiceClient) ListSites(ctx context.Context, in *ListSitesRequest, opts ...grpc.CallOption) (*ListSitesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSitesResponse)
	err := c.cc.Invoke(ctx, GrengoService_ListSites_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grengoServiceClient) Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (*ExecResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecResponse)
	err := c.cc.Invoke(ctx, GrengoService_Exec_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grengoServiceClient) CreateSite(ctx context.Context, in *CreateSiteRequest, opts ...grpc.CallOption) (*CreateSiteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSiteResponse)
	err := c.cc.Invoke(ctx, GrengoService_CreateSite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grengoServiceClient) ProvisionFrappe(ctx context.Context, in *ProvisionFrappeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GrengoService_ServiceDesc.Streams[0], GrengoService_ProvisionFrappe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ProvisionFrappeRequest, LogStreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GrengoService_ProvisionFrappeClient = grpc.ServerStreamingClient[LogStreamResponse]

func (c *grengoServiceClient) DeleteSite(ctx context.Context, in *SiteRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, GrengoService_DeleteSite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grengoServiceClient) StartSite(ctx context.Context, in *SiteRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, GrengoService_StartSite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grengoServiceClient) StopSite(ctx context.Context, in *SiteRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, GrengoService_StopSite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grengoServiceClient) EnableSite(ctx context.Context, in *SiteRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, GrengoService_EnableSite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grengoServiceClient) DisableSite(ctx context.Context, in *SiteRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, GrengoService_DisableSite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grengoServiceClient) ArmSite(ctx context.Context, in *SiteRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, GrengoService_ArmSite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grengoServiceClient) DisarmSite(ctx context.Context, in *SiteRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, GrengoService_DisarmSite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grengoServiceClient) GetSiteEnv(ctx context.Context, in *SiteRequest, opts ...grpc.CallOption) (*GetSiteEnvResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSiteEnvResponse)
	err := c.cc.Invoke(ctx, GrengoService_GetSiteEnv_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grengoServiceClient) UpdateSiteEnv(ctx context.Context, in *UpdateSiteEnvRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, GrengoService_UpdateSiteEnv_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grengoServiceClient) Stats(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*StatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatsResponse)
	err := c.cc.Invoke(ctx, GrengoService_Stats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grengoServiceClient) Storage(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*StorageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StorageResponse)
	err := c.cc.Invoke(ctx, GrengoService_Storage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grengoServiceClient) GetSysInfo(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*SysInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SysInfoResponse)
	err := c.cc.Invoke(ctx, GrengoService_GetSysInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grengoServiceClient) GetHardware(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*HardwareResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HardwareResponse)
	err := c.cc.Invoke(ctx, GrengoService_GetHardware_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grengoServiceClient) ExportSite(ctx context.Context, in *SiteRequest, opts ...grpc.CallOption) (*ExportSiteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportSiteResponse)
	err := c.cc.Invoke(ctx, GrengoService_ExportSite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grengoServiceClient) ImportSite(ctx context.Context, in *ImportSiteRequest, opts ...grpc.CallOption) (*ImportSiteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImportSiteResponse)
	err := c.cc.Invoke(ctx, GrengoService_ImportSite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grengoServiceClient) MigrateSite(ctx context.Context, in *MigrateSiteRequest, opts ...grpc.CallOption) (*MigrateSiteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MigrateSiteResponse)
	err := c.cc.Invoke(ctx, GrengoService_MigrateSite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grengoServiceClient) MigrateAll(ctx context.Context, in *MigrateAllRequest, opts ...grpc.CallOption) (*MigrateAllResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MigrateAllResponse)
	err := c.cc.Invoke(ctx, GrengoService_MigrateAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grengoServiceClient) ExportNode(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*ExportNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportNodeResponse)
	err := c.cc.Invoke(ctx, GrengoService_ExportNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grengoServiceClient) ImportNode(ctx context.Context, in *ImportNodeRequest, opts ...grpc.CallOption) (*ImportNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImportNodeResponse)
	err := c.cc.Invoke(ctx, GrengoService_ImportNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grengoServiceClient) ListExports(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*ListExportsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListExportsResponse)
	err := c.cc.Invoke(ctx, GrengoService_ListExports_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grengoServiceClient) DownloadExport(ctx context.Context, in *DownloadExportRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FileChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GrengoService_ServiceDesc.Streams[1], GrengoService_DownloadExport_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DownloadExportRequest, FileChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GrengoService_DownloadExportClient = grpc.ServerStreamingClient[FileChunk]

func (c *grengoServiceClient) DeleteExport(ctx context.Context, in *DeleteExportRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, GrengoService_DeleteExport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grengoServiceClient) ListJobs(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*ListJobsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListJobsResponse)
	err := c.cc.Invoke(ctx, GrengoService_ListJobs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grengoServiceClient) GetJob(ctx context.Context, in *GetJobRequest, opts ...grpc.CallOption) (*GetJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetJobResponse)
	err := c.cc.Invoke(ctx, GrengoService_GetJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grengoServiceClient) DownloadJob(ctx context.Context, in *DownloadJobRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FileChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GrengoService_ServiceDesc.Streams[2], GrengoService_DownloadJob_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DownloadJobRequest, FileChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GrengoService_DownloadJobClient = grpc.ServerStreamingClient[FileChunk]

func (c *grengoServiceClient) WatchJobs(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JobEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GrengoService_ServiceDesc.Streams[3], GrengoService_WatchJobs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EmptyRequest, JobEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GrengoService_WatchJobsClient = grpc.ServerStreamingClient[JobEvent]

func (c *grengoServiceClient) SendAction(ctx context.Context, in *SendActionRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, GrengoService_SendAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grengoServiceClient) PasscodeStatus(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*PasscodeStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PasscodeStatusResponse)
	err := c.cc.Invoke(ctx, GrengoService_PasscodeStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grengoServiceClient) VerifyPasscode(ctx context.Context, in *VerifyPasscodeRequest, opts ...grpc.CallOption) (*VerifyPasscodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyPasscodeResponse)
	err := c.cc.Invoke(ctx, GrengoService_VerifyPasscode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GrengoServiceServer is the server API for GrengoService service.
// All implementations must embed UnimplementedGrengoServiceServer
// for forward compatibility.
type GrengoServiceServer interface {
	// Sites
	ListSites(context.Context, *ListSitesRequest) (*ListSitesResponse, error)
	Exec(context.Context, *ExecRequest) (*ExecResponse, error)
	CreateSite(context.Context, *CreateSiteRequest) (*CreateSiteResponse, error)
	ProvisionFrappe(*ProvisionFrappeRequest, grpc.ServerStreamingServer[LogStreamResponse]) error
	DeleteSite(context.Context, *SiteRequest) (*EmptyResponse, error)
	StartSite(context.Context, *SiteRequest) (*EmptyResponse, error)
	StopSite(context.Context, *SiteRequest) (*EmptyResponse, error)
	EnableSite(context.Context, *SiteRequest) (*EmptyResponse, error)
	DisableSite(context.Context, *SiteRequest) (*EmptyResponse, error)
	ArmSite(context.Context, *SiteRequest) (*EmptyResponse, error)
	DisarmSite(context.Context, *SiteRequest) (*EmptyResponse, error)
	// Environment
	GetSiteEnv(context.Context, *SiteRequest) (*GetSiteEnvResponse, error)
	UpdateSiteEnv(context.Context, *UpdateSiteEnvRequest) (*EmptyResponse, error)
	// Metrics & SysInfo
	Stats(context.Context, *EmptyRequest) (*StatsResponse, error)
	Storage(context.Context, *EmptyRequest) (*StorageResponse, error)
	GetSysInfo(context.Context, *EmptyRequest) (*SysInfoResponse, error)
	GetHardware(context.Context, *EmptyRequest) (*HardwareResponse, error)
	// Archives & Migrations
	ExportSite(context.Context, *SiteRequest) (*ExportSiteResponse, error)
	ImportSite(context.Context, *ImportSiteRequest) (*ImportSiteResponse, error)
	MigrateSite(context.Context, *MigrateSiteRequest) (*MigrateSiteResponse, error)
	MigrateAll(context.Context, *MigrateAllRequest) (*MigrateAllResponse, error)
	ExportNode(context.Context, *EmptyRequest) (*ExportNodeResponse, error)
	ImportNode(context.Context, *ImportNodeRequest) (*ImportNodeResponse, error)
	ListExports(context.Context, *EmptyRequest) (*ListExportsResponse, error)
	DownloadExport(*DownloadExportRequest, grpc.ServerStreamingServer[FileChunk]) error
	DeleteExport(context.Context, *DeleteExportRequest) (*EmptyResponse, error)
	// Jobs
	ListJobs(context.Context, *EmptyRequest) (*ListJobsResponse, error)
	GetJob(context.Context, *GetJobRequest) (*GetJobResponse, error)
	DownloadJob(*DownloadJobRequest, grpc.ServerStreamingServer[FileChunk]) error
	WatchJobs(*EmptyRequest, grpc.ServerStreamingServer[JobEvent]) error
	// WS proxy replacement
	SendAction(context.Context, *SendActionRequest) (*EmptyResponse, error)
	// Auth
	PasscodeStatus(context.Context, *EmptyRequest) (*PasscodeStatusResponse, error)
	VerifyPasscode(context.Context, *VerifyPasscodeRequest) (*VerifyPasscodeResponse, error)
	mustEmbedUnimplementedGrengoServiceServer()
}

// UnimplementedGrengoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGrengoServiceServer struct{}

func (UnimplementedGrengoServiceServer) ListSites(context.Context, *ListSitesRequest) (*ListSitesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSites not implemented")
}
func (UnimplementedGrengoServiceServer) Exec(context.Context, *ExecRequest) (*ExecResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Exec not implemented")
}
func (UnimplementedGrengoServiceServer) CreateSite(context.Context, *CreateSiteRequest) (*CreateSiteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSite not implemented")
}
func (UnimplementedGrengoServiceServer) ProvisionFrappe(*ProvisionFrappeRequest, grpc.ServerStreamingServer[LogStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method ProvisionFrappe not implemented")
}
func (UnimplementedGrengoServiceServer) DeleteSite(context.Context, *SiteRequest) (*EmptyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSite not implemented")
}
func (UnimplementedGrengoServiceServer) StartSite(context.Context, *SiteRequest) (*EmptyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartSite not implemented")
}
func (UnimplementedGrengoServiceServer) StopSite(context.Context, *SiteRequest) (*EmptyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopSite not implemented")
}
func (UnimplementedGrengoServiceServer) EnableSite(context.Context, *SiteRequest) (*EmptyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnableSite not implemented")
}
func (UnimplementedGrengoServiceServer) DisableSite(context.Context, *SiteRequest) (*EmptyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DisableSite not implemented")
}
func (UnimplementedGrengoServiceServer) ArmSite(context.Context, *SiteRequest) (*EmptyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ArmSite not implemented")
}
func (UnimplementedGrengoServiceServer) DisarmSite(context.Context, *SiteRequest) (*EmptyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DisarmSite not implemented")
}
func (UnimplementedGrengoServiceServer) GetSiteEnv(context.Context, *SiteRequest) (*GetSiteEnvResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSiteEnv not implemented")
}
func (UnimplementedGrengoServiceServer) UpdateSiteEnv(context.Context, *UpdateSiteEnvRequest) (*EmptyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSiteEnv not implemented")
}
func (UnimplementedGrengoServiceServer) Stats(context.Context, *EmptyRequest) (*StatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Stats not implemented")
}
func (UnimplementedGrengoServiceServer) Storage(context.Context, *EmptyRequest) (*StorageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Storage not implemented")
}
func (UnimplementedGrengoServiceServer) GetSysInfo(context.Context, *EmptyRequest) (*SysInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSysInfo not implemented")
}
func (UnimplementedGrengoServiceServer) GetHardware(context.Context, *EmptyRequest) (*HardwareResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHardware not implemented")
}
func (UnimplementedGrengoServiceServer) ExportSite(context.Context, *SiteRequest) (*ExportSiteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExportSite not implemented")
}
func (UnimplementedGrengoServiceServer) ImportSite(context.Context, *ImportSiteRequest) (*ImportSiteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ImportSite not implemented")
}
func (UnimplementedGrengoServiceServer) MigrateSite(context.Context, *MigrateSiteRequest) (*MigrateSiteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MigrateSite not implemented")
}
func (UnimplementedGrengoServiceServer) MigrateAll(context.Context, *MigrateAllRequest) (*MigrateAllResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MigrateAll not implemented")
}
func (UnimplementedGrengoServiceServer) ExportNode(context.Context, *EmptyRequest) (*ExportNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExportNode not implemented")
}
func (UnimplementedGrengoServiceServer) ImportNode(context.Context, *ImportNodeRequest) (*ImportNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ImportNode not implemented")
}
func (UnimplementedGrengoServiceServer) ListExports(context.Context, *EmptyRequest) (*ListExportsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListExports not implemented")
}
func (UnimplementedGrengoServiceServer) DownloadExport(*DownloadExportRequest, grpc.ServerStreamingServer[FileChunk]) error {
	return status.Error(codes.Unimplemented, "method DownloadExport not implemented")
}
func (UnimplementedGrengoServiceServer) DeleteExport(context.Context, *DeleteExportRequest) (*EmptyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteExport not implemented")
}
func (UnimplementedGrengoServiceServer) ListJobs(context.Context, *EmptyRequest) (*ListJobsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListJobs not implemented")
}
func (UnimplementedGrengoServiceServer) GetJob(context.Context, *GetJobRequest) (*GetJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetJob not implemented")
}
func (UnimplementedGrengoServiceServer) DownloadJob(*DownloadJobRequest, grpc.ServerStreamingServer[FileChunk]) error {
	return status.Error(codes.Unimplemented, "method DownloadJob not implemented")
}
func (UnimplementedGrengoServiceServer) WatchJobs(*EmptyRequest, grpc.ServerStreamingServer[JobEvent]) error {
	return status.Error(codes.Unimplemented, "method WatchJobs not implemented")
}
func (UnimplementedGrengoServiceServer) SendAction(context.Context, *SendActionRequest) (*EmptyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendAction not implemented")
}
func (UnimplementedGrengoServiceServer) PasscodeStatus(context.Context, *EmptyRequest) (*PasscodeStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PasscodeStatus not implemented")
}
func (UnimplementedGrengoServiceServer) VerifyPasscode(context.Context, *VerifyPasscodeRequest) (*VerifyPasscodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyPasscode not implemented")
}
func (UnimplementedGrengoServiceServer) mustEmbedUnimplementedGrengoServiceServer() {}
func (UnimplementedGrengoServiceServer) testEmbeddedByValue()                       {}

// UnsafeGrengoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GrengoServiceServer will
// result in compilation errors.
type UnsafeGrengoServiceServer interface {
	mustEmbedUnimplementedGrengoServiceServer()
}

func RegisterGrengoServiceServer(s grpc.ServiceRegistrar, srv GrengoServiceServer) {
	// If the following call panics, it indicates UnimplementedGrengoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GrengoService_ServiceDesc, srv)
}

func _GrengoService_ListSites_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSitesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrengoServiceServer).ListSites(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrengoService_ListSites_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrengoServiceServer).ListSites(ctx, req.(*ListSitesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrengoService_Exec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrengoServiceServer).Exec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrengoService_Exec_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrengoServiceServer).Exec(ctx, req.(*ExecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrengoService_CreateSite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSiteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrengoServiceServer).CreateSite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrengoService_CreateSite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrengoServiceServer).CreateSite(ctx, req.(*CreateSiteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrengoService_ProvisionFrappe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ProvisionFrappeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GrengoServiceServer).ProvisionFrappe(m, &grpc.GenericServerStream[ProvisionFrappeRequest, LogStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GrengoService_ProvisionFrappeServer = grpc.ServerStreamingServer[LogStreamResponse]

func _GrengoService_DeleteSite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SiteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrengoServiceServer).DeleteSite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrengoService_DeleteSite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrengoServiceServer).DeleteSite(ctx, req.(*SiteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrengoService_StartSite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SiteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrengoServiceServer).StartSite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrengoService_StartSite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrengoServiceServer).StartSite(ctx, req.(*SiteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrengoService_StopSite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SiteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrengoServiceServer).StopSite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrengoService_StopSite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrengoServiceServer).StopSite(ctx, req.(*SiteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrengoService_EnableSite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SiteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrengoServiceServer).EnableSite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrengoService_EnableSite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrengoServiceServer).EnableSite(ctx, req.(*SiteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrengoService_DisableSite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SiteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrengoServiceServer).DisableSite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrengoService_DisableSite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrengoServiceServer).DisableSite(ctx, req.(*SiteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrengoService_ArmSite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SiteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrengoServiceServer).ArmSite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrengoService_ArmSite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrengoServiceServer).ArmSite(ctx, req.(*SiteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrengoService_DisarmSite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SiteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrengoServiceServer).DisarmSite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrengoService_DisarmSite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrengoServiceServer).DisarmSite(ctx, req.(*SiteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrengoService_GetSiteEnv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SiteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrengoServiceServer).GetSiteEnv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrengoService_GetSiteEnv_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrengoServiceServer).GetSiteEnv(ctx, req.(*SiteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrengoService_UpdateSiteEnv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSiteEnvRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrengoServiceServer).UpdateSiteEnv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrengoService_UpdateSiteEnv_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrengoServiceServer).UpdateSiteEnv(ctx, req.(*UpdateSiteEnvRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrengoService_Stats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrengoServiceServer).Stats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrengoService_Stats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrengoServiceServer).Stats(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrengoService_Storage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrengoServiceServer).Storage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrengoService_Storage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrengoServiceServer).Storage(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrengoService_GetSysInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrengoServiceServer).GetSysInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrengoService_GetSysInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrengoServiceServer).GetSysInfo(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrengoService_GetHardware_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrengoServiceServer).GetHardware(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrengoService_GetHardware_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrengoServiceServer).GetHardware(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrengoService_ExportSite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SiteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrengoServiceServer).ExportSite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrengoService_ExportSite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrengoServiceServer).ExportSite(ctx, req.(*SiteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrengoService_ImportSite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportSiteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrengoServiceServer).ImportSite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrengoService_ImportSite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrengoServiceServer).ImportSite(ctx, req.(*ImportSiteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrengoService_MigrateSite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MigrateSiteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrengoServiceServer).MigrateSite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrengoService_MigrateSite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrengoServiceServer).MigrateSite(ctx, req.(*MigrateSiteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrengoService_MigrateAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MigrateAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrengoServiceServer).MigrateAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrengoService_MigrateAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrengoServiceServer).MigrateAll(ctx, req.(*MigrateAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrengoService_ExportNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrengoServiceServer).ExportNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrengoService_ExportNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrengoServiceServer).ExportNode(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrengoService_ImportNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrengoServiceServer).ImportNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrengoService_ImportNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrengoServiceServer).ImportNode(ctx, req.(*ImportNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrengoService_ListExports_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrengoServiceServer).ListExports(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrengoService_ListExports_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrengoServiceServer).ListExports(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrengoService_DownloadExport_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadExportRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GrengoServiceServer).DownloadExport(m, &grpc.GenericServerStream[DownloadExportRequest, FileChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GrengoService_DownloadExportServer = grpc.ServerStreamingServer[FileChunk]

func _GrengoService_DeleteExport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteExportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrengoServiceServer).DeleteExport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrengoService_DeleteExport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrengoServiceServer).DeleteExport(ctx, req.(*DeleteExportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrengoService_ListJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrengoServiceServer).ListJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrengoService_ListJobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrengoServiceServer).ListJobs(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrengoService_GetJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrengoServiceServer).GetJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrengoService_GetJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrengoServiceServer).GetJob(ctx, req.(*GetJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrengoService_DownloadJob_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadJobRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GrengoServiceServer).DownloadJob(m, &grpc.GenericServerStream[DownloadJobRequest, FileChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GrengoService_DownloadJobServer = grpc.ServerStreamingServer[FileChunk]

func _GrengoService_WatchJobs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EmptyRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GrengoServiceServer).WatchJobs(m, &grpc.GenericServerStream[EmptyRequest, JobEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GrengoService_WatchJobsServer = grpc.ServerStreamingServer[JobEvent]

func _GrengoService_SendAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrengoServiceServer).SendAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrengoService_SendAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrengoServiceServer).SendAction(ctx, req.(*SendActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrengoService_PasscodeStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrengoServiceServer).PasscodeStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrengoService_PasscodeStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrengoServiceServer).PasscodeStatus(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrengoService_VerifyPasscode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyPasscodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrengoServiceServer).VerifyPasscode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrengoService_VerifyPasscode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrengoServiceServer).VerifyPasscode(ctx, req.(*VerifyPasscodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GrengoService_ServiceDesc is the grpc.ServiceDesc for GrengoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GrengoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grengo.grpc.GrengoService",
	HandlerType: (*GrengoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListSites",
			Handler:    _GrengoService_ListSites_Handler,
		},
		{
			MethodName: "Exec",
			Handler:    _GrengoService_Exec_Handler,
		},
		{
			MethodName: "CreateSite",
			Handler:    _GrengoService_CreateSite_Handler,
		},
		{
			MethodName: "DeleteSite",
			Handler:    _GrengoService_DeleteSite_Handler,
		},
		{
			MethodName: "StartSite",
			Handler:    _GrengoService_StartSite_Handler,
		},
		{
			MethodName: "StopSite",
			Handler:    _GrengoService_StopSite_Handler,
		},
		{
			MethodName: "EnableSite",
			Handler:    _GrengoService_EnableSite_Handler,
		},
		{
			MethodName: "DisableSite",
			Handler:    _GrengoService_DisableSite_Handler,
		},
		{
			MethodName: "ArmSite",
			Handler:    _GrengoService_ArmSite_Handler,
		},
		{
			MethodName: "DisarmSite",
			Handler:    _GrengoService_DisarmSite_Handler,
		},
		{
			MethodName: "GetSiteEnv",
			Handler:    _GrengoService_GetSiteEnv_Handler,
		},
		{
			MethodName: "UpdateSiteEnv",
			Handler:    _GrengoService_UpdateSiteEnv_Handler,
		},
		{
			MethodName: "Stats",
			Handler:    _GrengoService_Stats_Handler,
		},
		{
			MethodName: "Storage",
			Handler:    _GrengoService_Storage_Handler,
		},
		{
			MethodName: "GetSysInfo",
			Handler:    _GrengoService_GetSysInfo_Handler,
		},
		{
			MethodName: "GetHardware",
			Handler:    _GrengoService_GetHardware_Handler,
		},
		{
			MethodName: "ExportSite",
			Handler:    _GrengoService_ExportSite_Handler,
		},
		{
			MethodName: "ImportSite",
			Handler:    _GrengoService_ImportSite_Handler,
		},
		{
			MethodName: "MigrateSite",
			Handler:    _GrengoService_MigrateSite_Handler,
		},
		{
			MethodName: "MigrateAll",
			Handler:    _GrengoService_MigrateAll_Handler,
		},
		{
			MethodName: "ExportNode",
			Handler:    _GrengoService_ExportNode_Handler,
		},
		{
			MethodName: "ImportNode",
			Handler:    _GrengoService_ImportNode_Handler,
		},
		{
			MethodName: "ListExports",
			Handler:    _GrengoService_ListExports_Handler,
		},
		{
			MethodName: "DeleteExport",
			Handler:    _GrengoService_DeleteExport_Handler,
		},
		{
			MethodName: "ListJobs",
			Handler:    _GrengoService_ListJobs_Handler,
		},
		{
			MethodName: "GetJob",
			Handler:    _GrengoService_GetJob_Handler,
		},
		{
			MethodName: "SendAction",
			Handler:    _GrengoService_SendAction_Handler,
		},
		{
			MethodName: "PasscodeStatus",
			Handler:    _GrengoService_PasscodeStatus_Handler,
		},
		{
			MethodName: "VerifyPasscode",
			Handler:    _GrengoService_VerifyPasscode_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ProvisionFrappe",
			Handler:       _GrengoService_ProvisionFrappe_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "DownloadExport",
			Handler:       _GrengoService_DownloadExport_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "DownloadJob",
			Handler:       _GrengoService_DownloadJob_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchJobs",
			Handler:       _GrengoService_WatchJobs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "grengo.proto",
}
