// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: grengo.proto

package grengo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmptyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyRequest) Reset() {
	*x = EmptyRequest{}
	mi := &file_grengo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRequest) ProtoMessage() {}

func (x *EmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grengo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRequest.ProtoReflect.Descriptor instead.
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return file_grengo_proto_rawDescGZIP(), []int{0}
}

type EmptyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyResponse) Reset() {
	*x = EmptyResponse{}
	mi := &file_grengo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyResponse) ProtoMessage() {}

func (x *EmptyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grengo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyResponse.ProtoReflect.Descriptor instead.
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return file_grengo_proto_rawDescGZIP(), []int{1}
}

type SiteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SiteRequest) Reset() {
	*x = SiteRequest{}
	mi := &file_grengo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SiteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiteRequest) ProtoMessage() {}

func (x *SiteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grengo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiteRequest.ProtoReflect.Descriptor instead.
func (*SiteRequest) Descriptor() ([]byte, []int) {
	return file_grengo_proto_rawDescGZIP(), []int{2}
}

func (x *SiteRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListSitesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSitesRequest) Reset() {
	*x = ListSitesRequest{}
	mi := &file_grengo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSitesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSitesRequest) ProtoMessage() {}

func (x *ListSitesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grengo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSitesRequest.ProtoReflect.Descriptor instead.
func (*ListSitesRequest) Descriptor() ([]byte, []int) {
	return file_grengo_proto_rawDescGZIP(), []int{3}
}

type ListSitesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SitesJson     string                 `protobuf:"bytes,1,opt,name=sites_json,json=sitesJson,proto3" json:"sites_json,omitempty"` // Keeping it simple for migration
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSitesResponse) Reset() {
	*x = ListSitesResponse{}
	mi := &file_grengo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSitesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSitesResponse) ProtoMessage() {}

func (x *ListSitesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grengo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSitesResponse.ProtoReflect.Descriptor instead.
func (*ListSitesResponse) Descriptor() ([]byte, []int) {
	return file_grengo_proto_rawDescGZIP(), []int{4}
}

func (x *ListSitesResponse) GetSitesJson() string {
	if x != nil {
		return x.SitesJson
	}
	return ""
}

type ExecRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Args          []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	mi := &file_grengo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grengo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_grengo_proto_rawDescGZIP(), []int{5}
}

func (x *ExecRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ExecRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

type ExecResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Output        string                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecResponse) Reset() {
	*x = ExecResponse{}
	mi := &file_grengo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResponse) ProtoMessage() {}

func (x *ExecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grengo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResponse.ProtoReflect.Descriptor instead.
func (*ExecResponse) Descriptor() ([]byte, []int) {
	return file_grengo_proto_rawDescGZIP(), []int{6}
}

func (x *ExecResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ExecResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *ExecResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CreateSiteRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Port           string                 `protobuf:"bytes,2,opt,name=port,proto3" json:"port,omitempty"`
	Domains        []string               `protobuf:"bytes,3,rep,name=domains,proto3" json:"domains,omitempty"`
	DbName         string                 `protobuf:"bytes,4,opt,name=db_name,json=dbName,proto3" json:"db_name,omitempty"`
	AdminPassword  string                 `protobuf:"bytes,5,opt,name=admin_password,json=adminPassword,proto3" json:"admin_password,omitempty"`
	AdminEmail     string                 `protobuf:"bytes,6,opt,name=admin_email,json=adminEmail,proto3" json:"admin_email,omitempty"`
	SessionTimeout string                 `protobuf:"bytes,7,opt,name=session_timeout,json=sessionTimeout,proto3" json:"session_timeout,omitempty"`
	Environment    string                 `protobuf:"bytes,8,opt,name=environment,proto3" json:"environment,omitempty"`
	Features       string                 `protobuf:"bytes,9,opt,name=features,proto3" json:"features,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateSiteRequest) Reset() {
	*x = CreateSiteRequest{}
	mi := &file_grengo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSiteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSiteRequest) ProtoMessage() {}

func (x *CreateSiteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grengo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSiteRequest.ProtoReflect.Descriptor instead.
func (*CreateSiteRequest) Descriptor() ([]byte, []int) {
	return file_grengo_proto_rawDescGZIP(), []int{7}
}

func (x *CreateSiteRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSiteRequest) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *CreateSiteRequest) GetDomains() []string {
	if x != nil {
		return x.Domains
	}
	return nil
}

func (x *CreateSiteRequest) GetDbName() string {
	if x != nil {
		return x.DbName
	}
	return ""
}

func (x *CreateSiteRequest) GetAdminPassword() string {
	if x != nil {
		return x.AdminPassword
	}
	return ""
}

func (x *CreateSiteRequest) GetAdminEmail() string {
	if x != nil {
		return x.AdminEmail
	}
	return ""
}

func (x *CreateSiteRequest) GetSessionTimeout() string {
	if x != nil {
		return x.SessionTimeout
	}
	return ""
}

func (x *CreateSiteRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *CreateSiteRequest) GetFeatures() string {
	if x != nil {
		return x.Features
	}
	return ""
}

type CreateSiteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSiteResponse) Reset() {
	*x = CreateSiteResponse{}
	mi := &file_grengo_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSiteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSiteResponse) ProtoMessage() {}

func (x *CreateSiteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grengo_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSiteResponse.ProtoReflect.Descriptor instead.
func (*CreateSiteResponse) Descriptor() ([]byte, []int) {
	return file_grengo_proto_rawDescGZIP(), []int{8}
}

type ProvisionFrappeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SiteName      string                 `protobuf:"bytes,1,opt,name=site_name,json=siteName,proto3" json:"site_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionFrappeRequest) Reset() {
	*x = ProvisionFrappeRequest{}
	mi := &file_grengo_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionFrappeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionFrappeRequest) ProtoMessage() {}

func (x *ProvisionFrappeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grengo_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionFrappeRequest.ProtoReflect.Descriptor instead.
func (*ProvisionFrappeRequest) Descriptor() ([]byte, []int) {
	return file_grengo_proto_rawDescGZIP(), []int{9}
}

func (x *ProvisionFrappeRequest) GetSiteName() string {
	if x != nil {
		return x.SiteName
	}
	return ""
}

type LogStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        string                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogStreamResponse) Reset() {
	*x = LogStreamResponse{}
	mi := &file_grengo_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogStreamResponse) ProtoMessage() {}

func (x *LogStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grengo_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogStreamResponse.ProtoReflect.Descriptor instead.
func (*LogStreamResponse) Descriptor() ([]byte, []int) {
	return file_grengo_proto_rawDescGZIP(), []int{10}
}

func (x *LogStreamResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

type GetSiteEnvResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSiteEnvResponse) Reset() {
	*x = GetSiteEnvResponse{}
	mi := &file_grengo_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSiteEnvResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSiteEnvResponse) ProtoMessage() {}

func (x *GetSiteEnvResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grengo_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSiteEnvResponse.ProtoReflect.Descriptor instead.
func (*GetSiteEnvResponse) Descriptor() ([]byte, []int) {
	return file_grengo_proto_rawDescGZIP(), []int{11}
}

func (x *GetSiteEnvResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type UpdateSiteEnvRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSiteEnvRequest) Reset() {
	*x = UpdateSiteEnvRequest{}
	mi := &file_grengo_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSiteEnvRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSiteEnvRequest) ProtoMessage() {}

func (x *UpdateSiteEnvRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grengo_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSiteEnvRequest.ProtoReflect.Descriptor instead.
func (*UpdateSiteEnvRequest) Descriptor() ([]byte, []int) {
	return file_grengo_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateSiteEnvRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateSiteEnvRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type StatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatsJson     string                 `protobuf:"bytes,1,opt,name=stats_json,json=statsJson,proto3" json:"stats_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_grengo_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grengo_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_grengo_proto_rawDescGZIP(), []int{13}
}

func (x *StatsResponse) GetStatsJson() string {
	if x != nil {
		return x.StatsJson
	}
	return ""
}

type StorageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StorageJson   string                 `protobuf:"bytes,1,opt,name=storage_json,json=storageJson,proto3" json:"storage_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageResponse) Reset() {
	*x = StorageResponse{}
	mi := &file_grengo_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageResponse) ProtoMessage() {}

func (x *StorageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grengo_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageResponse.ProtoReflect.Descriptor instead.
func (*StorageResponse) Descriptor() ([]byte, []int) {
	return file_grengo_proto_rawDescGZIP(), []int{14}
}

func (x *StorageResponse) GetStorageJson() string {
	if x != nil {
		return x.StorageJson
	}
	return ""
}

type SysInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SysinfoJson   string                 `protobuf:"bytes,1,opt,name=sysinfo_json,json=sysinfoJson,proto3" json:"sysinfo_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SysInfoResponse) Reset() {
	*x = SysInfoResponse{}
	mi := &file_grengo_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SysInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysInfoResponse) ProtoMessage() {}

func (x *SysInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grengo_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysInfoResponse.ProtoReflect.Descriptor instead.
func (*SysInfoResponse) Descriptor() ([]byte, []int) {
	return file_grengo_proto_rawDescGZIP(), []int{15}
}

func (x *SysInfoResponse) GetSysinfoJson() string {
	if x != nil {
		return x.SysinfoJson
	}
	return ""
}

type ExportSiteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportSiteResponse) Reset() {
	*x = ExportSiteResponse{}
	mi := &file_grengo_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportSiteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportSiteResponse) ProtoMessage() {}

func (x *ExportSiteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grengo_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportSiteResponse.ProtoReflect.Descriptor instead.
func (*ExportSiteResponse) Descriptor() ([]byte, []int) {
	return file_grengo_proto_rawDescGZIP(), []int{16}
}

func (x *ExportSiteResponse) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type ImportSiteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArchivePath   string                 `protobuf:"bytes,1,opt,name=archive_path,json=archivePath,proto3" json:"archive_path,omitempty"`
	NewName       string                 `protobuf:"bytes,2,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"`
	NewPort       string                 `protobuf:"bytes,3,opt,name=new_port,json=newPort,proto3" json:"new_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportSiteRequest) Reset() {
	*x = ImportSiteRequest{}
	mi := &file_grengo_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportSiteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportSiteRequest) ProtoMessage() {}

func (x *ImportSiteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grengo_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportSiteRequest.ProtoReflect.Descriptor instead.
func (*ImportSiteRequest) Descriptor() ([]byte, []int) {
	return file_grengo_proto_rawDescGZIP(), []int{17}
}

func (x *ImportSiteRequest) GetArchivePath() string {
	if x != nil {
		return x.ArchivePath
	}
	return ""
}

func (x *ImportSiteRequest) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

func (x *ImportSiteRequest) GetNewPort() string {
	if x != nil {
		return x.NewPort
	}
	return ""
}

type ImportSiteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportSiteResponse) Reset() {
	*x = ImportSiteResponse{}
	mi := &file_grengo_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportSiteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportSiteResponse) ProtoMessage() {}

func (x *ImportSiteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grengo_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportSiteResponse.ProtoReflect.Descriptor instead.
func (*ImportSiteResponse) Descriptor() ([]byte, []int) {
	return file_grengo_proto_rawDescGZIP(), []int{18}
}

func (x *ImportSiteResponse) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type MigrateSiteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Rebuild       bool                   `protobuf:"varint,2,opt,name=rebuild,proto3" json:"rebuild,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigrateSiteRequest) Reset() {
	*x = MigrateSiteRequest{}
	mi := &file_grengo_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrateSiteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrateSiteRequest) ProtoMessage() {}

func (x *MigrateSiteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grengo_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrateSiteRequest.ProtoReflect.Descriptor instead.
func (*MigrateSiteRequest) Descriptor() ([]byte, []int) {
	return file_grengo_proto_rawDescGZIP(), []int{19}
}

func (x *MigrateSiteRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MigrateSiteRequest) GetRebuild() bool {
	if x != nil {
		return x.Rebuild
	}
	return false
}

type MigrateSiteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultJson    string                 `protobuf:"bytes,1,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigrateSiteResponse) Reset() {
	*x = MigrateSiteResponse{}
	mi := &file_grengo_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrateSiteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrateSiteResponse) ProtoMessage() {}

func (x *MigrateSiteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grengo_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrateSiteResponse.ProtoReflect.Descriptor instead.
func (*MigrateSiteResponse) Descriptor() ([]byte, []int) {
	return file_grengo_proto_rawDescGZIP(), []int{20}
}

func (x *MigrateSiteResponse) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

type MigrateAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rebuild       bool                   `protobuf:"varint,1,opt,name=rebuild,proto3" json:"rebuild,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigrateAllRequest) Reset() {
	*x = MigrateAllRequest{}
	mi := &file_grengo_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrateAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrateAllRequest) ProtoMessage() {}

func (x *MigrateAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grengo_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrateAllRequest.ProtoReflect.Descriptor instead.
func (*MigrateAllRequest) Descriptor() ([]byte, []int) {
	return file_grengo_proto_rawDescGZIP(), []int{21}
}

func (x *MigrateAllRequest) GetRebuild() bool {
	if x != nil {
		return x.Rebuild
	}
	return false
}

type MigrateAllResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultJson    string                 `protobuf:"bytes,1,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigrateAllResponse) Reset() {
	*x = MigrateAllResponse{}
	mi := &file_grengo_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrateAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrateAllResponse) ProtoMessage() {}

func (x *MigrateAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grengo_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrateAllResponse.ProtoReflect.Descriptor instead.
func (*MigrateAllResponse) Descriptor() ([]byte, []int) {
	return file_grengo_proto_rawDescGZIP(), []int{22}
}

func (x *MigrateAllResponse) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

type ExportNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportNodeResponse) Reset() {
	*x = ExportNodeResponse{}
	mi := &file_grengo_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportNodeResponse) ProtoMessage() {}

func (x *ExportNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grengo_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportNodeResponse.ProtoReflect.Descriptor instead.
func (*ExportNodeResponse) Descriptor() ([]byte, []int) {
	return file_grengo_proto_rawDescGZIP(), []int{23}
}

func (x *ExportNodeResponse) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type ImportNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArchivePath   string                 `protobuf:"bytes,1,opt,name=archive_path,json=archivePath,proto3" json:"archive_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportNodeRequest) Reset() {
	*x = ImportNodeRequest{}
	mi := &file_grengo_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportNodeRequest) ProtoMessage() {}

func (x *ImportNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grengo_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportNodeRequest.ProtoReflect.Descriptor instead.
func (*ImportNodeRequest) Descriptor() ([]byte, []int) {
	return file_grengo_proto_rawDescGZIP(), []int{24}
}

func (x *ImportNodeRequest) GetArchivePath() string {
	if x != nil {
		return x.ArchivePath
	}
	return ""
}

type ImportNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportNodeResponse) Reset() {
	*x = ImportNodeResponse{}
	mi := &file_grengo_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportNodeResponse) ProtoMessage() {}

func (x *ImportNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grengo_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportNodeResponse.ProtoReflect.Descriptor instead.
func (*ImportNodeResponse) Descriptor() ([]byte, []int) {
	return file_grengo_proto_rawDescGZIP(), []int{25}
}

func (x *ImportNodeResponse) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type ListExportsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExportsJson   string                 `protobuf:"bytes,1,opt,name=exports_json,json=exportsJson,proto3" json:"exports_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExportsResponse) Reset() {
	*x = ListExportsResponse{}
	mi := &file_grengo_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExportsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExportsResponse) ProtoMessage() {}

func (x *ListExportsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grengo_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExportsResponse.ProtoReflect.Descriptor instead.
func (*ListExportsResponse) Descriptor() ([]byte, []int) {
	return file_grengo_proto_rawDescGZIP(), []int{26}
}

func (x *ListExportsResponse) GetExportsJson() string {
	if x != nil {
		return x.ExportsJson
	}
	return ""
}

type DownloadExportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadExportRequest) Reset() {
	*x = DownloadExportRequest{}
	mi := &file_grengo_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadExportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadExportRequest) ProtoMessage() {}

func (x *DownloadExportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grengo_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadExportRequest.ProtoReflect.Descriptor instead.
func (*DownloadExportRequest) Descriptor() ([]byte, []int) {
	return file_grengo_proto_rawDescGZIP(), []int{27}
}

func (x *DownloadExportRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type DeleteExportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteExportRequest) Reset() {
	*x = DeleteExportRequest{}
	mi := &file_grengo_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteExportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExportRequest) ProtoMessage() {}

func (x *DeleteExportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grengo_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteExportRequest.ProtoReflect.Descriptor instead.
func (*DeleteExportRequest) Descriptor() ([]byte, []int) {
	return file_grengo_proto_rawDescGZIP(), []int{28}
}

func (x *DeleteExportRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type FileChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         []byte                 `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	mi := &file_grengo_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_grengo_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunk.ProtoReflect.Descriptor instead.
func (*FileChunk) Descriptor() ([]byte, []int) {
	return file_grengo_proto_rawDescGZIP(), []int{29}
}

func (x *FileChunk) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

type ListJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobsJson      string                 `protobuf:"bytes,1,opt,name=jobs_json,json=jobsJson,proto3" json:"jobs_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsResponse) Reset() {
	*x = ListJobsResponse{}
	mi := &file_grengo_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsResponse) ProtoMessage() {}

func (x *ListJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grengo_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsResponse.ProtoReflect.Descriptor instead.
func (*ListJobsResponse) Descriptor() ([]byte, []int) {
	return file_grengo_proto_rawDescGZIP(), []int{30}
}

func (x *ListJobsResponse) GetJobsJson() string {
	if x != nil {
		return x.JobsJson
	}
	return ""
}

type GetJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobRequest) Reset() {
	*x = GetJobRequest{}
	mi := &file_grengo_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobRequest) ProtoMessage() {}

func (x *GetJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grengo_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobRequest.ProtoReflect.Descriptor instead.
func (*GetJobRequest) Descriptor() ([]byte, []int) {
	return file_grengo_proto_rawDescGZIP(), []int{31}
}

func (x *GetJobRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobJson       string                 `protobuf:"bytes,1,opt,name=job_json,json=jobJson,proto3" json:"job_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobResponse) Reset() {
	*x = GetJobResponse{}
	mi := &file_grengo_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobResponse) ProtoMessage() {}

func (x *GetJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grengo_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobResponse.ProtoReflect.Descriptor instead.
func (*GetJobResponse) Descriptor() ([]byte, []int) {
	return file_grengo_proto_rawDescGZIP(), []int{32}
}

func (x *GetJobResponse) GetJobJson() string {
	if x != nil {
		return x.JobJson
	}
	return ""
}

type DownloadJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadJobRequest) Reset() {
	*x = DownloadJobRequest{}
	mi := &file_grengo_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadJobRequest) ProtoMessage() {}

func (x *DownloadJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grengo_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadJobRequest.ProtoReflect.Descriptor instead.
func (*DownloadJobRequest) Descriptor() ([]byte, []int) {
	return file_grengo_proto_rawDescGZIP(), []int{33}
}

func (x *DownloadJobRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type JobEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventJson     string                 `protobuf:"bytes,1,opt,name=event_json,json=eventJson,proto3" json:"event_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobEvent) Reset() {
	*x = JobEvent{}
	mi := &file_grengo_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobEvent) ProtoMessage() {}

func (x *JobEvent) ProtoReflect() protoreflect.Message {
	mi := &file_grengo_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobEvent.ProtoReflect.Descriptor instead.
func (*JobEvent) Descriptor() ([]byte, []int) {
	return file_grengo_proto_rawDescGZIP(), []int{34}
}

func (x *JobEvent) GetEventJson() string {
	if x != nil {
		return x.EventJson
	}
	return ""
}

type SendActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        []byte                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendActionRequest) Reset() {
	*x = SendActionRequest{}
	mi := &file_grengo_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendActionRequest) ProtoMessage() {}

func (x *SendActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grengo_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendActionRequest.ProtoReflect.Descriptor instead.
func (*SendActionRequest) Descriptor() ([]byte, []int) {
	return file_grengo_proto_rawDescGZIP(), []int{35}
}

func (x *SendActionRequest) GetAction() []byte {
	if x != nil {
		return x.Action
	}
	return nil
}

type PasscodeStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configured    bool                   `protobuf:"varint,1,opt,name=configured,proto3" json:"configured,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PasscodeStatusResponse) Reset() {
	*x = PasscodeStatusResponse{}
	mi := &file_grengo_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PasscodeStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasscodeStatusResponse) ProtoMessage() {}

func (x *PasscodeStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grengo_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasscodeStatusResponse.ProtoReflect.Descriptor instead.
func (*PasscodeStatusResponse) Descriptor() ([]byte, []int) {
	return file_grengo_proto_rawDescGZIP(), []int{36}
}

func (x *PasscodeStatusResponse) GetConfigured() bool {
	if x != nil {
		return x.Configured
	}
	return false
}

type VerifyPasscodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	P1            string                 `protobuf:"bytes,1,opt,name=p1,proto3" json:"p1,omitempty"`
	P2            string                 `protobuf:"bytes,2,opt,name=p2,proto3" json:"p2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyPasscodeRequest) Reset() {
	*x = VerifyPasscodeRequest{}
	mi := &file_grengo_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyPasscodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyPasscodeRequest) ProtoMessage() {}

func (x *VerifyPasscodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grengo_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyPasscodeRequest.ProtoReflect.Descriptor instead.
func (*VerifyPasscodeRequest) Descriptor() ([]byte, []int) {
	return file_grengo_proto_rawDescGZIP(), []int{37}
}

func (x *VerifyPasscodeRequest) GetP1() string {
	if x != nil {
		return x.P1
	}
	return ""
}

func (x *VerifyPasscodeRequest) GetP2() string {
	if x != nil {
		return x.P2
	}
	return ""
}

type VerifyPasscodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyPasscodeResponse) Reset() {
	*x = VerifyPasscodeResponse{}
	mi := &file_grengo_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyPasscodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyPasscodeResponse) ProtoMessage() {}

func (x *VerifyPasscodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grengo_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyPasscodeResponse.ProtoReflect.Descriptor instead.
func (*VerifyPasscodeResponse) Descriptor() ([]byte, []int) {
	return file_grengo_proto_rawDescGZIP(), []int{38}
}

func (x *VerifyPasscodeResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

var File_grengo_proto protoreflect.FileDescriptor

const file_grengo_proto_rawDesc = "" +
	"\n" +
	"\fgrengo.proto\x12\vgrengo.grpc\"\x0e\n" +
	"\fEmptyRequest\"\x0f\n" +
	"\rEmptyResponse\"!\n" +
	"\vSiteRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x12\n" +
	"\x10ListSitesRequest\"2\n" +
	"\x11ListSitesResponse\x12\x1d\n" +
	"\n" +
	"sites_json\x18\x01 \x01(\tR\tsitesJson\";\n" +
	"\vExecRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\"i\n" +
	"\fExecResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\x9d\x02\n" +
	"\x11CreateSiteRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04port\x18\x02 \x01(\tR\x04port\x12\x18\n" +
	"\adomains\x18\x03 \x03(\tR\adomains\x12\x17\n" +
	"\adb_name\x18\x04 \x01(\tR\x06dbName\x12%\n" +
	"\x0eadmin_password\x18\x05 \x01(\tR\radminPassword\x12\x1f\n" +
	"\vadmin_email\x18\x06 \x01(\tR\n" +
	"adminEmail\x12'\n" +
	"\x0fsession_timeout\x18\a \x01(\tR\x0esessionTimeout\x12 \n" +
	"\venvironment\x18\b \x01(\tR\venvironment\x12\x1a\n" +
	"\bfeatures\x18\t \x01(\tR\bfeatures\"\x14\n" +
	"\x12CreateSiteResponse\"5\n" +
	"\x16ProvisionFrappeRequest\x12\x1b\n" +
	"\tsite_name\x18\x01 \x01(\tR\bsiteName\"+\n" +
	"\x11LogStreamResponse\x12\x16\n" +
	"\x06output\x18\x01 \x01(\tR\x06output\".\n" +
	"\x12GetSiteEnvResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\"D\n" +
	"\x14UpdateSiteEnvRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\".\n" +
	"\rStatsResponse\x12\x1d\n" +
	"\n" +
	"stats_json\x18\x01 \x01(\tR\tstatsJson\"4\n" +
	"\x0fStorageResponse\x12!\n" +
	"\fstorage_json\x18\x01 \x01(\tR\vstorageJson\"4\n" +
	"\x0fSysInfoResponse\x12!\n" +
	"\fsysinfo_json\x18\x01 \x01(\tR\vsysinfoJson\"0\n" +
	"\x12ExportSiteResponse\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\"l\n" +
	"\x11ImportSiteRequest\x12!\n" +
	"\farchive_path\x18\x01 \x01(\tR\varchivePath\x12\x19\n" +
	"\bnew_name\x18\x02 \x01(\tR\anewName\x12\x19\n" +
	"\bnew_port\x18\x03 \x01(\tR\anewPort\"0\n" +
	"\x12ImportSiteResponse\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\"B\n" +
	"\x12MigrateSiteRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\arebuild\x18\x02 \x01(\bR\arebuild\"6\n" +
	"\x13MigrateSiteResponse\x12\x1f\n" +
	"\vresult_json\x18\x01 \x01(\tR\n" +
	"resultJson\"-\n" +
	"\x11MigrateAllRequest\x12\x18\n" +
	"\arebuild\x18\x01 \x01(\bR\arebuild\"5\n" +
	"\x12MigrateAllResponse\x12\x1f\n" +
	"\vresult_json\x18\x01 \x01(\tR\n" +
	"resultJson\"0\n" +
	"\x12ExportNodeResponse\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\"6\n" +
	"\x11ImportNodeRequest\x12!\n" +
	"\farchive_path\x18\x01 \x01(\tR\varchivePath\"0\n" +
	"\x12ImportNodeResponse\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\"8\n" +
	"\x13ListExportsResponse\x12!\n" +
	"\fexports_json\x18\x01 \x01(\tR\vexportsJson\"3\n" +
	"\x15DownloadExportRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\"1\n" +
	"\x13DeleteExportRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\"!\n" +
	"\tFileChunk\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\fR\x05chunk\"/\n" +
	"\x10ListJobsResponse\x12\x1b\n" +
	"\tjobs_json\x18\x01 \x01(\tR\bjobsJson\"\x1f\n" +
	"\rGetJobRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"+\n" +
	"\x0eGetJobResponse\x12\x19\n" +
	"\bjob_json\x18\x01 \x01(\tR\ajobJson\"$\n" +
	"\x12DownloadJobRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\")\n" +
	"\bJobEvent\x12\x1d\n" +
	"\n" +
	"event_json\x18\x01 \x01(\tR\teventJson\"+\n" +
	"\x11SendActionRequest\x12\x16\n" +
	"\x06action\x18\x01 \x01(\fR\x06action\"8\n" +
	"\x16PasscodeStatusResponse\x12\x1e\n" +
	"\n" +
	"configured\x18\x01 \x01(\bR\n" +
	"configured\"7\n" +
	"\x15VerifyPasscodeRequest\x12\x0e\n" +
	"\x02p1\x18\x01 \x01(\tR\x02p1\x12\x0e\n" +
	"\x02p2\x18\x02 \x01(\tR\x02p2\".\n" +
	"\x16VerifyPasscodeResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid2\xc3\x12\n" +
	"\rGrengoService\x12J\n" +
	"\tListSites\x12\x1d.grengo.grpc.ListSitesRequest\x1a\x1e.grengo.grpc.ListSitesResponse\x12;\n" +
	"\x04Exec\x12\x18.grengo.grpc.ExecRequest\x1a\x19.grengo.grpc.ExecResponse\x12M\n" +
	"\n" +
	"CreateSite\x12\x1e.grengo.grpc.CreateSiteRequest\x1a\x1f.grengo.grpc.CreateSiteResponse\x12X\n" +
	"\x0fProvisionFrappe\x12#.grengo.grpc.ProvisionFrappeRequest\x1a\x1e.grengo.grpc.LogStreamResponse0\x01\x12B\n" +
	"\n" +
	"DeleteSite\x12\x18.grengo.grpc.SiteRequest\x1a\x1a.grengo.grpc.EmptyResponse\x12A\n" +
	"\tStartSite\x12\x18.grengo.grpc.SiteRequest\x1a\x1a.grengo.grpc.EmptyResponse\x12@\n" +
	"\bStopSite\x12\x18.grengo.grpc.SiteRequest\x1a\x1a.grengo.grpc.EmptyResponse\x12B\n" +
	"\n" +
	"EnableSite\x12\x18.grengo.grpc.SiteRequest\x1a\x1a.grengo.grpc.EmptyResponse\x12C\n" +
	"\vDisableSite\x12\x18.grengo.grpc.SiteRequest\x1a\x1a.grengo.grpc.EmptyResponse\x12?\n" +
	"\aArmSite\x12\x18.grengo.grpc.SiteRequest\x1a\x1a.grengo.grpc.EmptyResponse\x12B\n" +
	"\n" +
	"DisarmSite\x12\x18.grengo.grpc.SiteRequest\x1a\x1a.grengo.grpc.EmptyResponse\x12G\n" +
	"\n" +
	"GetSiteEnv\x12\x18.grengo.grpc.SiteRequest\x1a\x1f.grengo.grpc.GetSiteEnvResponse\x12N\n" +
	"\rUpdateSiteEnv\x12!.grengo.grpc.UpdateSiteEnvRequest\x1a\x1a.grengo.grpc.EmptyResponse\x12>\n" +
	"\x05Stats\x12\x19.grengo.grpc.EmptyRequest\x1a\x1a.grengo.grpc.StatsResponse\x12B\n" +
	"\aStorage\x12\x19.grengo.grpc.EmptyRequest\x1a\x1c.grengo.grpc.StorageResponse\x12E\n" +
	"\n" +
	"GetSysInfo\x12\x19.grengo.grpc.EmptyRequest\x1a\x1c.grengo.grpc.SysInfoResponse\x12G\n" +
	"\n" +
	"ExportSite\x12\x18.grengo.grpc.SiteRequest\x1a\x1f.grengo.grpc.ExportSiteResponse\x12M\n" +
	"\n" +
	"ImportSite\x12\x1e.grengo.grpc.ImportSiteRequest\x1a\x1f.grengo.grpc.ImportSiteResponse\x12P\n" +
	"\vMigrateSite\x12\x1f.grengo.grpc.MigrateSiteRequest\x1a .grengo.grpc.MigrateSiteResponse\x12M\n" +
	"\n" +
	"MigrateAll\x12\x1e.grengo.grpc.MigrateAllRequest\x1a\x1f.grengo.grpc.MigrateAllResponse\x12H\n" +
	"\n" +
	"ExportNode\x12\x19.grengo.grpc.EmptyRequest\x1a\x1f.grengo.grpc.ExportNodeResponse\x12M\n" +
	"\n" +
	"ImportNode\x12\x1e.grengo.grpc.ImportNodeRequest\x1a\x1f.grengo.grpc.ImportNodeResponse\x12J\n" +
	"\vListExports\x12\x19.grengo.grpc.EmptyRequest\x1a .grengo.grpc.ListExportsResponse\x12N\n" +
	"\x0eDownloadExport\x12\".grengo.grpc.DownloadExportRequest\x1a\x16.grengo.grpc.FileChunk0\x01\x12L\n" +
	"\fDeleteExport\x12 .grengo.grpc.DeleteExportRequest\x1a\x1a.grengo.grpc.EmptyResponse\x12D\n" +
	"\bListJobs\x12\x19.grengo.grpc.EmptyRequest\x1a\x1d.grengo.grpc.ListJobsResponse\x12A\n" +
	"\x06GetJob\x12\x1a.grengo.grpc.GetJobRequest\x1a\x1b.grengo.grpc.GetJobResponse\x12H\n" +
	"\vDownloadJob\x12\x1f.grengo.grpc.DownloadJobRequest\x1a\x16.grengo.grpc.FileChunk0\x01\x12?\n" +
	"\tWatchJobs\x12\x19.grengo.grpc.EmptyRequest\x1a\x15.grengo.grpc.JobEvent0\x01\x12H\n" +
	"\n" +
	"SendAction\x12\x1e.grengo.grpc.SendActionRequest\x1a\x1a.grengo.grpc.EmptyResponse\x12P\n" +
	"\x0ePasscodeStatus\x12\x19.grengo.grpc.EmptyRequest\x1a#.grengo.grpc.PasscodeStatusResponse\x12Y\n" +
	"\x0eVerifyPasscode\x12\".grengo.grpc.VerifyPasscodeRequest\x1a#.grengo.grpc.VerifyPasscodeResponseB\x1eZ\x1cgithub.com/skaia/grpc/grengob\x06proto3"

var (
	file_grengo_proto_rawDescOnce sync.Once
	file_grengo_proto_rawDescData []byte
)

func file_grengo_proto_rawDescGZIP() []byte {
	file_grengo_proto_rawDescOnce.Do(func() {
		file_grengo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grengo_proto_rawDesc), len(file_grengo_proto_rawDesc)))
	})
	return file_grengo_proto_rawDescData
}

var file_grengo_proto_msgTypes = make([]protoimpl.MessageInfo, 39)
var file_grengo_proto_goTypes = []any{
	(*EmptyRequest)(nil),           // 0: grengo.grpc.EmptyRequest
	(*EmptyResponse)(nil),          // 1: grengo.grpc.EmptyResponse
	(*SiteRequest)(nil),            // 2: grengo.grpc.SiteRequest
	(*ListSitesRequest)(nil),       // 3: grengo.grpc.ListSitesRequest
	(*ListSitesResponse)(nil),      // 4: grengo.grpc.ListSitesResponse
	(*ExecRequest)(nil),            // 5: grengo.grpc.ExecRequest
	(*ExecResponse)(nil),           // 6: grengo.grpc.ExecResponse
	(*CreateSiteRequest)(nil),      // 7: grengo.grpc.CreateSiteRequest
	(*CreateSiteResponse)(nil),     // 8: grengo.grpc.CreateSiteResponse
	(*ProvisionFrappeRequest)(nil), // 9: grengo.grpc.ProvisionFrappeRequest
	(*LogStreamResponse)(nil),      // 10: grengo.grpc.LogStreamResponse
	(*GetSiteEnvResponse)(nil),     // 11: grengo.grpc.GetSiteEnvResponse
	(*UpdateSiteEnvRequest)(nil),   // 12: grengo.grpc.UpdateSiteEnvRequest
	(*StatsResponse)(nil),          // 13: grengo.grpc.StatsResponse
	(*StorageResponse)(nil),        // 14: grengo.grpc.StorageResponse
	(*SysInfoResponse)(nil),        // 15: grengo.grpc.SysInfoResponse
	(*ExportSiteResponse)(nil),     // 16: grengo.grpc.ExportSiteResponse
	(*ImportSiteRequest)(nil),      // 17: grengo.grpc.ImportSiteRequest
	(*ImportSiteResponse)(nil),     // 18: grengo.grpc.ImportSiteResponse
	(*MigrateSiteRequest)(nil),     // 19: grengo.grpc.MigrateSiteRequest
	(*MigrateSiteResponse)(nil),    // 20: grengo.grpc.MigrateSiteResponse
	(*MigrateAllRequest)(nil),      // 21: grengo.grpc.MigrateAllRequest
	(*MigrateAllResponse)(nil),     // 22: grengo.grpc.MigrateAllResponse
	(*ExportNodeResponse)(nil),     // 23: grengo.grpc.ExportNodeResponse
	(*ImportNodeRequest)(nil),      // 24: grengo.grpc.ImportNodeRequest
	(*ImportNodeResponse)(nil),     // 25: grengo.grpc.ImportNodeResponse
	(*ListExportsResponse)(nil),    // 26: grengo.grpc.ListExportsResponse
	(*DownloadExportRequest)(nil),  // 27: grengo.grpc.DownloadExportRequest
	(*DeleteExportRequest)(nil),    // 28: grengo.grpc.DeleteExportRequest
	(*FileChunk)(nil),              // 29: grengo.grpc.FileChunk
	(*ListJobsResponse)(nil),       // 30: grengo.grpc.ListJobsResponse
	(*GetJobRequest)(nil),          // 31: grengo.grpc.GetJobRequest
	(*GetJobResponse)(nil),         // 32: grengo.grpc.GetJobResponse
	(*DownloadJobRequest)(nil),     // 33: grengo.grpc.DownloadJobRequest
	(*JobEvent)(nil),               // 34: grengo.grpc.JobEvent
	(*SendActionRequest)(nil),      // 35: grengo.grpc.SendActionRequest
	(*PasscodeStatusResponse)(nil), // 36: grengo.grpc.PasscodeStatusResponse
	(*VerifyPasscodeRequest)(nil),  // 37: grengo.grpc.VerifyPasscodeRequest
	(*VerifyPasscodeResponse)(nil), // 38: grengo.grpc.VerifyPasscodeResponse
}
var file_grengo_proto_depIdxs = []int32{
	3,  // 0: grengo.grpc.GrengoService.ListSites:input_type -> grengo.grpc.ListSitesRequest
	5,  // 1: grengo.grpc.GrengoService.Exec:input_type -> grengo.grpc.ExecRequest
	7,  // 2: grengo.grpc.GrengoService.CreateSite:input_type -> grengo.grpc.CreateSiteRequest
	9,  // 3: grengo.grpc.GrengoService.ProvisionFrappe:input_type -> grengo.grpc.ProvisionFrappeRequest
	2,  // 4: grengo.grpc.GrengoService.DeleteSite:input_type -> grengo.grpc.SiteRequest
	2,  // 5: grengo.grpc.GrengoService.StartSite:input_type -> grengo.grpc.SiteRequest
	2,  // 6: grengo.grpc.GrengoService.StopSite:input_type -> grengo.grpc.SiteRequest
	2,  // 7: grengo.grpc.GrengoService.EnableSite:input_type -> grengo.grpc.SiteRequest
	2,  // 8: grengo.grpc.GrengoService.DisableSite:input_type -> grengo.grpc.SiteRequest
	2,  // 9: grengo.grpc.GrengoService.ArmSite:input_type -> grengo.grpc.SiteRequest
	2,  // 10: grengo.grpc.GrengoService.DisarmSite:input_type -> grengo.grpc.SiteRequest
	2,  // 11: grengo.grpc.GrengoService.GetSiteEnv:input_type -> grengo.grpc.SiteRequest
	12, // 12: grengo.grpc.GrengoService.UpdateSiteEnv:input_type -> grengo.grpc.UpdateSiteEnvRequest
	0,  // 13: grengo.grpc.GrengoService.Stats:input_type -> grengo.grpc.EmptyRequest
	0,  // 14: grengo.grpc.GrengoService.Storage:input_type -> grengo.grpc.EmptyRequest
	0,  // 15: grengo.grpc.GrengoService.GetSysInfo:input_type -> grengo.grpc.EmptyRequest
	2,  // 16: grengo.grpc.GrengoService.ExportSite:input_type -> grengo.grpc.SiteRequest
	17, // 17: grengo.grpc.GrengoService.ImportSite:input_type -> grengo.grpc.ImportSiteRequest
	19, // 18: grengo.grpc.GrengoService.MigrateSite:input_type -> grengo.grpc.MigrateSiteRequest
	21, // 19: grengo.grpc.GrengoService.MigrateAll:input_type -> grengo.grpc.MigrateAllRequest
	0,  // 20: grengo.grpc.GrengoService.ExportNode:input_type -> grengo.grpc.EmptyRequest
	24, // 21: grengo.grpc.GrengoService.ImportNode:input_type -> grengo.grpc.ImportNodeRequest
	0,  // 22: grengo.grpc.GrengoService.ListExports:input_type -> grengo.grpc.EmptyRequest
	27, // 23: grengo.grpc.GrengoService.DownloadExport:input_type -> grengo.grpc.DownloadExportRequest
	28, // 24: grengo.grpc.GrengoService.DeleteExport:input_type -> grengo.grpc.DeleteExportRequest
	0,  // 25: grengo.grpc.GrengoService.ListJobs:input_type -> grengo.grpc.EmptyRequest
	31, // 26: grengo.grpc.GrengoService.GetJob:input_type -> grengo.grpc.GetJobRequest
	33, // 27: grengo.grpc.GrengoService.DownloadJob:input_type -> grengo.grpc.DownloadJobRequest
	0,  // 28: grengo.grpc.GrengoService.WatchJobs:input_type -> grengo.grpc.EmptyRequest
	35, // 29: grengo.grpc.GrengoService.SendAction:input_type -> grengo.grpc.SendActionRequest
	0,  // 30: grengo.grpc.GrengoService.PasscodeStatus:input_type -> grengo.grpc.EmptyRequest
	37, // 31: grengo.grpc.GrengoService.VerifyPasscode:input_type -> grengo.grpc.VerifyPasscodeRequest
	4,  // 32: grengo.grpc.GrengoService.ListSites:output_type -> grengo.grpc.ListSitesResponse
	6,  // 33: grengo.grpc.GrengoService.Exec:output_type -> grengo.grpc.ExecResponse
	8,  // 34: grengo.grpc.GrengoService.CreateSite:output_type -> grengo.grpc.CreateSiteResponse
	10, // 35: grengo.grpc.GrengoService.ProvisionFrappe:output_type -> grengo.grpc.LogStreamResponse
	1,  // 36: grengo.grpc.GrengoService.DeleteSite:output_type -> grengo.grpc.EmptyResponse
	1,  // 37: grengo.grpc.GrengoService.StartSite:output_type -> grengo.grpc.EmptyResponse
	1,  // 38: grengo.grpc.GrengoService.StopSite:output_type -> grengo.grpc.EmptyResponse
	1,  // 39: grengo.grpc.GrengoService.EnableSite:output_type -> grengo.grpc.EmptyResponse
	1,  // 40: grengo.grpc.GrengoService.DisableSite:output_type -> grengo.grpc.EmptyResponse
	1,  // 41: grengo.grpc.GrengoService.ArmSite:output_type -> grengo.grpc.EmptyResponse
	1,  // 42: grengo.grpc.GrengoService.DisarmSite:output_type -> grengo.grpc.EmptyResponse
	11, // 43: grengo.grpc.GrengoService.GetSiteEnv:output_type -> grengo.grpc.GetSiteEnvResponse
	1,  // 44: grengo.grpc.GrengoService.UpdateSiteEnv:output_type -> grengo.grpc.EmptyResponse
	13, // 45: grengo.grpc.GrengoService.Stats:output_type -> grengo.grpc.StatsResponse
	14, // 46: grengo.grpc.GrengoService.Storage:output_type -> grengo.grpc.StorageResponse
	15, // 47: grengo.grpc.GrengoService.GetSysInfo:output_type -> grengo.grpc.SysInfoResponse
	16, // 48: grengo.grpc.GrengoService.ExportSite:output_type -> grengo.grpc.ExportSiteResponse
	18, // 49: grengo.grpc.GrengoService.ImportSite:output_type -> grengo.grpc.ImportSiteResponse
	20, // 50: grengo.grpc.GrengoService.MigrateSite:output_type -> grengo.grpc.MigrateSiteResponse
	22, // 51: grengo.grpc.GrengoService.MigrateAll:output_type -> grengo.grpc.MigrateAllResponse
	23, // 52: grengo.grpc.GrengoService.ExportNode:output_type -> grengo.grpc.ExportNodeResponse
	25, // 53: grengo.grpc.GrengoService.ImportNode:output_type -> grengo.grpc.ImportNodeResponse
	26, // 54: grengo.grpc.GrengoService.ListExports:output_type -> grengo.grpc.ListExportsResponse
	29, // 55: grengo.grpc.GrengoService.DownloadExport:output_type -> grengo.grpc.FileChunk
	1,  // 56: grengo.grpc.GrengoService.DeleteExport:output_type -> grengo.grpc.EmptyResponse
	30, // 57: grengo.grpc.GrengoService.ListJobs:output_type -> grengo.grpc.ListJobsResponse
	32, // 58: grengo.grpc.GrengoService.GetJob:output_type -> grengo.grpc.GetJobResponse
	29, // 59: grengo.grpc.GrengoService.DownloadJob:output_type -> grengo.grpc.FileChunk
	34, // 60: grengo.grpc.GrengoService.WatchJobs:output_type -> grengo.grpc.JobEvent
	1,  // 61: grengo.grpc.GrengoService.SendAction:output_type -> grengo.grpc.EmptyResponse
	36, // 62: grengo.grpc.GrengoService.PasscodeStatus:output_type -> grengo.grpc.PasscodeStatusResponse
	38, // 63: grengo.grpc.GrengoService.VerifyPasscode:output_type -> grengo.grpc.VerifyPasscodeResponse
	32, // [32:64] is the sub-list for method output_type
	0,  // [0:32] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_grengo_proto_init() }
func file_grengo_proto_init() {
	if File_grengo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grengo_proto_rawDesc), len(file_grengo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   39,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grengo_proto_goTypes,
		DependencyIndexes: file_grengo_proto_depIdxs,
		MessageInfos:      file_grengo_proto_msgTypes,
	}.Build()
	File_grengo_proto = out.File
	file_grengo_proto_goTypes = nil
	file_grengo_proto_depIdxs = nil
}
