// Code generated by backend/cmd/section-contract-gen; DO NOT EDIT.

package s_registry

// NormalizedSectionType is a canonical page-section discriminator.
type NormalizedSectionType string

const (
	SectionTypeHero            NormalizedSectionType = "hero"
	SectionTypeCardGroup       NormalizedSectionType = "card_group"
	SectionTypeStatCards       NormalizedSectionType = "stat_cards"
	SectionTypeSocialLinks     NormalizedSectionType = "social_links"
	SectionTypeImageGallery    NormalizedSectionType = "image_gallery"
	SectionTypeFeatureGrid     NormalizedSectionType = "feature_grid"
	SectionTypeCTA             NormalizedSectionType = "cta"
	SectionTypeEventHighlights NormalizedSectionType = "event_highlights"
	SectionTypeProfileCard     NormalizedSectionType = "profile_card"
	SectionTypeRichText        NormalizedSectionType = "rich_text"
	SectionTypeCodeEditor      NormalizedSectionType = "code_editor"
	SectionTypeDataSources     NormalizedSectionType = "data_sources"
	SectionTypeDerivedSection  NormalizedSectionType = "derived_section"
	SectionTypeCustomSection   NormalizedSectionType = "custom_section"
	SectionTypeForm            NormalizedSectionType = "form"
	SectionTypeQA              NormalizedSectionType = "qa"
	SectionTypeSurvey          NormalizedSectionType = "survey"
	SectionTypePoll            NormalizedSectionType = "poll"
	SectionTypeVote            NormalizedSectionType = "vote"
)

// NormalizedSectionConfig is implemented by every generated config DTO.
type NormalizedSectionConfig interface{ isNormalizedSectionConfig() }

type HeroConfig struct {
	BackgroundImage *string  `json:"background_image,omitempty"`
	TintColor       *string  `json:"tint_color,omitempty"`
	TintOpacity     *float64 `json:"tint_opacity,omitempty"`
	Variant         *int64   `json:"variant,omitempty"`
	Videos          []string `json:"videos,omitempty"`
}

func (*HeroConfig) isNormalizedSectionConfig() {}

type CardGroupConfig struct{}

func (*CardGroupConfig) isNormalizedSectionConfig() {}

type StatCardsConfig struct{}

func (*StatCardsConfig) isNormalizedSectionConfig() {}

type SocialLinksConfig struct {
	Links []struct {
		Icon string `json:"icon"`
		URL  string `json:"url"`
	} `json:"links"`
}

func (*SocialLinksConfig) isNormalizedSectionConfig() {}

type ImageGalleryConfig struct {
	Albums []struct {
		Key   string `json:"key"`
		Label string `json:"label"`
	} `json:"albums"`
	DefaultCardWidth string `json:"default_card_width"`
}

func (*ImageGalleryConfig) isNormalizedSectionConfig() {}

type FeatureGridConfig struct{}

func (*FeatureGridConfig) isNormalizedSectionConfig() {}

type CTAConfig struct{}

func (*CTAConfig) isNormalizedSectionConfig() {}

type EventHighlightsConfig struct{}

func (*EventHighlightsConfig) isNormalizedSectionConfig() {}

type ProfileCardConfig struct {
	AvatarURL   *string  `json:"avatar_url,omitempty"`
	BannerURL   *string  `json:"banner_url,omitempty"`
	Checklist   []string `json:"checklist"`
	Description *string  `json:"description,omitempty"`
	Links       []struct {
		Label string `json:"label"`
		URL   string `json:"url"`
	} `json:"links"`
	ProfileName     *string `json:"profile_name,omitempty"`
	ProfileSubtitle *string `json:"profile_subtitle,omitempty"`
}

func (*ProfileCardConfig) isNormalizedSectionConfig() {}

type RichTextConfig struct {
	Content string `json:"content"`
}

func (*RichTextConfig) isNormalizedSectionConfig() {}

type CodeEditorConfig struct {
	Code     string `json:"code"`
	Filename string `json:"filename"`
	Language string `json:"language"`
}

func (*CodeEditorConfig) isNormalizedSectionConfig() {}

type DataSourcesConfig struct{}

func (*DataSourcesConfig) isNormalizedSectionConfig() {}

type DerivedSectionConfig struct {
	Bindings       map[string]string `json:"bindings,omitempty"`
	CardTemplate   map[string]any    `json:"card_template,omitempty"`
	ColumnMap      map[string]string `json:"column_map,omitempty"`
	Columns        *int64            `json:"columns,omitempty"`
	ComponentGroup *struct {
		Gap      float64          `json:"gap"`
		Items    []map[string]any `json:"items"`
		MaxWidth float64          `json:"max_width"`
		Wrapper  map[string]any   `json:"wrapper,omitempty"`
	} `json:"component_group,omitempty"`
	ComponentType    *string          `json:"component_type,omitempty"`
	ComponentVersion *int64           `json:"component_version,omitempty"`
	DatasourceID     *int64           `json:"datasource_id,omitempty"`
	EventHooks       []map[string]any `json:"event_hooks,omitempty"`
	RenderAs         *string          `json:"render_as,omitempty"`
	RowKeyColumn     *string          `json:"row_key_column,omitempty"`
	RowOverrides     map[string]any   `json:"row_overrides,omitempty"`
	StyleOverrides   map[string]any   `json:"style_overrides,omitempty"`
}

func (*DerivedSectionConfig) isNormalizedSectionConfig() {}

type CustomSectionConfig struct {
	Bindings         map[string]string `json:"bindings,omitempty"`
	CardTemplate     map[string]any    `json:"card_template,omitempty"`
	ColumnMap        map[string]string `json:"column_map,omitempty"`
	Columns          *int64            `json:"columns,omitempty"`
	ComponentGroup   map[string]any    `json:"component_group,omitempty"`
	ComponentType    *string           `json:"component_type,omitempty"`
	ComponentVersion *int64            `json:"component_version,omitempty"`
	CustomSectionID  *int64            `json:"custom_section_id,omitempty"`
	DatasourceID     *int64            `json:"datasource_id,omitempty"`
	EventHooks       []map[string]any  `json:"event_hooks,omitempty"`
	RenderAs         *string           `json:"render_as,omitempty"`
	RowKeyColumn     *string           `json:"row_key_column,omitempty"`
	RowOverrides     map[string]any    `json:"row_overrides,omitempty"`
	StyleOverrides   map[string]any    `json:"style_overrides,omitempty"`
}

func (*CustomSectionConfig) isNormalizedSectionConfig() {}

type FormConfig struct {
	Fields []struct {
		Description *string          `json:"description,omitempty"`
		Key         string           `json:"key"`
		Label       string           `json:"label"`
		Max         *float64         `json:"max,omitempty"`
		Min         *float64         `json:"min,omitempty"`
		Options     []map[string]any `json:"options,omitempty"`
		Placeholder *string          `json:"placeholder,omitempty"`
		Required    *bool            `json:"required,omitempty"`
		Type        string           `json:"type"`
	} `json:"fields"`
	ResponseLimit    int64  `json:"response_limit"`
	ResultVisibility string `json:"result_visibility"`
	Status           string `json:"status"`
	SubmitLabel      string `json:"submit_label"`
	SuccessText      string `json:"success_text"`
}

func (*FormConfig) isNormalizedSectionConfig() {}

type QAConfig struct {
	Fields           []map[string]any `json:"fields"`
	Moderation       bool             `json:"moderation"`
	ResponseLimit    int64            `json:"response_limit"`
	ResultVisibility string           `json:"result_visibility"`
	Status           string           `json:"status"`
	SubmitLabel      string           `json:"submit_label"`
	SuccessText      string           `json:"success_text"`
}

func (*QAConfig) isNormalizedSectionConfig() {}

type SurveyConfig struct {
	Fields           []map[string]any `json:"fields"`
	ResponseLimit    int64            `json:"response_limit"`
	ResultVisibility string           `json:"result_visibility"`
	Status           string           `json:"status"`
	SubmitLabel      string           `json:"submit_label"`
	SuccessText      string           `json:"success_text"`
}

func (*SurveyConfig) isNormalizedSectionConfig() {}

type PollConfig struct {
	Fields           []map[string]any `json:"fields"`
	ResponseLimit    int64            `json:"response_limit"`
	ResultVisibility string           `json:"result_visibility"`
	Status           string           `json:"status"`
	SubmitLabel      string           `json:"submit_label"`
	SuccessText      string           `json:"success_text"`
}

func (*PollConfig) isNormalizedSectionConfig() {}

type VoteConfig struct {
	Fields           []map[string]any `json:"fields"`
	ResponseLimit    int64            `json:"response_limit"`
	ResultVisibility string           `json:"result_visibility"`
	Status           string           `json:"status"`
	SubmitLabel      string           `json:"submit_label"`
	SuccessText      string           `json:"success_text"`
}

func (*VoteConfig) isNormalizedSectionConfig() {}

var normalizedSectionConfigFactories = map[NormalizedSectionType]func() NormalizedSectionConfig{
	SectionTypeHero:            func() NormalizedSectionConfig { return &HeroConfig{} },
	SectionTypeCardGroup:       func() NormalizedSectionConfig { return &CardGroupConfig{} },
	SectionTypeStatCards:       func() NormalizedSectionConfig { return &StatCardsConfig{} },
	SectionTypeSocialLinks:     func() NormalizedSectionConfig { return &SocialLinksConfig{} },
	SectionTypeImageGallery:    func() NormalizedSectionConfig { return &ImageGalleryConfig{} },
	SectionTypeFeatureGrid:     func() NormalizedSectionConfig { return &FeatureGridConfig{} },
	SectionTypeCTA:             func() NormalizedSectionConfig { return &CTAConfig{} },
	SectionTypeEventHighlights: func() NormalizedSectionConfig { return &EventHighlightsConfig{} },
	SectionTypeProfileCard:     func() NormalizedSectionConfig { return &ProfileCardConfig{} },
	SectionTypeRichText:        func() NormalizedSectionConfig { return &RichTextConfig{} },
	SectionTypeCodeEditor:      func() NormalizedSectionConfig { return &CodeEditorConfig{} },
	SectionTypeDataSources:     func() NormalizedSectionConfig { return &DataSourcesConfig{} },
	SectionTypeDerivedSection:  func() NormalizedSectionConfig { return &DerivedSectionConfig{} },
	SectionTypeCustomSection:   func() NormalizedSectionConfig { return &CustomSectionConfig{} },
	SectionTypeForm:            func() NormalizedSectionConfig { return &FormConfig{} },
	SectionTypeQA:              func() NormalizedSectionConfig { return &QAConfig{} },
	SectionTypeSurvey:          func() NormalizedSectionConfig { return &SurveyConfig{} },
	SectionTypePoll:            func() NormalizedSectionConfig { return &PollConfig{} },
	SectionTypeVote:            func() NormalizedSectionConfig { return &VoteConfig{} },
}

// ParseNormalizedSectionType rejects unknown discriminators.
func ParseNormalizedSectionType(value string) (NormalizedSectionType, bool) {
	sectionType := NormalizedSectionType(value)
	_, ok := normalizedSectionConfigFactories[sectionType]
	return sectionType, ok
}
